/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type InstallPluginInput,
    InstallPluginInputFromJSON,
    InstallPluginInputToJSON,
} from '../models/InstallPluginInput';
import {
    type PluginInfo,
    PluginInfoFromJSON,
    PluginInfoToJSON,
} from '../models/PluginInfo';

export interface DeletePluginsPluginIdRequest {
    /**
     * 
     */
    pluginId: string;
}

export interface GetPluginsRequest {
    /**
     * 
     */
    all?: boolean;
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    match?: string;
    /**
     * 
     */
    prefix?: string;
    /**
     * 
     */
    r?: string;
    /**
     * 
     */
    start?: number;
}

export interface GetPluginsPluginIdStatusRequest {
    /**
     * 
     */
    pluginId: string;
}

export interface PostPluginsPluginIdDisableRequest {
    /**
     * 
     */
    pluginId: string;
}

export interface PostPluginsPluginIdEnableRequest {
    /**
     * 
     */
    pluginId: string;
}

export interface PostPluginsPluginIdReloadRequest {
    /**
     * 
     */
    pluginId: string;
}

export interface PutPluginsPluginIdRequest {
    /**
     * 
     */
    pluginId: string;
    /**
     * 
     */
    installPluginInput?: InstallPluginInput;
}

/**
 * 
 */
export class PluginsApi extends runtime.BaseAPI {

    /**
     * Creates request options for deletePluginsPluginId without sending the request
     */
    async deletePluginsPluginIdRequestOpts(requestParameters: DeletePluginsPluginIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pluginId'] == null) {
            throw new runtime.RequiredError(
                'pluginId',
                'Required parameter "pluginId" was null or undefined when calling deletePluginsPluginId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/plugins/{plugin-id}`;
        urlPath = urlPath.replace('{plugin-id}', encodeURIComponent(String(requestParameters['pluginId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Disables a plugin on the Gerrit server.
     * Disable Plugin
     */
    async deletePluginsPluginIdRaw(requestParameters: DeletePluginsPluginIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginInfo>> {
        const requestOptions = await this.deletePluginsPluginIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PluginInfoFromJSON(jsonValue));
    }

    /**
     * Disables a plugin on the Gerrit server.
     * Disable Plugin
     */
    async deletePluginsPluginId(requestParameters: DeletePluginsPluginIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginInfo> {
        const response = await this.deletePluginsPluginIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPlugins without sending the request
     */
    async getPluginsRequestOpts(requestParameters: GetPluginsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['all'] != null) {
            queryParameters['all'] = requestParameters['all'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['match'] != null) {
            queryParameters['match'] = requestParameters['match'];
        }

        if (requestParameters['prefix'] != null) {
            queryParameters['prefix'] = requestParameters['prefix'];
        }

        if (requestParameters['r'] != null) {
            queryParameters['r'] = requestParameters['r'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/plugins`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists the plugins installed on the Gerrit server. Only the enabled plugins are returned unless the all option is specified.
     * List Plugins
     */
    async getPluginsRaw(requestParameters: GetPluginsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: PluginInfo; }>> {
        const requestOptions = await this.getPluginsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, PluginInfoFromJSON));
    }

    /**
     * Lists the plugins installed on the Gerrit server. Only the enabled plugins are returned unless the all option is specified.
     * List Plugins
     */
    async getPlugins(requestParameters: GetPluginsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: PluginInfo; }> {
        const response = await this.getPluginsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPluginsPluginIdStatus without sending the request
     */
    async getPluginsPluginIdStatusRequestOpts(requestParameters: GetPluginsPluginIdStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pluginId'] == null) {
            throw new runtime.RequiredError(
                'pluginId',
                'Required parameter "pluginId" was null or undefined when calling getPluginsPluginIdStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/plugins/{plugin-id}/status`;
        urlPath = urlPath.replace('{plugin-id}', encodeURIComponent(String(requestParameters['pluginId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getPluginsPluginIdStatusRaw(requestParameters: GetPluginsPluginIdStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginInfo>> {
        const requestOptions = await this.getPluginsPluginIdStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PluginInfoFromJSON(jsonValue));
    }

    /**
     */
    async getPluginsPluginIdStatus(requestParameters: GetPluginsPluginIdStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginInfo> {
        const response = await this.getPluginsPluginIdStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postPluginsPluginIdDisable without sending the request
     */
    async postPluginsPluginIdDisableRequestOpts(requestParameters: PostPluginsPluginIdDisableRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pluginId'] == null) {
            throw new runtime.RequiredError(
                'pluginId',
                'Required parameter "pluginId" was null or undefined when calling postPluginsPluginIdDisable().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/plugins/{plugin-id}/disable`;
        urlPath = urlPath.replace('{plugin-id}', encodeURIComponent(String(requestParameters['pluginId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async postPluginsPluginIdDisableRaw(requestParameters: PostPluginsPluginIdDisableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginInfo>> {
        const requestOptions = await this.postPluginsPluginIdDisableRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PluginInfoFromJSON(jsonValue));
    }

    /**
     */
    async postPluginsPluginIdDisable(requestParameters: PostPluginsPluginIdDisableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginInfo> {
        const response = await this.postPluginsPluginIdDisableRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postPluginsPluginIdEnable without sending the request
     */
    async postPluginsPluginIdEnableRequestOpts(requestParameters: PostPluginsPluginIdEnableRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pluginId'] == null) {
            throw new runtime.RequiredError(
                'pluginId',
                'Required parameter "pluginId" was null or undefined when calling postPluginsPluginIdEnable().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/plugins/{plugin-id}/enable`;
        urlPath = urlPath.replace('{plugin-id}', encodeURIComponent(String(requestParameters['pluginId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async postPluginsPluginIdEnableRaw(requestParameters: PostPluginsPluginIdEnableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginInfo>> {
        const requestOptions = await this.postPluginsPluginIdEnableRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PluginInfoFromJSON(jsonValue));
    }

    /**
     */
    async postPluginsPluginIdEnable(requestParameters: PostPluginsPluginIdEnableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginInfo> {
        const response = await this.postPluginsPluginIdEnableRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postPluginsPluginIdReload without sending the request
     */
    async postPluginsPluginIdReloadRequestOpts(requestParameters: PostPluginsPluginIdReloadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pluginId'] == null) {
            throw new runtime.RequiredError(
                'pluginId',
                'Required parameter "pluginId" was null or undefined when calling postPluginsPluginIdReload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/plugins/{plugin-id}/reload`;
        urlPath = urlPath.replace('{plugin-id}', encodeURIComponent(String(requestParameters['pluginId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async postPluginsPluginIdReloadRaw(requestParameters: PostPluginsPluginIdReloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginInfo>> {
        const requestOptions = await this.postPluginsPluginIdReloadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PluginInfoFromJSON(jsonValue));
    }

    /**
     */
    async postPluginsPluginIdReload(requestParameters: PostPluginsPluginIdReloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginInfo> {
        const response = await this.postPluginsPluginIdReloadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putPluginsPluginId without sending the request
     */
    async putPluginsPluginIdRequestOpts(requestParameters: PutPluginsPluginIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pluginId'] == null) {
            throw new runtime.RequiredError(
                'pluginId',
                'Required parameter "pluginId" was null or undefined when calling putPluginsPluginId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/plugins/{plugin-id}`;
        urlPath = urlPath.replace('{plugin-id}', encodeURIComponent(String(requestParameters['pluginId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InstallPluginInputToJSON(requestParameters['installPluginInput']),
        };
    }

    /**
     * Installs a new plugin on the Gerrit server. If a plugin with the specified name already exists it is overwritten. Note: if the plugin provides its own name in the MANIFEST file, then the plugin name from the MANIFEST file has precedence over the \\{plugin-id\\} above.
     * Install Plugin
     */
    async putPluginsPluginIdRaw(requestParameters: PutPluginsPluginIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginInfo>> {
        const requestOptions = await this.putPluginsPluginIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PluginInfoFromJSON(jsonValue));
    }

    /**
     * Installs a new plugin on the Gerrit server. If a plugin with the specified name already exists it is overwritten. Note: if the plugin provides its own name in the MANIFEST file, then the plugin name from the MANIFEST file has precedence over the \\{plugin-id\\} above.
     * Install Plugin
     */
    async putPluginsPluginId(requestParameters: PutPluginsPluginIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginInfo> {
        const response = await this.putPluginsPluginIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
