/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type InstallPluginInput,
    InstallPluginInputFromJSON,
    InstallPluginInputToJSON,
} from '../models/InstallPluginInput';
import {
    type PluginInfo,
    PluginInfoFromJSON,
    PluginInfoToJSON,
} from '../models/PluginInfo';

export interface DeletePluginsPluginIdRequest {
    /**
     * 
     */
    pluginId: string;
}

export interface GetPluginsRequest {
    /**
     * 
     */
    all?: boolean;
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    match?: string;
    /**
     * 
     */
    prefix?: string;
    /**
     * 
     */
    r?: string;
    /**
     * 
     */
    start?: number;
}

export interface GetPluginsPluginIdGerritStatusRequest {
    /**
     * 
     */
    pluginId: string;
}

export interface PostPluginsPluginIdGerritDisableRequest {
    /**
     * 
     */
    pluginId: string;
}

export interface PostPluginsPluginIdGerritEnableRequest {
    /**
     * 
     */
    pluginId: string;
}

export interface PostPluginsPluginIdGerritReloadRequest {
    /**
     * 
     */
    pluginId: string;
}

export interface PutPluginsPluginIdRequest {
    /**
     * 
     */
    pluginId: string;
    /**
     * 
     */
    installPluginInput?: InstallPluginInput;
}

/**
 * 
 */
export class PluginsApi extends runtime.BaseAPI {

    /**
     * Creates request options for deletePluginsPluginId without sending the request
     */
    async deletePluginsPluginIdRequestOpts(requestParameters: DeletePluginsPluginIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pluginId'] == null) {
            throw new runtime.RequiredError(
                'pluginId',
                'Required parameter "pluginId" was null or undefined when calling deletePluginsPluginId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/plugins/{plugin-id}`;
        urlPath = urlPath.replace('{plugin-id}', encodeURIComponent(String(requestParameters['pluginId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Disables a plugin on the Gerrit server.
     * Disable Plugin
     */
    async deletePluginsPluginIdRaw(requestParameters: DeletePluginsPluginIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginInfo>> {
        const requestOptions = await this.deletePluginsPluginIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PluginInfoFromJSON(jsonValue));
    }

    /**
     * Disables a plugin on the Gerrit server.
     * Disable Plugin
     */
    async deletePluginsPluginId(requestParameters: DeletePluginsPluginIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginInfo> {
        const response = await this.deletePluginsPluginIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPlugins without sending the request
     */
    async getPluginsRequestOpts(requestParameters: GetPluginsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['all'] != null) {
            queryParameters['all'] = requestParameters['all'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['match'] != null) {
            queryParameters['match'] = requestParameters['match'];
        }

        if (requestParameters['prefix'] != null) {
            queryParameters['prefix'] = requestParameters['prefix'];
        }

        if (requestParameters['r'] != null) {
            queryParameters['r'] = requestParameters['r'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/plugins`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists the plugins installed on the Gerrit server. Only the enabled plugins are returned unless the all option is specified.
     * List Plugins
     */
    async getPluginsRaw(requestParameters: GetPluginsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: PluginInfo; }>> {
        const requestOptions = await this.getPluginsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, PluginInfoFromJSON));
    }

    /**
     * Lists the plugins installed on the Gerrit server. Only the enabled plugins are returned unless the all option is specified.
     * List Plugins
     */
    async getPlugins(requestParameters: GetPluginsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: PluginInfo; }> {
        const response = await this.getPluginsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPluginsPluginIdGerritStatus without sending the request
     */
    async getPluginsPluginIdGerritStatusRequestOpts(requestParameters: GetPluginsPluginIdGerritStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pluginId'] == null) {
            throw new runtime.RequiredError(
                'pluginId',
                'Required parameter "pluginId" was null or undefined when calling getPluginsPluginIdGerritStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/plugins/{plugin-id}/gerrit~status`;
        urlPath = urlPath.replace('{plugin-id}', encodeURIComponent(String(requestParameters['pluginId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the status of a plugin on the Gerrit server.
     * Get Plugin Status
     */
    async getPluginsPluginIdGerritStatusRaw(requestParameters: GetPluginsPluginIdGerritStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginInfo>> {
        const requestOptions = await this.getPluginsPluginIdGerritStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PluginInfoFromJSON(jsonValue));
    }

    /**
     * Retrieves the status of a plugin on the Gerrit server.
     * Get Plugin Status
     */
    async getPluginsPluginIdGerritStatus(requestParameters: GetPluginsPluginIdGerritStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginInfo> {
        const response = await this.getPluginsPluginIdGerritStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postPluginsPluginIdGerritDisable without sending the request
     */
    async postPluginsPluginIdGerritDisableRequestOpts(requestParameters: PostPluginsPluginIdGerritDisableRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pluginId'] == null) {
            throw new runtime.RequiredError(
                'pluginId',
                'Required parameter "pluginId" was null or undefined when calling postPluginsPluginIdGerritDisable().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/plugins/{plugin-id}/gerrit~disable`;
        urlPath = urlPath.replace('{plugin-id}', encodeURIComponent(String(requestParameters['pluginId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Disable Plugin
     */
    async postPluginsPluginIdGerritDisableRaw(requestParameters: PostPluginsPluginIdGerritDisableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginInfo>> {
        const requestOptions = await this.postPluginsPluginIdGerritDisableRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PluginInfoFromJSON(jsonValue));
    }

    /**
     * Disable Plugin
     */
    async postPluginsPluginIdGerritDisable(requestParameters: PostPluginsPluginIdGerritDisableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginInfo> {
        const response = await this.postPluginsPluginIdGerritDisableRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postPluginsPluginIdGerritEnable without sending the request
     */
    async postPluginsPluginIdGerritEnableRequestOpts(requestParameters: PostPluginsPluginIdGerritEnableRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pluginId'] == null) {
            throw new runtime.RequiredError(
                'pluginId',
                'Required parameter "pluginId" was null or undefined when calling postPluginsPluginIdGerritEnable().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/plugins/{plugin-id}/gerrit~enable`;
        urlPath = urlPath.replace('{plugin-id}', encodeURIComponent(String(requestParameters['pluginId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Enables a plugin on the Gerrit server.
     * Enable Plugin
     */
    async postPluginsPluginIdGerritEnableRaw(requestParameters: PostPluginsPluginIdGerritEnableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginInfo>> {
        const requestOptions = await this.postPluginsPluginIdGerritEnableRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PluginInfoFromJSON(jsonValue));
    }

    /**
     * Enables a plugin on the Gerrit server.
     * Enable Plugin
     */
    async postPluginsPluginIdGerritEnable(requestParameters: PostPluginsPluginIdGerritEnableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginInfo> {
        const response = await this.postPluginsPluginIdGerritEnableRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postPluginsPluginIdGerritReload without sending the request
     */
    async postPluginsPluginIdGerritReloadRequestOpts(requestParameters: PostPluginsPluginIdGerritReloadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pluginId'] == null) {
            throw new runtime.RequiredError(
                'pluginId',
                'Required parameter "pluginId" was null or undefined when calling postPluginsPluginIdGerritReload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/plugins/{plugin-id}/gerrit~reload`;
        urlPath = urlPath.replace('{plugin-id}', encodeURIComponent(String(requestParameters['pluginId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Reloads a plugin on the Gerrit server.
     * Reload Plugin
     */
    async postPluginsPluginIdGerritReloadRaw(requestParameters: PostPluginsPluginIdGerritReloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginInfo>> {
        const requestOptions = await this.postPluginsPluginIdGerritReloadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PluginInfoFromJSON(jsonValue));
    }

    /**
     * Reloads a plugin on the Gerrit server.
     * Reload Plugin
     */
    async postPluginsPluginIdGerritReload(requestParameters: PostPluginsPluginIdGerritReloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginInfo> {
        const response = await this.postPluginsPluginIdGerritReloadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putPluginsPluginId without sending the request
     */
    async putPluginsPluginIdRequestOpts(requestParameters: PutPluginsPluginIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pluginId'] == null) {
            throw new runtime.RequiredError(
                'pluginId',
                'Required parameter "pluginId" was null or undefined when calling putPluginsPluginId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/plugins/{plugin-id}`;
        urlPath = urlPath.replace('{plugin-id}', encodeURIComponent(String(requestParameters['pluginId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InstallPluginInputToJSON(requestParameters['installPluginInput']),
        };
    }

    /**
     * Installs a new plugin on the Gerrit server. If a plugin with the specified name already exists it is overwritten. Note: if the plugin provides its own name in the MANIFEST file, then the plugin name from the MANIFEST file has precedence over the \\{plugin-id\\} above.
     * Install Plugin
     */
    async putPluginsPluginIdRaw(requestParameters: PutPluginsPluginIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PluginInfo>> {
        const requestOptions = await this.putPluginsPluginIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PluginInfoFromJSON(jsonValue));
    }

    /**
     * Installs a new plugin on the Gerrit server. If a plugin with the specified name already exists it is overwritten. Note: if the plugin provides its own name in the MANIFEST file, then the plugin name from the MANIFEST file has precedence over the \\{plugin-id\\} above.
     * Install Plugin
     */
    async putPluginsPluginId(requestParameters: PutPluginsPluginIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PluginInfo> {
        const response = await this.putPluginsPluginIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
