/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessCheckInfo
 */
export interface AccessCheckInfo {
    /**
     * 
     */
    message?: string;
    /**
     * 
     */
    status?: number;
    /**
     * 
     */
    debugLogs?: Array<string>;
}

/**
 * Check if a given object implements the AccessCheckInfo interface.
 */
export function instanceOfAccessCheckInfo(value: object): value is AccessCheckInfo {
    return true;
}

export function AccessCheckInfoFromJSON(json: any): AccessCheckInfo {
    return AccessCheckInfoFromJSONTyped(json, false);
}

export function AccessCheckInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessCheckInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
        'debugLogs': json['debug_logs'] == null ? undefined : json['debug_logs'],
    };
}

export function AccessCheckInfoToJSON(json: any): AccessCheckInfo {
    return AccessCheckInfoToJSONTyped(json, false);
}

export function AccessCheckInfoToJSONTyped(value?: AccessCheckInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'status': value['status'],
        'debug_logs': value['debugLogs'],
    };
}

