/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountExternalIdInfo
 */
export interface AccountExternalIdInfo {
    /**
     * The account external id.
     */
    identity?: string;
    /**
     * The email address for the external id.
     */
    emailAddress?: string;
    /**
     * Whether the external id is trusted.
     */
    trusted?: boolean;
    /**
     * Whether the external id can be deleted by the calling user.
     */
    canDelete?: boolean;
}

/**
 * Check if a given object implements the AccountExternalIdInfo interface.
 */
export function instanceOfAccountExternalIdInfo(value: object): value is AccountExternalIdInfo {
    return true;
}

export function AccountExternalIdInfoFromJSON(json: any): AccountExternalIdInfo {
    return AccountExternalIdInfoFromJSONTyped(json, false);
}

export function AccountExternalIdInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountExternalIdInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'identity': json['identity'] == null ? undefined : json['identity'],
        'emailAddress': json['email_address'] == null ? undefined : json['email_address'],
        'trusted': json['trusted'] == null ? undefined : json['trusted'],
        'canDelete': json['can_delete'] == null ? undefined : json['can_delete'],
    };
}

export function AccountExternalIdInfoToJSON(json: any): AccountExternalIdInfo {
    return AccountExternalIdInfoToJSONTyped(json, false);
}

export function AccountExternalIdInfoToJSONTyped(value?: AccountExternalIdInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identity': value['identity'],
        'email_address': value['emailAddress'],
        'trusted': value['trusted'],
        'can_delete': value['canDelete'],
    };
}

