/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetadataInfo } from './MetadataInfo';
import {
    MetadataInfoFromJSON,
    MetadataInfoFromJSONTyped,
    MetadataInfoToJSON,
    MetadataInfoToJSONTyped,
} from './MetadataInfo';
import type { AccountDetailInfo } from './AccountDetailInfo';
import {
    AccountDetailInfoFromJSON,
    AccountDetailInfoFromJSONTyped,
    AccountDetailInfoToJSON,
    AccountDetailInfoToJSONTyped,
} from './AccountDetailInfo';
import type { GroupInfo } from './GroupInfo';
import {
    GroupInfoFromJSON,
    GroupInfoFromJSONTyped,
    GroupInfoToJSON,
    GroupInfoToJSONTyped,
} from './GroupInfo';
import type { AccountExternalIdInfo } from './AccountExternalIdInfo';
import {
    AccountExternalIdInfoFromJSON,
    AccountExternalIdInfoFromJSONTyped,
    AccountExternalIdInfoToJSON,
    AccountExternalIdInfoToJSONTyped,
} from './AccountExternalIdInfo';

/**
 * 
 * @export
 * @interface AccountStateInfo
 */
export interface AccountStateInfo {
    /**
     * The account details as AccountDetailInfo entity.
     */
    account?: AccountDetailInfo;
    /**
     * The global capabilities of the account as a CapabilityInfo entity. Not set if the permission backend doesn't use default capabilities.
     */
    capabilities?: { [key: string]: object; };
    /**
     * The groups that contain the account as a member as a list of GroupInfo entries.
     */
    groups?: Array<GroupInfo>;
    /**
     * The external IDs of the account as a list of AccountExternalIdInfo entities.
     */
    externalIds?: Array<AccountExternalIdInfo>;
    /**
     * Optional account metadata as a list of MetadataInfo entities. If and which metadata is provided depends on the Gerrit setup.
     */
    metadata?: Array<MetadataInfo>;
}

/**
 * Check if a given object implements the AccountStateInfo interface.
 */
export function instanceOfAccountStateInfo(value: object): value is AccountStateInfo {
    return true;
}

export function AccountStateInfoFromJSON(json: any): AccountStateInfo {
    return AccountStateInfoFromJSONTyped(json, false);
}

export function AccountStateInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountStateInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'] == null ? undefined : AccountDetailInfoFromJSON(json['account']),
        'capabilities': json['capabilities'] == null ? undefined : json['capabilities'],
        'groups': json['groups'] == null ? undefined : ((json['groups'] as Array<any>).map(GroupInfoFromJSON)),
        'externalIds': json['external_ids'] == null ? undefined : ((json['external_ids'] as Array<any>).map(AccountExternalIdInfoFromJSON)),
        'metadata': json['metadata'] == null ? undefined : ((json['metadata'] as Array<any>).map(MetadataInfoFromJSON)),
    };
}

export function AccountStateInfoToJSON(json: any): AccountStateInfo {
    return AccountStateInfoToJSONTyped(json, false);
}

export function AccountStateInfoToJSONTyped(value?: AccountStateInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': AccountDetailInfoToJSON(value['account']),
        'capabilities': value['capabilities'],
        'groups': value['groups'] == null ? undefined : ((value['groups'] as Array<any>).map(GroupInfoToJSON)),
        'external_ids': value['externalIds'] == null ? undefined : ((value['externalIds'] as Array<any>).map(AccountExternalIdInfoToJSON)),
        'metadata': value['metadata'] == null ? undefined : ((value['metadata'] as Array<any>).map(MetadataInfoToJSON)),
    };
}

