/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActionInfo
 */
export interface ActionInfo {
    /**
     * HTTP method to use with the action. Most actions use POST, PUT or DELETE to cause state changes.
     */
    method?: string;
    /**
     * Short title to display to a user describing the action. In the Gerrit web interface the label is used as the text on the button presented in the UI.
     */
    label?: string;
    /**
     * Longer text to display describing the action. In a web UI this should be the title attribute of the element, displaying when the user hovers the mouse.
     */
    title?: string;
    /**
     * If true the action is permitted at this time and the caller is likely allowed to execute it. This may change if state is updated at the server or permissions are modified. Not present if false.
     */
    enabled?: boolean;
    /**
     * Optional list of enabled options. + See the list of suppported options below.
     */
    enabledOptions?: Array<string>;
}

/**
 * Check if a given object implements the ActionInfo interface.
 */
export function instanceOfActionInfo(value: object): value is ActionInfo {
    return true;
}

export function ActionInfoFromJSON(json: any): ActionInfo {
    return ActionInfoFromJSONTyped(json, false);
}

export function ActionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'method': json['method'] == null ? undefined : json['method'],
        'label': json['label'] == null ? undefined : json['label'],
        'title': json['title'] == null ? undefined : json['title'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'enabledOptions': json['enabled_options'] == null ? undefined : json['enabled_options'],
    };
}

export function ActionInfoToJSON(json: any): ActionInfo {
    return ActionInfoToJSONTyped(json, false);
}

export function ActionInfoToJSONTyped(value?: ActionInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'method': value['method'],
        'label': value['label'],
        'title': value['title'],
        'enabled': value['enabled'],
        'enabled_options': value['enabledOptions'],
    };
}

