/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddSubgroupsInput
 */
export interface AddSubgroupsInput {
    /**
     * 
     */
    oneGroup?: string;
    /**
     * 
     */
    groups?: Array<string>;
}

/**
 * Check if a given object implements the AddSubgroupsInput interface.
 */
export function instanceOfAddSubgroupsInput(value: object): value is AddSubgroupsInput {
    return true;
}

export function AddSubgroupsInputFromJSON(json: any): AddSubgroupsInput {
    return AddSubgroupsInputFromJSONTyped(json, false);
}

export function AddSubgroupsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddSubgroupsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'oneGroup': json['_one_group'] == null ? undefined : json['_one_group'],
        'groups': json['groups'] == null ? undefined : json['groups'],
    };
}

export function AddSubgroupsInputToJSON(json: any): AddSubgroupsInput {
    return AddSubgroupsInputToJSONTyped(json, false);
}

export function AddSubgroupsInputToJSONTyped(value?: AddSubgroupsInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_one_group': value['oneGroup'],
        'groups': value['groups'],
    };
}

