/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupInfo } from './GroupInfo';
import {
    GroupInfoFromJSON,
    GroupInfoFromJSONTyped,
    GroupInfoToJSON,
    GroupInfoToJSONTyped,
} from './GroupInfo';

/**
 * 
 * @export
 * @interface AgreementInfo
 */
export interface AgreementInfo {
    /**
     * The unique name of the contributor agreement.
     */
    name?: string;
    /**
     * The description of the contributor agreement.
     */
    description?: string;
    /**
     * The URL of the contributor agreement.
     */
    url?: string;
    /**
     * The group to which a user that signs the contributor agreement online is added automatically as a GroupInfo entity. If not set, users cannot sign the contributor agreement online.
     */
    autoVerifyGroup?: GroupInfo;
}

/**
 * Check if a given object implements the AgreementInfo interface.
 */
export function instanceOfAgreementInfo(value: object): value is AgreementInfo {
    return true;
}

export function AgreementInfoFromJSON(json: any): AgreementInfo {
    return AgreementInfoFromJSONTyped(json, false);
}

export function AgreementInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgreementInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'url': json['url'] == null ? undefined : json['url'],
        'autoVerifyGroup': json['auto_verify_group'] == null ? undefined : GroupInfoFromJSON(json['auto_verify_group']),
    };
}

export function AgreementInfoToJSON(json: any): AgreementInfo {
    return AgreementInfoToJSONTyped(json, false);
}

export function AgreementInfoToJSONTyped(value?: AgreementInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'url': value['url'],
        'auto_verify_group': GroupInfoToJSON(value['autoVerifyGroup']),
    };
}

