/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplyPatchInput
 */
export interface ApplyPatchInput {
    /**
     * The patch to be applied. Must be compatible with git diff output. For example, Get Patch output. The patch must be provided as UTF-8 text, either directly or base64-encoded.
     */
    patch?: string;
    /**
     * If true, tolerate conflicts and add conflict markers where required.
     */
    allowConflicts?: boolean;
}

/**
 * Check if a given object implements the ApplyPatchInput interface.
 */
export function instanceOfApplyPatchInput(value: object): value is ApplyPatchInput {
    return true;
}

export function ApplyPatchInputFromJSON(json: any): ApplyPatchInput {
    return ApplyPatchInputFromJSONTyped(json, false);
}

export function ApplyPatchInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplyPatchInput {
    if (json == null) {
        return json;
    }
    return {
        
        'patch': json['patch'] == null ? undefined : json['patch'],
        'allowConflicts': json['allow_conflicts'] == null ? undefined : json['allow_conflicts'],
    };
}

export function ApplyPatchInputToJSON(json: any): ApplyPatchInput {
    return ApplyPatchInputToJSONTyped(json, false);
}

export function ApplyPatchInputToJSONTyped(value?: ApplyPatchInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'patch': value['patch'],
        'allow_conflicts': value['allowConflicts'],
    };
}

