/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListChangesOption } from './ListChangesOption';
import {
    ListChangesOptionFromJSON,
    ListChangesOptionFromJSONTyped,
    ListChangesOptionToJSON,
    ListChangesOptionToJSONTyped,
} from './ListChangesOption';
import type { AccountInput } from './AccountInput';
import {
    AccountInputFromJSON,
    AccountInputFromJSONTyped,
    AccountInputToJSON,
    AccountInputToJSONTyped,
} from './AccountInput';
import type { ApplyPatchInput } from './ApplyPatchInput';
import {
    ApplyPatchInputFromJSON,
    ApplyPatchInputFromJSONTyped,
    ApplyPatchInputToJSON,
    ApplyPatchInputToJSONTyped,
} from './ApplyPatchInput';

/**
 * 
 * @export
 * @interface ApplyPatchPatchSetInput
 */
export interface ApplyPatchPatchSetInput {
    /**
     * 
     */
    patch?: ApplyPatchInput;
    /**
     * 
     */
    commitMessage?: string;
    /**
     * 
     */
    base?: string;
    /**
     * 
     */
    author?: AccountInput;
    /**
     * 
     */
    responseFormatOptions?: Array<ListChangesOption>;
    /**
     * 
     */
    amend?: boolean;
}

/**
 * Check if a given object implements the ApplyPatchPatchSetInput interface.
 */
export function instanceOfApplyPatchPatchSetInput(value: object): value is ApplyPatchPatchSetInput {
    return true;
}

export function ApplyPatchPatchSetInputFromJSON(json: any): ApplyPatchPatchSetInput {
    return ApplyPatchPatchSetInputFromJSONTyped(json, false);
}

export function ApplyPatchPatchSetInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplyPatchPatchSetInput {
    if (json == null) {
        return json;
    }
    return {
        
        'patch': json['patch'] == null ? undefined : ApplyPatchInputFromJSON(json['patch']),
        'commitMessage': json['commit_message'] == null ? undefined : json['commit_message'],
        'base': json['base'] == null ? undefined : json['base'],
        'author': json['author'] == null ? undefined : AccountInputFromJSON(json['author']),
        'responseFormatOptions': json['response_format_options'] == null ? undefined : ((json['response_format_options'] as Array<any>).map(ListChangesOptionFromJSON)),
        'amend': json['amend'] == null ? undefined : json['amend'],
    };
}

export function ApplyPatchPatchSetInputToJSON(json: any): ApplyPatchPatchSetInput {
    return ApplyPatchPatchSetInputToJSONTyped(json, false);
}

export function ApplyPatchPatchSetInputToJSONTyped(value?: ApplyPatchPatchSetInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'patch': ApplyPatchInputToJSON(value['patch']),
        'commit_message': value['commitMessage'],
        'base': value['base'],
        'author': AccountInputToJSON(value['author']),
        'response_format_options': value['responseFormatOptions'] == null ? undefined : ((value['responseFormatOptions'] as Array<any>).map(ListChangesOptionToJSON)),
        'amend': value['amend'],
    };
}

