/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountInfo } from './AccountInfo';
import {
    AccountInfoFromJSON,
    AccountInfoFromJSONTyped,
    AccountInfoToJSON,
    AccountInfoToJSONTyped,
} from './AccountInfo';

/**
 * 
 * @export
 * @interface AttentionSetInfo
 */
export interface AttentionSetInfo {
    /**
     * 
     */
    account?: AccountInfo;
    /**
     * 
     */
    lastUpdate?: string;
    /**
     * 
     */
    reason?: string;
    /**
     * 
     */
    reasonAccount?: AccountInfo;
}

/**
 * Check if a given object implements the AttentionSetInfo interface.
 */
export function instanceOfAttentionSetInfo(value: object): value is AttentionSetInfo {
    return true;
}

export function AttentionSetInfoFromJSON(json: any): AttentionSetInfo {
    return AttentionSetInfoFromJSONTyped(json, false);
}

export function AttentionSetInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttentionSetInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'] == null ? undefined : AccountInfoFromJSON(json['account']),
        'lastUpdate': json['last_update'] == null ? undefined : json['last_update'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'reasonAccount': json['reason_account'] == null ? undefined : AccountInfoFromJSON(json['reason_account']),
    };
}

export function AttentionSetInfoToJSON(json: any): AttentionSetInfo {
    return AttentionSetInfoToJSONTyped(json, false);
}

export function AttentionSetInfoToJSONTyped(value?: AttentionSetInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': AccountInfoToJSON(value['account']),
        'last_update': value['lastUpdate'],
        'reason': value['reason'],
        'reason_account': AccountInfoToJSON(value['reasonAccount']),
    };
}

