/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotifyInfo } from './NotifyInfo';
import {
    NotifyInfoFromJSON,
    NotifyInfoFromJSONTyped,
    NotifyInfoToJSON,
    NotifyInfoToJSONTyped,
} from './NotifyInfo';
import type { NotifyHandling } from './NotifyHandling';
import {
    NotifyHandlingFromJSON,
    NotifyHandlingFromJSONTyped,
    NotifyHandlingToJSON,
    NotifyHandlingToJSONTyped,
} from './NotifyHandling';

/**
 * 
 * @export
 * @interface AttentionSetInput
 */
export interface AttentionSetInput {
    /**
     * 
     */
    user?: string;
    /**
     * 
     */
    reason?: string;
    /**
     * 
     */
    notify?: NotifyHandling;
    /**
     * 
     */
    notifyDetails?: { [key: string]: NotifyInfo; };
}



/**
 * Check if a given object implements the AttentionSetInput interface.
 */
export function instanceOfAttentionSetInput(value: object): value is AttentionSetInput {
    return true;
}

export function AttentionSetInputFromJSON(json: any): AttentionSetInput {
    return AttentionSetInputFromJSONTyped(json, false);
}

export function AttentionSetInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttentionSetInput {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : json['user'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'notify': json['notify'] == null ? undefined : NotifyHandlingFromJSON(json['notify']),
        'notifyDetails': json['notify_details'] == null ? undefined : (mapValues(json['notify_details'], NotifyInfoFromJSON)),
    };
}

export function AttentionSetInputToJSON(json: any): AttentionSetInput {
    return AttentionSetInputToJSONTyped(json, false);
}

export function AttentionSetInputToJSONTyped(value?: AttentionSetInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': value['user'],
        'reason': value['reason'],
        'notify': NotifyHandlingToJSON(value['notify']),
        'notify_details': value['notifyDetails'] == null ? undefined : (mapValues(value['notifyDetails'], NotifyInfoToJSON)),
    };
}

