/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthTokenInput
 */
export interface AuthTokenInput {
    /**
     * Must be the same as the id used in the URL.
     */
    id?: string;
    /**
     * The new token. Only Gerrit administrators may set the token directly.
     */
    token?: string;
    /**
     * Lifetime of the token. After the given duration the token will be invalid.
     */
    lifetime?: string;
}

/**
 * Check if a given object implements the AuthTokenInput interface.
 */
export function instanceOfAuthTokenInput(value: object): value is AuthTokenInput {
    return true;
}

export function AuthTokenInputFromJSON(json: any): AuthTokenInput {
    return AuthTokenInputFromJSONTyped(json, false);
}

export function AuthTokenInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthTokenInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'token': json['token'] == null ? undefined : json['token'],
        'lifetime': json['lifetime'] == null ? undefined : json['lifetime'],
    };
}

export function AuthTokenInputToJSON(json: any): AuthTokenInput {
    return AuthTokenInputToJSONTyped(json, false);
}

export function AuthTokenInputToJSONTyped(value?: AuthTokenInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'token': value['token'],
        'lifetime': value['lifetime'],
    };
}

