/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChangeInfo } from './ChangeInfo';
import {
    ChangeInfoFromJSON,
    ChangeInfoFromJSONTyped,
    ChangeInfoToJSON,
    ChangeInfoToJSONTyped,
} from './ChangeInfo';

/**
 * 
 * @export
 * @interface AutoCloseableChangesCheckResult
 */
export interface AutoCloseableChangesCheckResult {
    /**
     * Changes that can be auto-closed as list of ChangeInfo entities. For each returned ChangeInfo entity the problems field is populated that includes details about the detected issues. If fix in the AutoCloseableChangesCheckInput was set to true, status and outcome in ProblemInfo are populated.
     */
    autoCloseableChanges?: Array<ChangeInfo>;
}

/**
 * Check if a given object implements the AutoCloseableChangesCheckResult interface.
 */
export function instanceOfAutoCloseableChangesCheckResult(value: object): value is AutoCloseableChangesCheckResult {
    return true;
}

export function AutoCloseableChangesCheckResultFromJSON(json: any): AutoCloseableChangesCheckResult {
    return AutoCloseableChangesCheckResultFromJSONTyped(json, false);
}

export function AutoCloseableChangesCheckResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoCloseableChangesCheckResult {
    if (json == null) {
        return json;
    }
    return {
        
        'autoCloseableChanges': json['auto_closeable_changes'] == null ? undefined : ((json['auto_closeable_changes'] as Array<any>).map(ChangeInfoFromJSON)),
    };
}

export function AutoCloseableChangesCheckResultToJSON(json: any): AutoCloseableChangesCheckResult {
    return AutoCloseableChangesCheckResultToJSONTyped(json, false);
}

export function AutoCloseableChangesCheckResultToJSONTyped(value?: AutoCloseableChangesCheckResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auto_closeable_changes': value['autoCloseableChanges'] == null ? undefined : ((value['autoCloseableChanges'] as Array<any>).map(ChangeInfoToJSON)),
    };
}

