/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutoCloseableChangesCheckInput
 */
export interface AutoCloseableChangesCheckInput {
    /**
     * 
     */
    fix?: boolean;
    /**
     * 
     */
    branch?: string;
    /**
     * 
     */
    skipCommits?: number;
    /**
     * 
     */
    maxCommits?: number;
}

/**
 * Check if a given object implements the AutoCloseableChangesCheckInput interface.
 */
export function instanceOfAutoCloseableChangesCheckInput(value: object): value is AutoCloseableChangesCheckInput {
    return true;
}

export function AutoCloseableChangesCheckInputFromJSON(json: any): AutoCloseableChangesCheckInput {
    return AutoCloseableChangesCheckInputFromJSONTyped(json, false);
}

export function AutoCloseableChangesCheckInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoCloseableChangesCheckInput {
    if (json == null) {
        return json;
    }
    return {
        
        'fix': json['fix'] == null ? undefined : json['fix'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'skipCommits': json['skip_commits'] == null ? undefined : json['skip_commits'],
        'maxCommits': json['max_commits'] == null ? undefined : json['max_commits'],
    };
}

export function AutoCloseableChangesCheckInputToJSON(json: any): AutoCloseableChangesCheckInput {
    return AutoCloseableChangesCheckInputToJSONTyped(json, false);
}

export function AutoCloseableChangesCheckInputToJSONTyped(value?: AutoCloseableChangesCheckInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fix': value['fix'],
        'branch': value['branch'],
        'skip_commits': value['skipCommits'],
        'max_commits': value['maxCommits'],
    };
}

