/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BranchInput
 */
export interface BranchInput {
    /**
     * 
     */
    revision?: string;
    /**
     * 
     */
    createEmptyCommit?: boolean;
    /**
     * 
     */
    ref?: string;
    /**
     * 
     */
    sourceRef?: string;
    /**
     * 
     */
    validationOptions?: { [key: string]: string; };
}

/**
 * Check if a given object implements the BranchInput interface.
 */
export function instanceOfBranchInput(value: object): value is BranchInput {
    return true;
}

export function BranchInputFromJSON(json: any): BranchInput {
    return BranchInputFromJSONTyped(json, false);
}

export function BranchInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchInput {
    if (json == null) {
        return json;
    }
    return {
        
        'revision': json['revision'] == null ? undefined : json['revision'],
        'createEmptyCommit': json['create_empty_commit'] == null ? undefined : json['create_empty_commit'],
        'ref': json['ref'] == null ? undefined : json['ref'],
        'sourceRef': json['source_ref'] == null ? undefined : json['source_ref'],
        'validationOptions': json['validation_options'] == null ? undefined : json['validation_options'],
    };
}

export function BranchInputToJSON(json: any): BranchInput {
    return BranchInputToJSONTyped(json, false);
}

export function BranchInputToJSONTyped(value?: BranchInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'revision': value['revision'],
        'create_empty_commit': value['createEmptyCommit'],
        'ref': value['ref'],
        'source_ref': value['sourceRef'],
        'validation_options': value['validationOptions'],
    };
}

