/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CapabilityInfo
 */
export interface CapabilityInfo {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    name?: string;
}

/**
 * Check if a given object implements the CapabilityInfo interface.
 */
export function instanceOfCapabilityInfo(value: object): value is CapabilityInfo {
    return true;
}

export function CapabilityInfoFromJSON(json: any): CapabilityInfo {
    return CapabilityInfoFromJSONTyped(json, false);
}

export function CapabilityInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CapabilityInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CapabilityInfoToJSON(json: any): CapabilityInfo {
    return CapabilityInfoToJSONTyped(json, false);
}

export function CapabilityInfoToJSONTyped(value?: CapabilityInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

