/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChangeStatus } from './ChangeStatus';
import {
    ChangeStatusFromJSON,
    ChangeStatusFromJSONTyped,
    ChangeStatusToJSON,
    ChangeStatusToJSONTyped,
} from './ChangeStatus';
import type { ProblemInfo } from './ProblemInfo';
import {
    ProblemInfoFromJSON,
    ProblemInfoFromJSONTyped,
    ProblemInfoToJSON,
    ProblemInfoToJSONTyped,
} from './ProblemInfo';
import type { ReviewerUpdateInfo } from './ReviewerUpdateInfo';
import {
    ReviewerUpdateInfoFromJSON,
    ReviewerUpdateInfoFromJSONTyped,
    ReviewerUpdateInfoToJSON,
    ReviewerUpdateInfoToJSONTyped,
} from './ReviewerUpdateInfo';
import type { ActionInfo } from './ActionInfo';
import {
    ActionInfoFromJSON,
    ActionInfoFromJSONTyped,
    ActionInfoToJSON,
    ActionInfoToJSONTyped,
} from './ActionInfo';
import type { ChangeMessageInfo } from './ChangeMessageInfo';
import {
    ChangeMessageInfoFromJSON,
    ChangeMessageInfoFromJSONTyped,
    ChangeMessageInfoToJSON,
    ChangeMessageInfoToJSONTyped,
} from './ChangeMessageInfo';
import type { SubmitRecordInfo } from './SubmitRecordInfo';
import {
    SubmitRecordInfoFromJSON,
    SubmitRecordInfoFromJSONTyped,
    SubmitRecordInfoToJSON,
    SubmitRecordInfoToJSONTyped,
} from './SubmitRecordInfo';
import type { LabelInfo } from './LabelInfo';
import {
    LabelInfoFromJSON,
    LabelInfoFromJSONTyped,
    LabelInfoToJSON,
    LabelInfoToJSONTyped,
} from './LabelInfo';
import type { LegacySubmitRequirementInfo } from './LegacySubmitRequirementInfo';
import {
    LegacySubmitRequirementInfoFromJSON,
    LegacySubmitRequirementInfoFromJSONTyped,
    LegacySubmitRequirementInfoToJSON,
    LegacySubmitRequirementInfoToJSONTyped,
} from './LegacySubmitRequirementInfo';
import type { RevisionInfo } from './RevisionInfo';
import {
    RevisionInfoFromJSON,
    RevisionInfoFromJSONTyped,
    RevisionInfoToJSON,
    RevisionInfoToJSONTyped,
} from './RevisionInfo';
import type { SubmitRequirementResultInfo } from './SubmitRequirementResultInfo';
import {
    SubmitRequirementResultInfoFromJSON,
    SubmitRequirementResultInfoFromJSONTyped,
    SubmitRequirementResultInfoToJSON,
    SubmitRequirementResultInfoToJSONTyped,
} from './SubmitRequirementResultInfo';
import type { SubmitType } from './SubmitType';
import {
    SubmitTypeFromJSON,
    SubmitTypeFromJSONTyped,
    SubmitTypeToJSON,
    SubmitTypeToJSONTyped,
} from './SubmitType';
import type { TrackingIdInfo } from './TrackingIdInfo';
import {
    TrackingIdInfoFromJSON,
    TrackingIdInfoFromJSONTyped,
    TrackingIdInfoToJSON,
    TrackingIdInfoToJSONTyped,
} from './TrackingIdInfo';
import type { PluginDefinedInfo } from './PluginDefinedInfo';
import {
    PluginDefinedInfoFromJSON,
    PluginDefinedInfoFromJSONTyped,
    PluginDefinedInfoToJSON,
    PluginDefinedInfoToJSONTyped,
} from './PluginDefinedInfo';
import type { AccountInfo } from './AccountInfo';
import {
    AccountInfoFromJSON,
    AccountInfoFromJSONTyped,
    AccountInfoToJSON,
    AccountInfoToJSONTyped,
} from './AccountInfo';
import type { AttentionSetInfo } from './AttentionSetInfo';
import {
    AttentionSetInfoFromJSON,
    AttentionSetInfoFromJSONTyped,
    AttentionSetInfoToJSON,
    AttentionSetInfoToJSONTyped,
} from './AttentionSetInfo';

/**
 * 
 * @export
 * @interface ChangeInfo
 */
export interface ChangeInfo {
    /**
     * The ID of the change. The format is "'<project>\~<_number>'". 'project' and '_number' are URL encoded. The callers must not rely on the format.
     */
    id?: string;
    /**
     * The ID of the change in the format "'<project>\~<branch>~<Change-Id>'", where 'project' and 'branch' are URL encoded. For 'branch' the refs/heads/ prefix is omitted.
     */
    tripletId?: string;
    /**
     * The name of the project.
     */
    project?: string;
    /**
     * The name of the target branch. + The refs/heads/ prefix is omitted.
     */
    branch?: string;
    /**
     * The full name of the target branch. + Always starts with refs/.
     */
    fullBranch?: string;
    /**
     * The topic to which this change belongs.
     */
    topic?: string;
    /**
     * The map that maps account IDs to AttentionSetInfo of that account. Those are all accounts that are currently in the attention set.
     */
    attentionSet?: { [key: string]: AttentionSetInfo; };
    /**
     * The map that maps account IDs to AttentionSetInfo of that account. Those are all accounts that were in the attention set but were removed. The AttentionSetInfo is the latest and most recent removal of the account from the attention set.
     */
    removedFromAttentionSet?: { [key: string]: AttentionSetInfo; };
    /**
     * A map that maps custom keys to custom values that are tied to a specific change, both in the form of strings. Only set if custom keyed values are requested.
     */
    customKeyedValues?: { [key: string]: string; };
    /**
     * List of hashtags that are set on the change.
     */
    hashtags?: Array<string>;
    /**
     * The Change-Id of the change.
     */
    changeId?: string;
    /**
     * The subject of the change (header line of the commit message).
     */
    subject?: string;
    /**
     * The status of the change (NEW, MERGED, ABANDONED).
     */
    status?: ChangeStatus;
    /**
     * The timestamp of when the change was created.
     */
    created?: string;
    /**
     * The timestamp of when the change was last updated.
     */
    updated?: string;
    /**
     * The timestamp of when the change was submitted.
     */
    submitted?: string;
    /**
     * The user who submitted the change, as an AccountInfo entity.
     */
    submitter?: AccountInfo;
    /**
     * Whether the calling user has starred this change. Only set if requested.
     */
    starred?: boolean;
    /**
     * List of star labels that are applied by the calling user to this change.
     */
    stars?: Array<string>;
    /**
     * Whether the change was reviewed by the calling user. Only set if reviewed is requested.
     */
    reviewed?: boolean;
    /**
     * The submit type of the change. + Not set for merged changes.
     */
    submitType?: SubmitType;
    /**
     * Whether the change is mergeable. + Only set for open changes if change.mergeabilityComputationBehavior is API_REF_UPDATED_AND_CHANGE_REINDEX.
     */
    mergeable?: boolean;
    /**
     * Whether the change has been approved by the project submit rules. + Only set if requested.
     */
    submittable?: boolean;
    /**
     * Number of inserted lines.
     */
    insertions?: number;
    /**
     * Number of deleted lines.
     */
    deletions?: number;
    /**
     * Total number of inline comments across all patch sets.
     */
    totalCommentCount?: number;
    /**
     * Number of unresolved inline comment threads across all patch sets.
     */
    unresolvedCommentCount?: number;
    /**
     * When present, change is marked as private.
     */
    isPrivate?: boolean;
    /**
     * When present, change is marked as Work In Progress.
     */
    workInProgress?: boolean;
    /**
     * When present, change has been marked Ready at some point in time.
     */
    hasReviewStarted?: boolean;
    /**
     * The change number of the change that this change reverts.
     */
    revertOf?: number;
    /**
     * ID of the submission of this change. Only set if the status is MERGED. This ID is equal to the change number of the change that triggered the submission. If the change that triggered the submission also has a topic, it will be "<id>-<topic>" of the change that triggered the submission.
     */
    submissionId?: string;
    /**
     * The change number of the change that this change was cherry-picked from. Only set if the cherry-pick has been done through the Gerrit REST API (and not if a cherry-picked commit was pushed).
     */
    cherryPickOfChange?: number;
    /**
     * The patchset number of the change that this change was cherry-picked from. Only set if the cherry-pick has been done through the Gerrit REST API (and not if a cherry-picked commit was pushed).
     */
    cherryPickOfPatchSet?: number;
    /**
     * The SHA-1 of the NoteDb meta ref.
     */
    metaRevId?: string;
    /**
     * Whether the change contains conflicts. + If true, some of the file contents of the change contain git conflict markers to indicate the conflicts. + Only set if this change info is returned in response to a request that creates a new change or patch set and conflicts are allowed.
     */
    containsGitConflicts?: boolean;
    /**
     * The change number. (The underscore is just a relict of a prior attempt to deprecate the change number.)
     */
    number?: number;
    /**
     * The virtual id number is globally unique. For local changes, it is equal to the _number attribute. For imported changes, the original _number is processed through a function designed to prevent conflicts with local change numbers.
     */
    virtualIdNumber?: number;
    /**
     * The owner of the change as an AccountInfo entity.
     */
    owner?: AccountInfo;
    /**
     * Actions the caller might be able to perform on this revision. The information is a map of view name to ActionInfo entities.
     */
    actions?: { [key: string]: ActionInfo; };
    /**
     * The labels of the change as a map that maps the label names to LabelInfo entries. + Only set if labels or detailed labels are requested.
     */
    labels?: { [key: string]: LabelInfo; };
    /**
     * A map of the permitted labels that maps a label name to the list of values that the current user can vote on. + Only set if detailed labels are requested.
     */
    permittedLabels?: { [key: string]: Array<string>; };
    /**
     * A map of the removable labels that maps a label name to the map of values and reviewers ( AccountInfo entities) that are allowed to be removed from the change. + Only set if labels or detailed labels are requested.
     */
    removableLabels?: { [key: string]: { [key: string]: Array<AccountInfo>; }; };
    /**
     * The reviewers that can be removed by the calling user as a list of AccountInfo entities. + Only set if labels or detailed labels are requested.
     */
    removableReviewers?: Array<AccountInfo>;
    /**
     * The reviewers as a map that maps a reviewer state to a list of AccountInfo entities. Possible reviewer states are REVIEWER, CC. + REVIEWER: Users with at least one non-zero vote on the change. + CC: Users that were added to the change, but have not voted.
     */
    reviewers?: { [key: string]: Array<AccountInfo>; };
    /**
     * Updates to reviewers that have been made while the change was in the WIP state. Only present on WIP changes and only if there are pending reviewer updates to report. These are reviewers who have not yet been notified about being added to or removed from the change.
     */
    pendingReviewers?: { [key: string]: Array<AccountInfo>; };
    /**
     * Updates to reviewers set for the change as ReviewerUpdateInfo entities. Only set if reviewer updates are requested.
     */
    reviewerUpdates?: Array<ReviewerUpdateInfo>;
    /**
     * Messages associated with the change as a list of ChangeMessageInfo entities. + Only set if messages are requested.
     */
    messages?: Array<ChangeMessageInfo>;
    /**
     * The number of the current patch set of this change. +
     */
    currentRevisionNumber?: number;
    /**
     * The commit ID of the current patch set of this change. + Only set if the current revision is requested or if all revisions are requested.
     */
    currentRevision?: string;
    /**
     * All patch sets of this change as a map that maps the commit ID of the patch set to a RevisionInfo entity. + Only set if the current revision is requested (in which case it will only contain a key for the current revision) or if all revisions are requested.
     */
    revisions?: { [key: string]: RevisionInfo; };
    /**
     * Whether the query would deliver more results if not limited. + Only set on the last change that is returned.
     */
    moreChanges?: boolean;
    /**
     * A list of ProblemInfo entities describing potential problems with this change. Only set if CHECK is set.
     */
    problems?: Array<ProblemInfo>;
    /**
     * Plugin-provided information about the change, as a list of PluginDefinedInfo entities. Only present if a plugin contributes data.
     */
    plugins?: Array<PluginDefinedInfo>;
    /**
     * A list of TrackingIdInfo entities describing references to external tracking systems. Only set if tracking ids are requested.
     */
    trackingIds?: Array<TrackingIdInfo>;
    /**
     * List of the requirements to be met before this change can be submitted. This field is deprecated in favour of submit_requirements. Only set if SUBMIT_REQUIREMENTS is requested.
     */
    requirements?: Array<LegacySubmitRequirementInfo>;
    /**
     * List of the SubmitRecordInfo containing the submit records for the change at the latest patchset. This field is deprecated in favour of submit_requirements. Only set if SUBMIT_REQUIREMENTS is requested.
     */
    submitRecords?: Array<SubmitRecordInfo>;
    /**
     * List of the SubmitRequirementResultInfo containing the evaluated submit requirements for the change. Only set if SUBMIT_REQUIREMENTS is requested.
     */
    submitRequirements?: Array<SubmitRequirementResultInfo>;
}



/**
 * Check if a given object implements the ChangeInfo interface.
 */
export function instanceOfChangeInfo(value: object): value is ChangeInfo {
    return true;
}

export function ChangeInfoFromJSON(json: any): ChangeInfo {
    return ChangeInfoFromJSONTyped(json, false);
}

export function ChangeInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'tripletId': json['triplet_id'] == null ? undefined : json['triplet_id'],
        'project': json['project'] == null ? undefined : json['project'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'fullBranch': json['full_branch'] == null ? undefined : json['full_branch'],
        'topic': json['topic'] == null ? undefined : json['topic'],
        'attentionSet': json['attention_set'] == null ? undefined : (mapValues(json['attention_set'], AttentionSetInfoFromJSON)),
        'removedFromAttentionSet': json['removed_from_attention_set'] == null ? undefined : (mapValues(json['removed_from_attention_set'], AttentionSetInfoFromJSON)),
        'customKeyedValues': json['custom_keyed_values'] == null ? undefined : json['custom_keyed_values'],
        'hashtags': json['hashtags'] == null ? undefined : json['hashtags'],
        'changeId': json['change_id'] == null ? undefined : json['change_id'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'status': json['status'] == null ? undefined : ChangeStatusFromJSON(json['status']),
        'created': json['created'] == null ? undefined : json['created'],
        'updated': json['updated'] == null ? undefined : json['updated'],
        'submitted': json['submitted'] == null ? undefined : json['submitted'],
        'submitter': json['submitter'] == null ? undefined : AccountInfoFromJSON(json['submitter']),
        'starred': json['starred'] == null ? undefined : json['starred'],
        'stars': json['stars'] == null ? undefined : json['stars'],
        'reviewed': json['reviewed'] == null ? undefined : json['reviewed'],
        'submitType': json['submit_type'] == null ? undefined : SubmitTypeFromJSON(json['submit_type']),
        'mergeable': json['mergeable'] == null ? undefined : json['mergeable'],
        'submittable': json['submittable'] == null ? undefined : json['submittable'],
        'insertions': json['insertions'] == null ? undefined : json['insertions'],
        'deletions': json['deletions'] == null ? undefined : json['deletions'],
        'totalCommentCount': json['total_comment_count'] == null ? undefined : json['total_comment_count'],
        'unresolvedCommentCount': json['unresolved_comment_count'] == null ? undefined : json['unresolved_comment_count'],
        'isPrivate': json['is_private'] == null ? undefined : json['is_private'],
        'workInProgress': json['work_in_progress'] == null ? undefined : json['work_in_progress'],
        'hasReviewStarted': json['has_review_started'] == null ? undefined : json['has_review_started'],
        'revertOf': json['revert_of'] == null ? undefined : json['revert_of'],
        'submissionId': json['submission_id'] == null ? undefined : json['submission_id'],
        'cherryPickOfChange': json['cherry_pick_of_change'] == null ? undefined : json['cherry_pick_of_change'],
        'cherryPickOfPatchSet': json['cherry_pick_of_patch_set'] == null ? undefined : json['cherry_pick_of_patch_set'],
        'metaRevId': json['meta_rev_id'] == null ? undefined : json['meta_rev_id'],
        'containsGitConflicts': json['contains_git_conflicts'] == null ? undefined : json['contains_git_conflicts'],
        'number': json['_number'] == null ? undefined : json['_number'],
        'virtualIdNumber': json['virtual_id_number'] == null ? undefined : json['virtual_id_number'],
        'owner': json['owner'] == null ? undefined : AccountInfoFromJSON(json['owner']),
        'actions': json['actions'] == null ? undefined : (mapValues(json['actions'], ActionInfoFromJSON)),
        'labels': json['labels'] == null ? undefined : (mapValues(json['labels'], LabelInfoFromJSON)),
        'permittedLabels': json['permitted_labels'] == null ? undefined : json['permitted_labels'],
        'removableLabels': json['removable_labels'] == null ? undefined : json['removable_labels'],
        'removableReviewers': json['removable_reviewers'] == null ? undefined : ((json['removable_reviewers'] as Array<any>).map(AccountInfoFromJSON)),
        'reviewers': json['reviewers'] == null ? undefined : json['reviewers'],
        'pendingReviewers': json['pending_reviewers'] == null ? undefined : json['pending_reviewers'],
        'reviewerUpdates': json['reviewer_updates'] == null ? undefined : ((json['reviewer_updates'] as Array<any>).map(ReviewerUpdateInfoFromJSON)),
        'messages': json['messages'] == null ? undefined : ((json['messages'] as Array<any>).map(ChangeMessageInfoFromJSON)),
        'currentRevisionNumber': json['current_revision_number'] == null ? undefined : json['current_revision_number'],
        'currentRevision': json['current_revision'] == null ? undefined : json['current_revision'],
        'revisions': json['revisions'] == null ? undefined : (mapValues(json['revisions'], RevisionInfoFromJSON)),
        'moreChanges': json['_more_changes'] == null ? undefined : json['_more_changes'],
        'problems': json['problems'] == null ? undefined : ((json['problems'] as Array<any>).map(ProblemInfoFromJSON)),
        'plugins': json['plugins'] == null ? undefined : ((json['plugins'] as Array<any>).map(PluginDefinedInfoFromJSON)),
        'trackingIds': json['tracking_ids'] == null ? undefined : ((json['tracking_ids'] as Array<any>).map(TrackingIdInfoFromJSON)),
        'requirements': json['requirements'] == null ? undefined : ((json['requirements'] as Array<any>).map(LegacySubmitRequirementInfoFromJSON)),
        'submitRecords': json['submit_records'] == null ? undefined : ((json['submit_records'] as Array<any>).map(SubmitRecordInfoFromJSON)),
        'submitRequirements': json['submit_requirements'] == null ? undefined : ((json['submit_requirements'] as Array<any>).map(SubmitRequirementResultInfoFromJSON)),
    };
}

export function ChangeInfoToJSON(json: any): ChangeInfo {
    return ChangeInfoToJSONTyped(json, false);
}

export function ChangeInfoToJSONTyped(value?: ChangeInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'triplet_id': value['tripletId'],
        'project': value['project'],
        'branch': value['branch'],
        'full_branch': value['fullBranch'],
        'topic': value['topic'],
        'attention_set': value['attentionSet'] == null ? undefined : (mapValues(value['attentionSet'], AttentionSetInfoToJSON)),
        'removed_from_attention_set': value['removedFromAttentionSet'] == null ? undefined : (mapValues(value['removedFromAttentionSet'], AttentionSetInfoToJSON)),
        'custom_keyed_values': value['customKeyedValues'],
        'hashtags': value['hashtags'],
        'change_id': value['changeId'],
        'subject': value['subject'],
        'status': ChangeStatusToJSON(value['status']),
        'created': value['created'],
        'updated': value['updated'],
        'submitted': value['submitted'],
        'submitter': AccountInfoToJSON(value['submitter']),
        'starred': value['starred'],
        'stars': value['stars'],
        'reviewed': value['reviewed'],
        'submit_type': SubmitTypeToJSON(value['submitType']),
        'mergeable': value['mergeable'],
        'submittable': value['submittable'],
        'insertions': value['insertions'],
        'deletions': value['deletions'],
        'total_comment_count': value['totalCommentCount'],
        'unresolved_comment_count': value['unresolvedCommentCount'],
        'is_private': value['isPrivate'],
        'work_in_progress': value['workInProgress'],
        'has_review_started': value['hasReviewStarted'],
        'revert_of': value['revertOf'],
        'submission_id': value['submissionId'],
        'cherry_pick_of_change': value['cherryPickOfChange'],
        'cherry_pick_of_patch_set': value['cherryPickOfPatchSet'],
        'meta_rev_id': value['metaRevId'],
        'contains_git_conflicts': value['containsGitConflicts'],
        '_number': value['number'],
        'virtual_id_number': value['virtualIdNumber'],
        'owner': AccountInfoToJSON(value['owner']),
        'actions': value['actions'] == null ? undefined : (mapValues(value['actions'], ActionInfoToJSON)),
        'labels': value['labels'] == null ? undefined : (mapValues(value['labels'], LabelInfoToJSON)),
        'permitted_labels': value['permittedLabels'],
        'removable_labels': value['removableLabels'],
        'removable_reviewers': value['removableReviewers'] == null ? undefined : ((value['removableReviewers'] as Array<any>).map(AccountInfoToJSON)),
        'reviewers': value['reviewers'],
        'pending_reviewers': value['pendingReviewers'],
        'reviewer_updates': value['reviewerUpdates'] == null ? undefined : ((value['reviewerUpdates'] as Array<any>).map(ReviewerUpdateInfoToJSON)),
        'messages': value['messages'] == null ? undefined : ((value['messages'] as Array<any>).map(ChangeMessageInfoToJSON)),
        'current_revision_number': value['currentRevisionNumber'],
        'current_revision': value['currentRevision'],
        'revisions': value['revisions'] == null ? undefined : (mapValues(value['revisions'], RevisionInfoToJSON)),
        '_more_changes': value['moreChanges'],
        'problems': value['problems'] == null ? undefined : ((value['problems'] as Array<any>).map(ProblemInfoToJSON)),
        'plugins': value['plugins'] == null ? undefined : ((value['plugins'] as Array<any>).map(PluginDefinedInfoToJSON)),
        'tracking_ids': value['trackingIds'] == null ? undefined : ((value['trackingIds'] as Array<any>).map(TrackingIdInfoToJSON)),
        'requirements': value['requirements'] == null ? undefined : ((value['requirements'] as Array<any>).map(LegacySubmitRequirementInfoToJSON)),
        'submit_records': value['submitRecords'] == null ? undefined : ((value['submitRecords'] as Array<any>).map(SubmitRecordInfoToJSON)),
        'submit_requirements': value['submitRequirements'] == null ? undefined : ((value['submitRequirements'] as Array<any>).map(SubmitRequirementResultInfoToJSON)),
    };
}

