/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeConfigInfo
 */
export interface ChangeConfigInfo {
    /**
     * 
     */
    allowBlame?: boolean;
    /**
     * 
     */
    disablePrivateChanges?: boolean;
    /**
     * 
     */
    updateDelay?: number;
    /**
     * 
     */
    submitWholeTopic?: boolean;
    /**
     * 
     */
    mergeabilityComputationBehavior?: string;
    /**
     * 
     */
    conflictsPredicateEnabled?: boolean;
    /**
     * 
     */
    allowMarkdownBase64ImagesInComments?: boolean;
}

/**
 * Check if a given object implements the ChangeConfigInfo interface.
 */
export function instanceOfChangeConfigInfo(value: object): value is ChangeConfigInfo {
    return true;
}

export function ChangeConfigInfoFromJSON(json: any): ChangeConfigInfo {
    return ChangeConfigInfoFromJSONTyped(json, false);
}

export function ChangeConfigInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeConfigInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'allowBlame': json['allow_blame'] == null ? undefined : json['allow_blame'],
        'disablePrivateChanges': json['disable_private_changes'] == null ? undefined : json['disable_private_changes'],
        'updateDelay': json['update_delay'] == null ? undefined : json['update_delay'],
        'submitWholeTopic': json['submit_whole_topic'] == null ? undefined : json['submit_whole_topic'],
        'mergeabilityComputationBehavior': json['mergeability_computation_behavior'] == null ? undefined : json['mergeability_computation_behavior'],
        'conflictsPredicateEnabled': json['conflicts_predicate_enabled'] == null ? undefined : json['conflicts_predicate_enabled'],
        'allowMarkdownBase64ImagesInComments': json['allow_markdown_base64_images_in_comments'] == null ? undefined : json['allow_markdown_base64_images_in_comments'],
    };
}

export function ChangeConfigInfoToJSON(json: any): ChangeConfigInfo {
    return ChangeConfigInfoToJSONTyped(json, false);
}

export function ChangeConfigInfoToJSONTyped(value?: ChangeConfigInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allow_blame': value['allowBlame'],
        'disable_private_changes': value['disablePrivateChanges'],
        'update_delay': value['updateDelay'],
        'submit_whole_topic': value['submitWholeTopic'],
        'mergeability_computation_behavior': value['mergeabilityComputationBehavior'],
        'conflicts_predicate_enabled': value['conflictsPredicateEnabled'],
        'allow_markdown_base64_images_in_comments': value['allowMarkdownBase64ImagesInComments'],
    };
}

