/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ChangeType = {
    Added: 'ADDED',
    Modified: 'MODIFIED',
    Deleted: 'DELETED',
    Renamed: 'RENAMED',
    Copied: 'COPIED',
    Rewrite: 'REWRITE',
} as const;
export type ChangeType = typeof ChangeType[keyof typeof ChangeType];


export function instanceOfChangeType(value: any): boolean {
    for (const key in ChangeType) {
        if (Object.prototype.hasOwnProperty.call(ChangeType, key)) {
            if (ChangeType[key as keyof typeof ChangeType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ChangeTypeFromJSON(json: any): ChangeType {
    return ChangeTypeFromJSONTyped(json, false);
}

export function ChangeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeType {
    return json as ChangeType;
}

export function ChangeTypeToJSON(value?: ChangeType | null): any {
    return value as any;
}

export function ChangeTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ChangeType {
    return value as ChangeType;
}

