/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ChangeKind = {
    Rework: 'REWORK',
    TrivialRebase: 'TRIVIAL_REBASE',
    TrivialRebaseWithMessageUpdate: 'TRIVIAL_REBASE_WITH_MESSAGE_UPDATE',
    MergeFirstParentUpdate: 'MERGE_FIRST_PARENT_UPDATE',
    NoCodeChange: 'NO_CODE_CHANGE',
    NoChange: 'NO_CHANGE',
} as const;
export type ChangeKind = typeof ChangeKind[keyof typeof ChangeKind];


export function instanceOfChangeKind(value: any): boolean {
    for (const key in ChangeKind) {
        if (Object.prototype.hasOwnProperty.call(ChangeKind, key)) {
            if (ChangeKind[key as keyof typeof ChangeKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ChangeKindFromJSON(json: any): ChangeKind {
    return ChangeKindFromJSONTyped(json, false);
}

export function ChangeKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeKind {
    return json as ChangeKind;
}

export function ChangeKindToJSON(value?: ChangeKind | null): any {
    return value as any;
}

export function ChangeKindToJSONTyped(value: any, ignoreDiscriminator: boolean): ChangeKind {
    return value as ChangeKind;
}

