/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AutoCloseableChangesCheckInput } from './AutoCloseableChangesCheckInput';
import {
    AutoCloseableChangesCheckInputFromJSON,
    AutoCloseableChangesCheckInputFromJSONTyped,
    AutoCloseableChangesCheckInputToJSON,
    AutoCloseableChangesCheckInputToJSONTyped,
} from './AutoCloseableChangesCheckInput';

/**
 * 
 * @export
 * @interface CheckProjectInput
 */
export interface CheckProjectInput {
    /**
     * 
     */
    autoCloseableChangesCheck?: AutoCloseableChangesCheckInput;
}

/**
 * Check if a given object implements the CheckProjectInput interface.
 */
export function instanceOfCheckProjectInput(value: object): value is CheckProjectInput {
    return true;
}

export function CheckProjectInputFromJSON(json: any): CheckProjectInput {
    return CheckProjectInputFromJSONTyped(json, false);
}

export function CheckProjectInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckProjectInput {
    if (json == null) {
        return json;
    }
    return {
        
        'autoCloseableChangesCheck': json['auto_closeable_changes_check'] == null ? undefined : AutoCloseableChangesCheckInputFromJSON(json['auto_closeable_changes_check']),
    };
}

export function CheckProjectInputToJSON(json: any): CheckProjectInput {
    return CheckProjectInputToJSONTyped(json, false);
}

export function CheckProjectInputToJSONTyped(value?: CheckProjectInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auto_closeable_changes_check': AutoCloseableChangesCheckInputToJSON(value['autoCloseableChangesCheck']),
    };
}

