/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConsistencyProblemInfo } from './ConsistencyProblemInfo';
import {
    ConsistencyProblemInfoFromJSON,
    ConsistencyProblemInfoFromJSONTyped,
    ConsistencyProblemInfoToJSON,
    ConsistencyProblemInfoToJSONTyped,
} from './ConsistencyProblemInfo';

/**
 * 
 * @export
 * @interface CheckGroupsResultInfo
 */
export interface CheckGroupsResultInfo {
    /**
     * A list of ConsistencyProblemInfo entities.
     */
    problems?: Array<ConsistencyProblemInfo>;
}

/**
 * Check if a given object implements the CheckGroupsResultInfo interface.
 */
export function instanceOfCheckGroupsResultInfo(value: object): value is CheckGroupsResultInfo {
    return true;
}

export function CheckGroupsResultInfoFromJSON(json: any): CheckGroupsResultInfo {
    return CheckGroupsResultInfoFromJSONTyped(json, false);
}

export function CheckGroupsResultInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckGroupsResultInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'problems': json['problems'] == null ? undefined : ((json['problems'] as Array<any>).map(ConsistencyProblemInfoFromJSON)),
    };
}

export function CheckGroupsResultInfoToJSON(json: any): CheckGroupsResultInfo {
    return CheckGroupsResultInfoToJSONTyped(json, false);
}

export function CheckGroupsResultInfoToJSONTyped(value?: CheckGroupsResultInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'problems': value['problems'] == null ? undefined : ((value['problems'] as Array<any>).map(ConsistencyProblemInfoToJSON)),
    };
}

