/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotifyInfo } from './NotifyInfo';
import {
    NotifyInfoFromJSON,
    NotifyInfoFromJSONTyped,
    NotifyInfoToJSON,
    NotifyInfoToJSONTyped,
} from './NotifyInfo';
import type { NotifyHandling } from './NotifyHandling';
import {
    NotifyHandlingFromJSON,
    NotifyHandlingFromJSONTyped,
    NotifyHandlingToJSON,
    NotifyHandlingToJSONTyped,
} from './NotifyHandling';

/**
 * 
 * @export
 * @interface CherryPickInput
 */
export interface CherryPickInput {
    /**
     * 
     */
    message?: string;
    /**
     * 
     */
    destination?: string;
    /**
     * 
     */
    base?: string;
    /**
     * 
     */
    parent?: number;
    /**
     * 
     */
    notify?: NotifyHandling;
    /**
     * 
     */
    notifyDetails?: { [key: string]: NotifyInfo; };
    /**
     * 
     */
    keepReviewers?: boolean;
    /**
     * 
     */
    allowConflicts?: boolean;
    /**
     * 
     */
    topic?: string;
    /**
     * 
     */
    allowEmpty?: boolean;
    /**
     * 
     */
    validationOptions?: { [key: string]: string; };
    /**
     * 
     */
    committerEmail?: string;
}



/**
 * Check if a given object implements the CherryPickInput interface.
 */
export function instanceOfCherryPickInput(value: object): value is CherryPickInput {
    return true;
}

export function CherryPickInputFromJSON(json: any): CherryPickInput {
    return CherryPickInputFromJSONTyped(json, false);
}

export function CherryPickInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CherryPickInput {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'destination': json['destination'] == null ? undefined : json['destination'],
        'base': json['base'] == null ? undefined : json['base'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'notify': json['notify'] == null ? undefined : NotifyHandlingFromJSON(json['notify']),
        'notifyDetails': json['notify_details'] == null ? undefined : (mapValues(json['notify_details'], NotifyInfoFromJSON)),
        'keepReviewers': json['keep_reviewers'] == null ? undefined : json['keep_reviewers'],
        'allowConflicts': json['allow_conflicts'] == null ? undefined : json['allow_conflicts'],
        'topic': json['topic'] == null ? undefined : json['topic'],
        'allowEmpty': json['allow_empty'] == null ? undefined : json['allow_empty'],
        'validationOptions': json['validation_options'] == null ? undefined : json['validation_options'],
        'committerEmail': json['committer_email'] == null ? undefined : json['committer_email'],
    };
}

export function CherryPickInputToJSON(json: any): CherryPickInput {
    return CherryPickInputToJSONTyped(json, false);
}

export function CherryPickInputToJSONTyped(value?: CherryPickInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'destination': value['destination'],
        'base': value['base'],
        'parent': value['parent'],
        'notify': NotifyHandlingToJSON(value['notify']),
        'notify_details': value['notifyDetails'] == null ? undefined : (mapValues(value['notifyDetails'], NotifyInfoToJSON)),
        'keep_reviewers': value['keepReviewers'],
        'allow_conflicts': value['allowConflicts'],
        'topic': value['topic'],
        'allow_empty': value['allowEmpty'],
        'validation_options': value['validationOptions'],
        'committer_email': value['committerEmail'],
    };
}

