/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommitMessageInfo
 */
export interface CommitMessageInfo {
    /**
     * 
     */
    subject?: string;
    /**
     * 
     */
    fullMessage?: string;
    /**
     * 
     */
    footers?: { [key: string]: string; };
}

/**
 * Check if a given object implements the CommitMessageInfo interface.
 */
export function instanceOfCommitMessageInfo(value: object): value is CommitMessageInfo {
    return true;
}

export function CommitMessageInfoFromJSON(json: any): CommitMessageInfo {
    return CommitMessageInfoFromJSONTyped(json, false);
}

export function CommitMessageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitMessageInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'subject': json['subject'] == null ? undefined : json['subject'],
        'fullMessage': json['full_message'] == null ? undefined : json['full_message'],
        'footers': json['footers'] == null ? undefined : json['footers'],
    };
}

export function CommitMessageInfoToJSON(json: any): CommitMessageInfo {
    return CommitMessageInfoToJSONTyped(json, false);
}

export function CommitMessageInfoToJSONTyped(value?: CommitMessageInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subject': value['subject'],
        'full_message': value['fullMessage'],
        'footers': value['footers'],
    };
}

