/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentLinkInfo
 */
export interface CommentLinkInfo {
    /**
     * A JavaScript regular expression to match positions to be replaced with a hyperlink, as documented in commentlink.name.match.
     */
    match?: string;
    /**
     * The URL to direct the user to whenever the regular expression is matched, as documented in commentlink.name.link.
     */
    link?: string;
    /**
     * Text inserted before the link.
     */
    prefix?: string;
    /**
     * Text inserted after the link.
     */
    suffix?: string;
    /**
     * Text of the link.
     */
    text?: string;
    /**
     * Whether the commentlink is enabled, as documented in commentlink.name.enabled. If not set the commentlink is enabled.
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the CommentLinkInfo interface.
 */
export function instanceOfCommentLinkInfo(value: object): value is CommentLinkInfo {
    return true;
}

export function CommentLinkInfoFromJSON(json: any): CommentLinkInfo {
    return CommentLinkInfoFromJSONTyped(json, false);
}

export function CommentLinkInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentLinkInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'match': json['match'] == null ? undefined : json['match'],
        'link': json['link'] == null ? undefined : json['link'],
        'prefix': json['prefix'] == null ? undefined : json['prefix'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
        'text': json['text'] == null ? undefined : json['text'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function CommentLinkInfoToJSON(json: any): CommentLinkInfo {
    return CommentLinkInfoToJSONTyped(json, false);
}

export function CommentLinkInfoToJSONTyped(value?: CommentLinkInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'match': value['match'],
        'link': value['link'],
        'prefix': value['prefix'],
        'suffix': value['suffix'],
        'text': value['text'],
        'enabled': value['enabled'],
    };
}

