/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonDescriptionInput
 */
export interface CommonDescriptionInput {
    /**
     * The description text.
     */
    description?: string;
}

/**
 * Check if a given object implements the CommonDescriptionInput interface.
 */
export function instanceOfCommonDescriptionInput(value: object): value is CommonDescriptionInput {
    return true;
}

export function CommonDescriptionInputFromJSON(json: any): CommonDescriptionInput {
    return CommonDescriptionInputFromJSONTyped(json, false);
}

export function CommonDescriptionInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonDescriptionInput {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CommonDescriptionInputToJSON(json: any): CommonDescriptionInput {
    return CommonDescriptionInputToJSONTyped(json, false);
}

export function CommonDescriptionInputToJSONTyped(value?: CommonDescriptionInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
    };
}

