/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotifyInfo } from './NotifyInfo';
import {
    NotifyInfoFromJSON,
    NotifyInfoFromJSONTyped,
    NotifyInfoToJSON,
    NotifyInfoToJSONTyped,
} from './NotifyInfo';
import type { NotifyHandling } from './NotifyHandling';
import {
    NotifyHandlingFromJSON,
    NotifyHandlingFromJSONTyped,
    NotifyHandlingToJSON,
    NotifyHandlingToJSONTyped,
} from './NotifyHandling';

/**
 * 
 * @export
 * @interface CommitMessageInput
 */
export interface CommitMessageInput {
    /**
     * 
     */
    message?: string;
    /**
     * 
     */
    notify?: NotifyHandling;
    /**
     * 
     */
    notifyDetails?: { [key: string]: NotifyInfo; };
    /**
     * 
     */
    committerEmail?: string;
}



/**
 * Check if a given object implements the CommitMessageInput interface.
 */
export function instanceOfCommitMessageInput(value: object): value is CommitMessageInput {
    return true;
}

export function CommitMessageInputFromJSON(json: any): CommitMessageInput {
    return CommitMessageInputFromJSONTyped(json, false);
}

export function CommitMessageInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitMessageInput {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'notify': json['notify'] == null ? undefined : NotifyHandlingFromJSON(json['notify']),
        'notifyDetails': json['notify_details'] == null ? undefined : (mapValues(json['notify_details'], NotifyInfoFromJSON)),
        'committerEmail': json['committer_email'] == null ? undefined : json['committer_email'],
    };
}

export function CommitMessageInputToJSON(json: any): CommitMessageInput {
    return CommitMessageInputToJSONTyped(json, false);
}

export function CommitMessageInputToJSONTyped(value?: CommitMessageInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'notify': NotifyHandlingToJSON(value['notify']),
        'notify_details': value['notifyDetails'] == null ? undefined : (mapValues(value['notifyDetails'], NotifyInfoToJSON)),
        'committer_email': value['committerEmail'],
    };
}

