/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NoMergeBaseReason } from './NoMergeBaseReason';
import {
    NoMergeBaseReasonFromJSON,
    NoMergeBaseReasonFromJSONTyped,
    NoMergeBaseReasonToJSON,
    NoMergeBaseReasonToJSONTyped,
} from './NoMergeBaseReason';

/**
 * 
 * @export
 * @interface ConflictsInfo
 */
export interface ConflictsInfo {
    /**
     * 
     */
    base?: string;
    /**
     * 
     */
    ours?: string;
    /**
     * 
     */
    theirs?: string;
    /**
     * 
     */
    mergeStrategy?: string;
    /**
     * 
     */
    noBaseReason?: NoMergeBaseReason;
    /**
     * 
     */
    containsConflicts?: boolean;
}



/**
 * Check if a given object implements the ConflictsInfo interface.
 */
export function instanceOfConflictsInfo(value: object): value is ConflictsInfo {
    return true;
}

export function ConflictsInfoFromJSON(json: any): ConflictsInfo {
    return ConflictsInfoFromJSONTyped(json, false);
}

export function ConflictsInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConflictsInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'] == null ? undefined : json['base'],
        'ours': json['ours'] == null ? undefined : json['ours'],
        'theirs': json['theirs'] == null ? undefined : json['theirs'],
        'mergeStrategy': json['merge_strategy'] == null ? undefined : json['merge_strategy'],
        'noBaseReason': json['no_base_reason'] == null ? undefined : NoMergeBaseReasonFromJSON(json['no_base_reason']),
        'containsConflicts': json['contains_conflicts'] == null ? undefined : json['contains_conflicts'],
    };
}

export function ConflictsInfoToJSON(json: any): ConflictsInfo {
    return ConflictsInfoToJSONTyped(json, false);
}

export function ConflictsInfoToJSONTyped(value?: ConflictsInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'ours': value['ours'],
        'theirs': value['theirs'],
        'merge_strategy': value['mergeStrategy'],
        'no_base_reason': NoMergeBaseReasonToJSON(value['noBaseReason']),
        'contains_conflicts': value['containsConflicts'],
    };
}

