/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaxObjectSizeLimitInfo } from './MaxObjectSizeLimitInfo';
import {
    MaxObjectSizeLimitInfoFromJSON,
    MaxObjectSizeLimitInfoFromJSONTyped,
    MaxObjectSizeLimitInfoToJSON,
    MaxObjectSizeLimitInfoToJSONTyped,
} from './MaxObjectSizeLimitInfo';
import type { SubmitTypeInfo } from './SubmitTypeInfo';
import {
    SubmitTypeInfoFromJSON,
    SubmitTypeInfoFromJSONTyped,
    SubmitTypeInfoToJSON,
    SubmitTypeInfoToJSONTyped,
} from './SubmitTypeInfo';
import type { CommentLinkInfo } from './CommentLinkInfo';
import {
    CommentLinkInfoFromJSON,
    CommentLinkInfoFromJSONTyped,
    CommentLinkInfoToJSON,
    CommentLinkInfoToJSONTyped,
} from './CommentLinkInfo';
import type { ActionInfo } from './ActionInfo';
import {
    ActionInfoFromJSON,
    ActionInfoFromJSONTyped,
    ActionInfoToJSON,
    ActionInfoToJSONTyped,
} from './ActionInfo';
import type { ProjectState } from './ProjectState';
import {
    ProjectStateFromJSON,
    ProjectStateFromJSONTyped,
    ProjectStateToJSON,
    ProjectStateToJSONTyped,
} from './ProjectState';
import type { SubmitType } from './SubmitType';
import {
    SubmitTypeFromJSON,
    SubmitTypeFromJSONTyped,
    SubmitTypeToJSON,
    SubmitTypeToJSONTyped,
} from './SubmitType';
import type { ConfigParameterInfo } from './ConfigParameterInfo';
import {
    ConfigParameterInfoFromJSON,
    ConfigParameterInfoFromJSONTyped,
    ConfigParameterInfoToJSON,
    ConfigParameterInfoToJSONTyped,
} from './ConfigParameterInfo';
import type { InheritedBooleanInfo } from './InheritedBooleanInfo';
import {
    InheritedBooleanInfoFromJSON,
    InheritedBooleanInfoFromJSONTyped,
    InheritedBooleanInfoToJSON,
    InheritedBooleanInfoToJSONTyped,
} from './InheritedBooleanInfo';

/**
 * 
 * @export
 * @interface ConfigInfo
 */
export interface ConfigInfo {
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    useContributorAgreements?: InheritedBooleanInfo;
    /**
     * 
     */
    useContentMerge?: InheritedBooleanInfo;
    /**
     * 
     */
    useSignedOffBy?: InheritedBooleanInfo;
    /**
     * 
     */
    createNewChangeForAllNotInTarget?: InheritedBooleanInfo;
    /**
     * 
     */
    requireChangeId?: InheritedBooleanInfo;
    /**
     * 
     */
    enableSignedPush?: InheritedBooleanInfo;
    /**
     * 
     */
    requireSignedPush?: InheritedBooleanInfo;
    /**
     * 
     */
    rejectImplicitMerges?: InheritedBooleanInfo;
    /**
     * 
     */
    privateByDefault?: InheritedBooleanInfo;
    /**
     * 
     */
    workInProgressByDefault?: InheritedBooleanInfo;
    /**
     * 
     */
    enableReviewerByEmail?: InheritedBooleanInfo;
    /**
     * 
     */
    matchAuthorToCommitterDate?: InheritedBooleanInfo;
    /**
     * 
     */
    rejectEmptyCommit?: InheritedBooleanInfo;
    /**
     * 
     */
    skipAddingAuthorAndCommitterAsReviewers?: InheritedBooleanInfo;
    /**
     * 
     */
    maxObjectSizeLimit?: MaxObjectSizeLimitInfo;
    /**
     * 
     */
    submitType?: SubmitType;
    /**
     * 
     */
    defaultSubmitType?: SubmitTypeInfo;
    /**
     * 
     */
    state?: ProjectState;
    /**
     * 
     */
    pluginConfig?: { [key: string]: { [key: string]: ConfigParameterInfo; }; };
    /**
     * 
     */
    actions?: { [key: string]: ActionInfo; };
    /**
     * 
     */
    commentlinks?: { [key: string]: CommentLinkInfo; };
    /**
     * 
     */
    extensionPanelNames?: { [key: string]: Array<string>; };
}



/**
 * Check if a given object implements the ConfigInfo interface.
 */
export function instanceOfConfigInfo(value: object): value is ConfigInfo {
    return true;
}

export function ConfigInfoFromJSON(json: any): ConfigInfo {
    return ConfigInfoFromJSONTyped(json, false);
}

export function ConfigInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'useContributorAgreements': json['use_contributor_agreements'] == null ? undefined : InheritedBooleanInfoFromJSON(json['use_contributor_agreements']),
        'useContentMerge': json['use_content_merge'] == null ? undefined : InheritedBooleanInfoFromJSON(json['use_content_merge']),
        'useSignedOffBy': json['use_signed_off_by'] == null ? undefined : InheritedBooleanInfoFromJSON(json['use_signed_off_by']),
        'createNewChangeForAllNotInTarget': json['create_new_change_for_all_not_in_target'] == null ? undefined : InheritedBooleanInfoFromJSON(json['create_new_change_for_all_not_in_target']),
        'requireChangeId': json['require_change_id'] == null ? undefined : InheritedBooleanInfoFromJSON(json['require_change_id']),
        'enableSignedPush': json['enable_signed_push'] == null ? undefined : InheritedBooleanInfoFromJSON(json['enable_signed_push']),
        'requireSignedPush': json['require_signed_push'] == null ? undefined : InheritedBooleanInfoFromJSON(json['require_signed_push']),
        'rejectImplicitMerges': json['reject_implicit_merges'] == null ? undefined : InheritedBooleanInfoFromJSON(json['reject_implicit_merges']),
        'privateByDefault': json['private_by_default'] == null ? undefined : InheritedBooleanInfoFromJSON(json['private_by_default']),
        'workInProgressByDefault': json['work_in_progress_by_default'] == null ? undefined : InheritedBooleanInfoFromJSON(json['work_in_progress_by_default']),
        'enableReviewerByEmail': json['enable_reviewer_by_email'] == null ? undefined : InheritedBooleanInfoFromJSON(json['enable_reviewer_by_email']),
        'matchAuthorToCommitterDate': json['match_author_to_committer_date'] == null ? undefined : InheritedBooleanInfoFromJSON(json['match_author_to_committer_date']),
        'rejectEmptyCommit': json['reject_empty_commit'] == null ? undefined : InheritedBooleanInfoFromJSON(json['reject_empty_commit']),
        'skipAddingAuthorAndCommitterAsReviewers': json['skip_adding_author_and_committer_as_reviewers'] == null ? undefined : InheritedBooleanInfoFromJSON(json['skip_adding_author_and_committer_as_reviewers']),
        'maxObjectSizeLimit': json['max_object_size_limit'] == null ? undefined : MaxObjectSizeLimitInfoFromJSON(json['max_object_size_limit']),
        'submitType': json['submit_type'] == null ? undefined : SubmitTypeFromJSON(json['submit_type']),
        'defaultSubmitType': json['default_submit_type'] == null ? undefined : SubmitTypeInfoFromJSON(json['default_submit_type']),
        'state': json['state'] == null ? undefined : ProjectStateFromJSON(json['state']),
        'pluginConfig': json['plugin_config'] == null ? undefined : json['plugin_config'],
        'actions': json['actions'] == null ? undefined : (mapValues(json['actions'], ActionInfoFromJSON)),
        'commentlinks': json['commentlinks'] == null ? undefined : (mapValues(json['commentlinks'], CommentLinkInfoFromJSON)),
        'extensionPanelNames': json['extension_panel_names'] == null ? undefined : json['extension_panel_names'],
    };
}

export function ConfigInfoToJSON(json: any): ConfigInfo {
    return ConfigInfoToJSONTyped(json, false);
}

export function ConfigInfoToJSONTyped(value?: ConfigInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'use_contributor_agreements': InheritedBooleanInfoToJSON(value['useContributorAgreements']),
        'use_content_merge': InheritedBooleanInfoToJSON(value['useContentMerge']),
        'use_signed_off_by': InheritedBooleanInfoToJSON(value['useSignedOffBy']),
        'create_new_change_for_all_not_in_target': InheritedBooleanInfoToJSON(value['createNewChangeForAllNotInTarget']),
        'require_change_id': InheritedBooleanInfoToJSON(value['requireChangeId']),
        'enable_signed_push': InheritedBooleanInfoToJSON(value['enableSignedPush']),
        'require_signed_push': InheritedBooleanInfoToJSON(value['requireSignedPush']),
        'reject_implicit_merges': InheritedBooleanInfoToJSON(value['rejectImplicitMerges']),
        'private_by_default': InheritedBooleanInfoToJSON(value['privateByDefault']),
        'work_in_progress_by_default': InheritedBooleanInfoToJSON(value['workInProgressByDefault']),
        'enable_reviewer_by_email': InheritedBooleanInfoToJSON(value['enableReviewerByEmail']),
        'match_author_to_committer_date': InheritedBooleanInfoToJSON(value['matchAuthorToCommitterDate']),
        'reject_empty_commit': InheritedBooleanInfoToJSON(value['rejectEmptyCommit']),
        'skip_adding_author_and_committer_as_reviewers': InheritedBooleanInfoToJSON(value['skipAddingAuthorAndCommitterAsReviewers']),
        'max_object_size_limit': MaxObjectSizeLimitInfoToJSON(value['maxObjectSizeLimit']),
        'submit_type': SubmitTypeToJSON(value['submitType']),
        'default_submit_type': SubmitTypeInfoToJSON(value['defaultSubmitType']),
        'state': ProjectStateToJSON(value['state']),
        'plugin_config': value['pluginConfig'],
        'actions': value['actions'] == null ? undefined : (mapValues(value['actions'], ActionInfoToJSON)),
        'commentlinks': value['commentlinks'] == null ? undefined : (mapValues(value['commentlinks'], CommentLinkInfoToJSON)),
        'extension_panel_names': value['extensionPanelNames'],
    };
}

