/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigValue
 */
export interface ConfigValue {
    /**
     * The new single value for the configuration parameter.
     */
    value?: string;
    /**
     * The new list of values for a multi-valued configuration parameter.
     */
    values?: Array<string>;
}

/**
 * Check if a given object implements the ConfigValue interface.
 */
export function instanceOfConfigValue(value: object): value is ConfigValue {
    return true;
}

export function ConfigValueFromJSON(json: any): ConfigValue {
    return ConfigValueFromJSONTyped(json, false);
}

export function ConfigValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigValue {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
        'values': json['values'] == null ? undefined : json['values'],
    };
}

export function ConfigValueToJSON(json: any): ConfigValue {
    return ConfigValueToJSONTyped(json, false);
}

export function ConfigValueToJSONTyped(value?: ConfigValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'values': value['values'],
    };
}

