/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmEmailInput
 */
export interface ConfirmEmailInput {
    /**
     * The token that was sent by mail to a newly registered email address.
     */
    token?: string;
}

/**
 * Check if a given object implements the ConfirmEmailInput interface.
 */
export function instanceOfConfirmEmailInput(value: object): value is ConfirmEmailInput {
    return true;
}

export function ConfirmEmailInputFromJSON(json: any): ConfirmEmailInput {
    return ConfirmEmailInputFromJSONTyped(json, false);
}

export function ConfirmEmailInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmEmailInput {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function ConfirmEmailInputToJSON(json: any): ConfirmEmailInput {
    return ConfirmEmailInputToJSONTyped(json, false);
}

export function ConfirmEmailInputToJSONTyped(value?: ConfirmEmailInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

