/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigUpdateEntryInfo
 */
export interface ConfigUpdateEntryInfo {
    /**
     * The config key that contains the value.
     */
    configKey?: string;
    /**
     * The old config value. + Missing if value was not previously configured.
     */
    oldValue?: string;
    /**
     * The new config value, picked up after reload.
     */
    newValue?: string;
}

/**
 * Check if a given object implements the ConfigUpdateEntryInfo interface.
 */
export function instanceOfConfigUpdateEntryInfo(value: object): value is ConfigUpdateEntryInfo {
    return true;
}

export function ConfigUpdateEntryInfoFromJSON(json: any): ConfigUpdateEntryInfo {
    return ConfigUpdateEntryInfoFromJSONTyped(json, false);
}

export function ConfigUpdateEntryInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigUpdateEntryInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'configKey': json['config_key'] == null ? undefined : json['config_key'],
        'oldValue': json['old_value'] == null ? undefined : json['old_value'],
        'newValue': json['new_value'] == null ? undefined : json['new_value'],
    };
}

export function ConfigUpdateEntryInfoToJSON(json: any): ConfigUpdateEntryInfo {
    return ConfigUpdateEntryInfoToJSONTyped(json, false);
}

export function ConfigUpdateEntryInfoToJSONTyped(value?: ConfigUpdateEntryInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config_key': value['configKey'],
        'old_value': value['oldValue'],
        'new_value': value['newValue'],
    };
}

