/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConsistencyCheckInput
 */
export interface ConsistencyCheckInput {
    /**
     * Input for the account consistency check as CheckAccountsInput entity.
     */
    checkAccounts?: object;
    /**
     * Input for the account external ID consistency check as CheckAccountExternalIdsInput entity.
     */
    checkAccountExternalIds?: object;
    /**
     * Input for the group consistency check as CheckGroupsInput entity.
     */
    checkGroups?: object;
}

/**
 * Check if a given object implements the ConsistencyCheckInput interface.
 */
export function instanceOfConsistencyCheckInput(value: object): value is ConsistencyCheckInput {
    return true;
}

export function ConsistencyCheckInputFromJSON(json: any): ConsistencyCheckInput {
    return ConsistencyCheckInputFromJSONTyped(json, false);
}

export function ConsistencyCheckInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsistencyCheckInput {
    if (json == null) {
        return json;
    }
    return {
        
        'checkAccounts': json['check_accounts'] == null ? undefined : json['check_accounts'],
        'checkAccountExternalIds': json['check_account_external_ids'] == null ? undefined : json['check_account_external_ids'],
        'checkGroups': json['check_groups'] == null ? undefined : json['check_groups'],
    };
}

export function ConsistencyCheckInputToJSON(json: any): ConsistencyCheckInput {
    return ConsistencyCheckInputToJSONTyped(json, false);
}

export function ConsistencyCheckInputToJSONTyped(value?: ConsistencyCheckInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'check_accounts': value['checkAccounts'],
        'check_account_external_ids': value['checkAccountExternalIds'],
        'check_groups': value['checkGroups'],
    };
}

