/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentEntry
 */
export interface ContentEntry {
    /**
     * Content in the file on both sides (unchanged).
     */
    ab?: Array<string>;
    /**
     * Content only in the file on side A (deleted in B).
     */
    a?: Array<string>;
    /**
     * Content only in the file on side B (added in B).
     */
    b?: Array<string>;
    /**
     * Text sections deleted from side A as a DiffIntralineInfo entity.
     */
    editA?: Array<Array<number>>;
    /**
     * Text sections inserted in side B as a DiffIntralineInfo entity.
     */
    editB?: Array<Array<number>>;
    /**
     * Indicates whether this entry was introduced by a rebase.
     */
    dueToRebase?: boolean;
    /**
     * Set to true if the region is common according to the requested ignore-whitespace parameter, but a and b contain differing amounts of whitespace. When present and true a and b are used instead of ab.
     */
    common?: boolean;
    /**
     * count of lines skipped on both sides when the file is too large to include all common lines.
     */
    skip?: number;
}

/**
 * Check if a given object implements the ContentEntry interface.
 */
export function instanceOfContentEntry(value: object): value is ContentEntry {
    return true;
}

export function ContentEntryFromJSON(json: any): ContentEntry {
    return ContentEntryFromJSONTyped(json, false);
}

export function ContentEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'ab': json['ab'] == null ? undefined : json['ab'],
        'a': json['a'] == null ? undefined : json['a'],
        'b': json['b'] == null ? undefined : json['b'],
        'editA': json['edit_a'] == null ? undefined : json['edit_a'],
        'editB': json['edit_b'] == null ? undefined : json['edit_b'],
        'dueToRebase': json['due_to_rebase'] == null ? undefined : json['due_to_rebase'],
        'common': json['common'] == null ? undefined : json['common'],
        'skip': json['skip'] == null ? undefined : json['skip'],
    };
}

export function ContentEntryToJSON(json: any): ContentEntry {
    return ContentEntryToJSONTyped(json, false);
}

export function ContentEntryToJSONTyped(value?: ContentEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ab': value['ab'],
        'a': value['a'],
        'b': value['b'],
        'edit_a': value['editA'],
        'edit_b': value['editB'],
        'due_to_rebase': value['dueToRebase'],
        'common': value['common'],
        'skip': value['skip'],
    };
}

