/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContextLineInfo
 */
export interface ContextLineInfo {
    /**
     * The line number of the source line.
     */
    lineNumber?: number;
    /**
     * The text of the context line.
     */
    contextLine?: string;
}

/**
 * Check if a given object implements the ContextLineInfo interface.
 */
export function instanceOfContextLineInfo(value: object): value is ContextLineInfo {
    return true;
}

export function ContextLineInfoFromJSON(json: any): ContextLineInfo {
    return ContextLineInfoFromJSONTyped(json, false);
}

export function ContextLineInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContextLineInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'lineNumber': json['line_number'] == null ? undefined : json['line_number'],
        'contextLine': json['context_line'] == null ? undefined : json['context_line'],
    };
}

export function ContextLineInfoToJSON(json: any): ContextLineInfo {
    return ContextLineInfoToJSONTyped(json, false);
}

export function ContextLineInfoToJSONTyped(value?: ContextLineInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'line_number': value['lineNumber'],
        'context_line': value['contextLine'],
    };
}

