/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DashboardSectionInfo } from './DashboardSectionInfo';
import {
    DashboardSectionInfoFromJSON,
    DashboardSectionInfoFromJSONTyped,
    DashboardSectionInfoToJSON,
    DashboardSectionInfoToJSONTyped,
} from './DashboardSectionInfo';

/**
 * 
 * @export
 * @interface DashboardInfo
 */
export interface DashboardInfo {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    project?: string;
    /**
     * 
     */
    definingProject?: string;
    /**
     * 
     */
    ref?: string;
    /**
     * 
     */
    path?: string;
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    foreach?: string;
    /**
     * 
     */
    url?: string;
    /**
     * 
     */
    isDefault?: boolean;
    /**
     * 
     */
    title?: string;
    /**
     * 
     */
    sections?: Array<DashboardSectionInfo>;
}

/**
 * Check if a given object implements the DashboardInfo interface.
 */
export function instanceOfDashboardInfo(value: object): value is DashboardInfo {
    return true;
}

export function DashboardInfoFromJSON(json: any): DashboardInfo {
    return DashboardInfoFromJSONTyped(json, false);
}

export function DashboardInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'project': json['project'] == null ? undefined : json['project'],
        'definingProject': json['defining_project'] == null ? undefined : json['defining_project'],
        'ref': json['ref'] == null ? undefined : json['ref'],
        'path': json['path'] == null ? undefined : json['path'],
        'description': json['description'] == null ? undefined : json['description'],
        'foreach': json['foreach'] == null ? undefined : json['foreach'],
        'url': json['url'] == null ? undefined : json['url'],
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
        'title': json['title'] == null ? undefined : json['title'],
        'sections': json['sections'] == null ? undefined : ((json['sections'] as Array<any>).map(DashboardSectionInfoFromJSON)),
    };
}

export function DashboardInfoToJSON(json: any): DashboardInfo {
    return DashboardInfoToJSONTyped(json, false);
}

export function DashboardInfoToJSONTyped(value?: DashboardInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'project': value['project'],
        'defining_project': value['definingProject'],
        'ref': value['ref'],
        'path': value['path'],
        'description': value['description'],
        'foreach': value['foreach'],
        'url': value['url'],
        'is_default': value['isDefault'],
        'title': value['title'],
        'sections': value['sections'] == null ? undefined : ((value['sections'] as Array<any>).map(DashboardSectionInfoToJSON)),
    };
}

