/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DashboardSectionInfo
 */
export interface DashboardSectionInfo {
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    query?: string;
}

/**
 * Check if a given object implements the DashboardSectionInfo interface.
 */
export function instanceOfDashboardSectionInfo(value: object): value is DashboardSectionInfo {
    return true;
}

export function DashboardSectionInfoFromJSON(json: any): DashboardSectionInfo {
    return DashboardSectionInfoFromJSONTyped(json, false);
}

export function DashboardSectionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardSectionInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'query': json['query'] == null ? undefined : json['query'],
    };
}

export function DashboardSectionInfoToJSON(json: any): DashboardSectionInfo {
    return DashboardSectionInfoToJSONTyped(json, false);
}

export function DashboardSectionInfoToJSONTyped(value?: DashboardSectionInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'query': value['query'],
    };
}

