/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteBranchesInput
 */
export interface DeleteBranchesInput {
    /**
     * A list of branch names that identify the branches that should be deleted.
     */
    branches?: Array<string>;
}

/**
 * Check if a given object implements the DeleteBranchesInput interface.
 */
export function instanceOfDeleteBranchesInput(value: object): value is DeleteBranchesInput {
    return true;
}

export function DeleteBranchesInputFromJSON(json: any): DeleteBranchesInput {
    return DeleteBranchesInputFromJSONTyped(json, false);
}

export function DeleteBranchesInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteBranchesInput {
    if (json == null) {
        return json;
    }
    return {
        
        'branches': json['branches'] == null ? undefined : json['branches'],
    };
}

export function DeleteBranchesInputToJSON(json: any): DeleteBranchesInput {
    return DeleteBranchesInputToJSONTyped(json, false);
}

export function DeleteBranchesInputToJSONTyped(value?: DeleteBranchesInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branches': value['branches'],
    };
}

