/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteDraftCommentsInput
 */
export interface DeleteDraftCommentsInput {
    /**
     * A change query limiting results to changes matching this query; has:draft is implied and not necessary to list explicitly. If not set, matches all changes with drafts.
     */
    query?: string;
}

/**
 * Check if a given object implements the DeleteDraftCommentsInput interface.
 */
export function instanceOfDeleteDraftCommentsInput(value: object): value is DeleteDraftCommentsInput {
    return true;
}

export function DeleteDraftCommentsInputFromJSON(json: any): DeleteDraftCommentsInput {
    return DeleteDraftCommentsInputFromJSONTyped(json, false);
}

export function DeleteDraftCommentsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteDraftCommentsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] == null ? undefined : json['query'],
    };
}

export function DeleteDraftCommentsInputToJSON(json: any): DeleteDraftCommentsInput {
    return DeleteDraftCommentsInputToJSONTyped(json, false);
}

export function DeleteDraftCommentsInputToJSONTyped(value?: DeleteDraftCommentsInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
    };
}

