/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteChangesInput
 */
export interface DeleteChangesInput {
    /**
     * 
     */
    changes?: Array<string>;
}

/**
 * Check if a given object implements the DeleteChangesInput interface.
 */
export function instanceOfDeleteChangesInput(value: object): value is DeleteChangesInput {
    return true;
}

export function DeleteChangesInputFromJSON(json: any): DeleteChangesInput {
    return DeleteChangesInputFromJSONTyped(json, false);
}

export function DeleteChangesInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteChangesInput {
    if (json == null) {
        return json;
    }
    return {
        
        'changes': json['changes'] == null ? undefined : json['changes'],
    };
}

export function DeleteChangesInputToJSON(json: any): DeleteChangesInput {
    return DeleteChangesInputToJSONTyped(json, false);
}

export function DeleteChangesInputToJSONTyped(value?: DeleteChangesInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'changes': value['changes'],
    };
}

