/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotifyInfo } from './NotifyInfo';
import {
    NotifyInfoFromJSON,
    NotifyInfoFromJSONTyped,
    NotifyInfoToJSON,
    NotifyInfoToJSONTyped,
} from './NotifyInfo';
import type { NotifyHandling } from './NotifyHandling';
import {
    NotifyHandlingFromJSON,
    NotifyHandlingFromJSONTyped,
    NotifyHandlingToJSON,
    NotifyHandlingToJSONTyped,
} from './NotifyHandling';

/**
 * 
 * @export
 * @interface DeleteVoteInput
 */
export interface DeleteVoteInput {
    /**
     * 
     */
    label?: string;
    /**
     * 
     */
    notify?: NotifyHandling;
    /**
     * 
     */
    notifyDetails?: { [key: string]: NotifyInfo; };
    /**
     * 
     */
    ignoreAutomaticAttentionSetRules?: boolean;
    /**
     * 
     */
    reason?: string;
}



/**
 * Check if a given object implements the DeleteVoteInput interface.
 */
export function instanceOfDeleteVoteInput(value: object): value is DeleteVoteInput {
    return true;
}

export function DeleteVoteInputFromJSON(json: any): DeleteVoteInput {
    return DeleteVoteInputFromJSONTyped(json, false);
}

export function DeleteVoteInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteVoteInput {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'notify': json['notify'] == null ? undefined : NotifyHandlingFromJSON(json['notify']),
        'notifyDetails': json['notify_details'] == null ? undefined : (mapValues(json['notify_details'], NotifyInfoFromJSON)),
        'ignoreAutomaticAttentionSetRules': json['ignore_automatic_attention_set_rules'] == null ? undefined : json['ignore_automatic_attention_set_rules'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function DeleteVoteInputToJSON(json: any): DeleteVoteInput {
    return DeleteVoteInputToJSONTyped(json, false);
}

export function DeleteVoteInputToJSONTyped(value?: DeleteVoteInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'notify': NotifyHandlingToJSON(value['notify']),
        'notify_details': value['notifyDetails'] == null ? undefined : (mapValues(value['notifyDetails'], NotifyInfoToJSON)),
        'ignore_automatic_attention_set_rules': value['ignoreAutomaticAttentionSetRules'],
        'reason': value['reason'],
    };
}

