/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsiveMode } from './ResponsiveMode';
import {
    ResponsiveModeFromJSON,
    ResponsiveModeFromJSONTyped,
    ResponsiveModeToJSON,
    ResponsiveModeToJSONTyped,
} from './ResponsiveMode';
import type { Whitespace } from './Whitespace';
import {
    WhitespaceFromJSON,
    WhitespaceFromJSONTyped,
    WhitespaceToJSON,
    WhitespaceToJSONTyped,
} from './Whitespace';

/**
 * 
 * @export
 * @interface DiffPreferencesInfo
 */
export interface DiffPreferencesInfo {
    /**
     * The number of lines of context when viewing a patch.
     */
    context?: number;
    /**
     * Number of spaces that should be used to display one tab.
     */
    tabSize?: number;
    /**
     * Default font size in pixels for change to be displayed in the diff view.
     */
    fontSize?: number;
    /**
     * Number of characters that should be displayed in one line.
     */
    lineLength?: number;
    /**
     * Half-period in milliseconds used for cursor blinking. Setting it to 0 disables cursor blinking.
     */
    cursorBlinkRate?: number;
    /**
     * Whether all inline comments should be automatically expanded.
     */
    expandAllComments?: boolean;
    /**
     * Whether intraline differences should be highlighted.
     */
    intralineDifference?: boolean;
    /**
     * Whether the 'Reviewed' flag should not be set automatically on a patch when it is viewed.
     */
    manualReview?: boolean;
    /**
     * Whether Windows EOL/Cr-Lf should be displayed as '\r' in a dotted-line box.
     */
    showLineEndings?: boolean;
    /**
     * Whether tabs should be shown.
     */
    showTabs?: boolean;
    /**
     * Whether whitespace errors should be shown.
     */
    showWhitespaceErrors?: boolean;
    /**
     * Whether syntax highlighting should be enabled.
     */
    syntaxHighlighting?: boolean;
    /**
     * If true the top menu header and site header are hidden.
     */
    hideTopMenu?: boolean;
    /**
     * If true the diff table header is automatically hidden when scrolling down more than half of a page.
     */
    autoHideDiffTableHeader?: boolean;
    /**
     * If true the line numbers are hidden.
     */
    hideLineNumbers?: boolean;
    /**
     * 
     */
    renderEntireFile?: boolean;
    /**
     * 
     */
    hideEmptyPane?: boolean;
    /**
     * Whether matching brackets should be highlighted.
     */
    matchBrackets?: boolean;
    /**
     * Whether to enable line wrapping or not.
     */
    lineWrapping?: boolean;
    /**
     * 
     */
    responsiveMode?: ResponsiveMode;
    /**
     * Whether whitespace changes should be ignored and if yes, which whitespace changes should be ignored. + Allowed values are IGNORE_NONE, IGNORE_TRAILING, IGNORE_LEADING_AND_TRAILING, IGNORE_ALL.
     */
    ignoreWhitespace?: Whitespace;
    /**
     * Whether the header that is displayed above the patch (that either shows the commit message, the diff preferences, the patch sets or the files) should be retained on file switch.
     */
    retainHeader?: boolean;
    /**
     * Whether deleted files should be skipped on file switch.
     */
    skipDeleted?: boolean;
    /**
     * 
     */
    skipUnchanged?: boolean;
    /**
     * Whether uncommented files should be skipped on file switch.
     */
    skipUncommented?: boolean;
}



/**
 * Check if a given object implements the DiffPreferencesInfo interface.
 */
export function instanceOfDiffPreferencesInfo(value: object): value is DiffPreferencesInfo {
    return true;
}

export function DiffPreferencesInfoFromJSON(json: any): DiffPreferencesInfo {
    return DiffPreferencesInfoFromJSONTyped(json, false);
}

export function DiffPreferencesInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiffPreferencesInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'context': json['context'] == null ? undefined : json['context'],
        'tabSize': json['tab_size'] == null ? undefined : json['tab_size'],
        'fontSize': json['font_size'] == null ? undefined : json['font_size'],
        'lineLength': json['line_length'] == null ? undefined : json['line_length'],
        'cursorBlinkRate': json['cursor_blink_rate'] == null ? undefined : json['cursor_blink_rate'],
        'expandAllComments': json['expand_all_comments'] == null ? undefined : json['expand_all_comments'],
        'intralineDifference': json['intraline_difference'] == null ? undefined : json['intraline_difference'],
        'manualReview': json['manual_review'] == null ? undefined : json['manual_review'],
        'showLineEndings': json['show_line_endings'] == null ? undefined : json['show_line_endings'],
        'showTabs': json['show_tabs'] == null ? undefined : json['show_tabs'],
        'showWhitespaceErrors': json['show_whitespace_errors'] == null ? undefined : json['show_whitespace_errors'],
        'syntaxHighlighting': json['syntax_highlighting'] == null ? undefined : json['syntax_highlighting'],
        'hideTopMenu': json['hide_top_menu'] == null ? undefined : json['hide_top_menu'],
        'autoHideDiffTableHeader': json['auto_hide_diff_table_header'] == null ? undefined : json['auto_hide_diff_table_header'],
        'hideLineNumbers': json['hide_line_numbers'] == null ? undefined : json['hide_line_numbers'],
        'renderEntireFile': json['render_entire_file'] == null ? undefined : json['render_entire_file'],
        'hideEmptyPane': json['hide_empty_pane'] == null ? undefined : json['hide_empty_pane'],
        'matchBrackets': json['match_brackets'] == null ? undefined : json['match_brackets'],
        'lineWrapping': json['line_wrapping'] == null ? undefined : json['line_wrapping'],
        'responsiveMode': json['responsive_mode'] == null ? undefined : ResponsiveModeFromJSON(json['responsive_mode']),
        'ignoreWhitespace': json['ignore_whitespace'] == null ? undefined : WhitespaceFromJSON(json['ignore_whitespace']),
        'retainHeader': json['retain_header'] == null ? undefined : json['retain_header'],
        'skipDeleted': json['skip_deleted'] == null ? undefined : json['skip_deleted'],
        'skipUnchanged': json['skip_unchanged'] == null ? undefined : json['skip_unchanged'],
        'skipUncommented': json['skip_uncommented'] == null ? undefined : json['skip_uncommented'],
    };
}

export function DiffPreferencesInfoToJSON(json: any): DiffPreferencesInfo {
    return DiffPreferencesInfoToJSONTyped(json, false);
}

export function DiffPreferencesInfoToJSONTyped(value?: DiffPreferencesInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': value['context'],
        'tab_size': value['tabSize'],
        'font_size': value['fontSize'],
        'line_length': value['lineLength'],
        'cursor_blink_rate': value['cursorBlinkRate'],
        'expand_all_comments': value['expandAllComments'],
        'intraline_difference': value['intralineDifference'],
        'manual_review': value['manualReview'],
        'show_line_endings': value['showLineEndings'],
        'show_tabs': value['showTabs'],
        'show_whitespace_errors': value['showWhitespaceErrors'],
        'syntax_highlighting': value['syntaxHighlighting'],
        'hide_top_menu': value['hideTopMenu'],
        'auto_hide_diff_table_header': value['autoHideDiffTableHeader'],
        'hide_line_numbers': value['hideLineNumbers'],
        'render_entire_file': value['renderEntireFile'],
        'hide_empty_pane': value['hideEmptyPane'],
        'match_brackets': value['matchBrackets'],
        'line_wrapping': value['lineWrapping'],
        'responsive_mode': ResponsiveModeToJSON(value['responsiveMode']),
        'ignore_whitespace': WhitespaceToJSON(value['ignoreWhitespace']),
        'retain_header': value['retainHeader'],
        'skip_deleted': value['skipDeleted'],
        'skip_unchanged': value['skipUnchanged'],
        'skip_uncommented': value['skipUncommented'],
    };
}

