/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DisplayNameInput
 */
export interface DisplayNameInput {
    /**
     * The new display name of the account.
     */
    displayName?: string;
}

/**
 * Check if a given object implements the DisplayNameInput interface.
 */
export function instanceOfDisplayNameInput(value: object): value is DisplayNameInput {
    return true;
}

export function DisplayNameInputFromJSON(json: any): DisplayNameInput {
    return DisplayNameInputFromJSONTyped(json, false);
}

export function DisplayNameInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DisplayNameInput {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
    };
}

export function DisplayNameInputToJSON(json: any): DisplayNameInput {
    return DisplayNameInputToJSONTyped(json, false);
}

export function DisplayNameInputToJSONTyped(value?: DisplayNameInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['displayName'],
    };
}

