/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DownloadSchemeInfo
 */
export interface DownloadSchemeInfo {
    /**
     * 
     */
    url?: string;
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    isAuthRequired?: boolean;
    /**
     * 
     */
    isAuthSupported?: boolean;
    /**
     * 
     */
    commands?: { [key: string]: string; };
    /**
     * 
     */
    cloneCommands?: { [key: string]: string; };
}

/**
 * Check if a given object implements the DownloadSchemeInfo interface.
 */
export function instanceOfDownloadSchemeInfo(value: object): value is DownloadSchemeInfo {
    return true;
}

export function DownloadSchemeInfoFromJSON(json: any): DownloadSchemeInfo {
    return DownloadSchemeInfoFromJSONTyped(json, false);
}

export function DownloadSchemeInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadSchemeInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'description': json['description'] == null ? undefined : json['description'],
        'isAuthRequired': json['is_auth_required'] == null ? undefined : json['is_auth_required'],
        'isAuthSupported': json['is_auth_supported'] == null ? undefined : json['is_auth_supported'],
        'commands': json['commands'] == null ? undefined : json['commands'],
        'cloneCommands': json['clone_commands'] == null ? undefined : json['clone_commands'],
    };
}

export function DownloadSchemeInfoToJSON(json: any): DownloadSchemeInfo {
    return DownloadSchemeInfoToJSONTyped(json, false);
}

export function DownloadSchemeInfoToJSONTyped(value?: DownloadSchemeInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'description': value['description'],
        'is_auth_required': value['isAuthRequired'],
        'is_auth_supported': value['isAuthSupported'],
        'commands': value['commands'],
        'clone_commands': value['cloneCommands'],
    };
}

