/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EmailStrategy = {
    Enabled: 'ENABLED',
    CcOnOwnComments: 'CC_ON_OWN_COMMENTS',
    AttentionSetOnly: 'ATTENTION_SET_ONLY',
    Disabled: 'DISABLED',
} as const;
export type EmailStrategy = typeof EmailStrategy[keyof typeof EmailStrategy];


export function instanceOfEmailStrategy(value: any): boolean {
    for (const key in EmailStrategy) {
        if (Object.prototype.hasOwnProperty.call(EmailStrategy, key)) {
            if (EmailStrategy[key as keyof typeof EmailStrategy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EmailStrategyFromJSON(json: any): EmailStrategy {
    return EmailStrategyFromJSONTyped(json, false);
}

export function EmailStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailStrategy {
    return json as EmailStrategy;
}

export function EmailStrategyToJSON(value?: EmailStrategy | null): any {
    return value as any;
}

export function EmailStrategyToJSONTyped(value: any, ignoreDiscriminator: boolean): EmailStrategy {
    return value as EmailStrategy;
}

