/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntriesInfo
 */
export interface EntriesInfo {
    /**
     * 
     */
    mem?: number;
    /**
     * 
     */
    disk?: number;
    /**
     * 
     */
    space?: string;
}

/**
 * Check if a given object implements the EntriesInfo interface.
 */
export function instanceOfEntriesInfo(value: object): value is EntriesInfo {
    return true;
}

export function EntriesInfoFromJSON(json: any): EntriesInfo {
    return EntriesInfoFromJSONTyped(json, false);
}

export function EntriesInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntriesInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'mem': json['mem'] == null ? undefined : json['mem'],
        'disk': json['disk'] == null ? undefined : json['disk'],
        'space': json['space'] == null ? undefined : json['space'],
    };
}

export function EntriesInfoToJSON(json: any): EntriesInfo {
    return EntriesInfoToJSONTyped(json, false);
}

export function EntriesInfoToJSONTyped(value?: EntriesInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mem': value['mem'],
        'disk': value['disk'],
        'space': value['space'],
    };
}

