/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvaluateChangeQueryExpressionResultInfo
 */
export interface EvaluateChangeQueryExpressionResultInfo {
    /**
     * 
     */
    status?: boolean;
    /**
     * 
     */
    passingAtoms?: Array<string>;
    /**
     * 
     */
    failingAtoms?: Array<string>;
    /**
     * 
     */
    atomExplanations?: { [key: string]: string; };
}

/**
 * Check if a given object implements the EvaluateChangeQueryExpressionResultInfo interface.
 */
export function instanceOfEvaluateChangeQueryExpressionResultInfo(value: object): value is EvaluateChangeQueryExpressionResultInfo {
    return true;
}

export function EvaluateChangeQueryExpressionResultInfoFromJSON(json: any): EvaluateChangeQueryExpressionResultInfo {
    return EvaluateChangeQueryExpressionResultInfoFromJSONTyped(json, false);
}

export function EvaluateChangeQueryExpressionResultInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvaluateChangeQueryExpressionResultInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'passingAtoms': json['passing_atoms'] == null ? undefined : json['passing_atoms'],
        'failingAtoms': json['failing_atoms'] == null ? undefined : json['failing_atoms'],
        'atomExplanations': json['atom_explanations'] == null ? undefined : json['atom_explanations'],
    };
}

export function EvaluateChangeQueryExpressionResultInfoToJSON(json: any): EvaluateChangeQueryExpressionResultInfo {
    return EvaluateChangeQueryExpressionResultInfoToJSONTyped(json, false);
}

export function EvaluateChangeQueryExpressionResultInfoToJSONTyped(value?: EvaluateChangeQueryExpressionResultInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'passing_atoms': value['passingAtoms'],
        'failing_atoms': value['failingAtoms'],
        'atom_explanations': value['atomExplanations'],
    };
}

