/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileContentInput
 */
export interface FileContentInput {
    /**
     * 
     */
    content?: object;
    /**
     * 
     */
    binaryContent?: string;
    /**
     * 
     */
    fileMode?: number;
}

/**
 * Check if a given object implements the FileContentInput interface.
 */
export function instanceOfFileContentInput(value: object): value is FileContentInput {
    return true;
}

export function FileContentInputFromJSON(json: any): FileContentInput {
    return FileContentInputFromJSONTyped(json, false);
}

export function FileContentInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileContentInput {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'binaryContent': json['binary_content'] == null ? undefined : json['binary_content'],
        'fileMode': json['file_mode'] == null ? undefined : json['file_mode'],
    };
}

export function FileContentInputToJSON(json: any): FileContentInput {
    return FileContentInputToJSONTyped(json, false);
}

export function FileContentInputToJSONTyped(value?: FileContentInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'binary_content': value['binaryContent'],
        'file_mode': value['fileMode'],
    };
}

