/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebLinkInfo } from './WebLinkInfo';
import {
    WebLinkInfoFromJSON,
    WebLinkInfoFromJSONTyped,
    WebLinkInfoToJSON,
    WebLinkInfoToJSONTyped,
} from './WebLinkInfo';

/**
 * 
 * @export
 * @interface FileMeta
 */
export interface FileMeta {
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    contentType?: string;
    /**
     * 
     */
    lines?: number;
    /**
     * 
     */
    webLinks?: Array<WebLinkInfo>;
}

/**
 * Check if a given object implements the FileMeta interface.
 */
export function instanceOfFileMeta(value: object): value is FileMeta {
    return true;
}

export function FileMetaFromJSON(json: any): FileMeta {
    return FileMetaFromJSONTyped(json, false);
}

export function FileMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'contentType': json['content_type'] == null ? undefined : json['content_type'],
        'lines': json['lines'] == null ? undefined : json['lines'],
        'webLinks': json['web_links'] == null ? undefined : ((json['web_links'] as Array<any>).map(WebLinkInfoFromJSON)),
    };
}

export function FileMetaToJSON(json: any): FileMeta {
    return FileMetaToJSONTyped(json, false);
}

export function FileMetaToJSONTyped(value?: FileMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'content_type': value['contentType'],
        'lines': value['lines'],
        'web_links': value['webLinks'] == null ? undefined : ((value['webLinks'] as Array<any>).map(WebLinkInfoToJSON)),
    };
}

