/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileContentInput
 */
export interface FileContentInput {
    /**
     * 
     */
    content?: object;
    /**
     * The file content as a base-64 encoded data URI. If no content is provided, an empty is created or if an existing file is updated the file content is removed so that the file becomes empty. The content must be a SHA1 if the file mode is 160000 (gitlink).
     */
    binaryContent?: string;
    /**
     * The file mode in octal format. Supported values are 100644 (regular file), 100755 (executable file), 120000 (symlink) and 160000 (gitlink). If unset, new files are created with file mode 100644 (regular file) and for existing files the existing file mode is kept.
     */
    fileMode?: number;
}

/**
 * Check if a given object implements the FileContentInput interface.
 */
export function instanceOfFileContentInput(value: object): value is FileContentInput {
    return true;
}

export function FileContentInputFromJSON(json: any): FileContentInput {
    return FileContentInputFromJSONTyped(json, false);
}

export function FileContentInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileContentInput {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'binaryContent': json['binary_content'] == null ? undefined : json['binary_content'],
        'fileMode': json['file_mode'] == null ? undefined : json['file_mode'],
    };
}

export function FileContentInputToJSON(json: any): FileContentInput {
    return FileContentInputToJSONTyped(json, false);
}

export function FileContentInputToJSONTyped(value?: FileContentInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'binary_content': value['binaryContent'],
        'file_mode': value['fileMode'],
    };
}

