/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FixInput
 */
export interface FixInput {
    /**
     * 
     */
    deletePatchSetIfCommitMissing?: boolean;
    /**
     * 
     */
    expectMergedAs?: string;
}

/**
 * Check if a given object implements the FixInput interface.
 */
export function instanceOfFixInput(value: object): value is FixInput {
    return true;
}

export function FixInputFromJSON(json: any): FixInput {
    return FixInputFromJSONTyped(json, false);
}

export function FixInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FixInput {
    if (json == null) {
        return json;
    }
    return {
        
        'deletePatchSetIfCommitMissing': json['delete_patch_set_if_commit_missing'] == null ? undefined : json['delete_patch_set_if_commit_missing'],
        'expectMergedAs': json['expect_merged_as'] == null ? undefined : json['expect_merged_as'],
    };
}

export function FixInputToJSON(json: any): FixInput {
    return FixInputToJSONTyped(json, false);
}

export function FixInputToJSONTyped(value?: FixInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'delete_patch_set_if_commit_missing': value['deletePatchSetIfCommitMissing'],
        'expect_merged_as': value['expectMergedAs'],
    };
}

