/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Range } from './Range';
import {
    RangeFromJSON,
    RangeFromJSONTyped,
    RangeToJSON,
    RangeToJSONTyped,
} from './Range';

/**
 * 
 * @export
 * @interface FixReplacementInfo
 */
export interface FixReplacementInfo {
    /**
     * The path of the file which should be modified. Any file in the repository may be modified. The commit message can be modified via the magic file /COMMIT_MSG though only the part below the generated header of that magic file can be modified.
     */
    path?: string;
    /**
     * A CommentRange indicating which content of the file should be replaced. Lines in the file are assumed to be separated by the line feed character.
     */
    range?: Range;
    /**
     * The content which should be used instead of the current one.
     */
    replacement?: string;
}

/**
 * Check if a given object implements the FixReplacementInfo interface.
 */
export function instanceOfFixReplacementInfo(value: object): value is FixReplacementInfo {
    return true;
}

export function FixReplacementInfoFromJSON(json: any): FixReplacementInfo {
    return FixReplacementInfoFromJSONTyped(json, false);
}

export function FixReplacementInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FixReplacementInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'] == null ? undefined : json['path'],
        'range': json['range'] == null ? undefined : RangeFromJSON(json['range']),
        'replacement': json['replacement'] == null ? undefined : json['replacement'],
    };
}

export function FixReplacementInfoToJSON(json: any): FixReplacementInfo {
    return FixReplacementInfoToJSONTyped(json, false);
}

export function FixReplacementInfoToJSONTyped(value?: FixReplacementInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'range': RangeToJSON(value['range']),
        'replacement': value['replacement'],
    };
}

