/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FlowActionInfo
 */
export interface FlowActionInfo {
    /**
     * The name of the action. Which actions are supported depends on the flow service implementation.
     */
    name?: string;
    /**
     * Parameters for the action as list of strings. Which parameters are supported and their format depends on the flow service implementation.
     */
    parameters?: Array<string>;
}

/**
 * Check if a given object implements the FlowActionInfo interface.
 */
export function instanceOfFlowActionInfo(value: object): value is FlowActionInfo {
    return true;
}

export function FlowActionInfoFromJSON(json: any): FlowActionInfo {
    return FlowActionInfoFromJSONTyped(json, false);
}

export function FlowActionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowActionInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
    };
}

export function FlowActionInfoToJSON(json: any): FlowActionInfo {
    return FlowActionInfoToJSONTyped(json, false);
}

export function FlowActionInfoToJSONTyped(value?: FlowActionInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'parameters': value['parameters'],
    };
}

