/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FlowActionInfo } from './FlowActionInfo';
import {
    FlowActionInfoFromJSON,
    FlowActionInfoFromJSONTyped,
    FlowActionInfoToJSON,
    FlowActionInfoToJSONTyped,
} from './FlowActionInfo';

/**
 * 
 * @export
 * @interface FlowExpressionInfo
 */
export interface FlowExpressionInfo {
    /**
     * The condition which must be satisfied for the action to be triggered. Can contain multiple conditions separated by comma. The syntax of the condition depends on the flow service implementation.
     */
    condition?: string;
    /**
     * The action that should be triggered when the condition is satisfied as a FlowActionInfo entity.
     */
    action?: FlowActionInfo;
}

/**
 * Check if a given object implements the FlowExpressionInfo interface.
 */
export function instanceOfFlowExpressionInfo(value: object): value is FlowExpressionInfo {
    return true;
}

export function FlowExpressionInfoFromJSON(json: any): FlowExpressionInfo {
    return FlowExpressionInfoFromJSONTyped(json, false);
}

export function FlowExpressionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowExpressionInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'condition': json['condition'] == null ? undefined : json['condition'],
        'action': json['action'] == null ? undefined : FlowActionInfoFromJSON(json['action']),
    };
}

export function FlowExpressionInfoToJSON(json: any): FlowExpressionInfo {
    return FlowExpressionInfoToJSONTyped(json, false);
}

export function FlowExpressionInfoToJSONTyped(value?: FlowExpressionInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'condition': value['condition'],
        'action': FlowActionInfoToJSON(value['action']),
    };
}

