/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FlowStageState = {
    Pending: 'PENDING',
    Done: 'DONE',
    Failed: 'FAILED',
    Terminated: 'TERMINATED',
} as const;
export type FlowStageState = typeof FlowStageState[keyof typeof FlowStageState];


export function instanceOfFlowStageState(value: any): boolean {
    for (const key in FlowStageState) {
        if (Object.prototype.hasOwnProperty.call(FlowStageState, key)) {
            if (FlowStageState[key as keyof typeof FlowStageState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FlowStageStateFromJSON(json: any): FlowStageState {
    return FlowStageStateFromJSONTyped(json, false);
}

export function FlowStageStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowStageState {
    return json as FlowStageState;
}

export function FlowStageStateToJSON(value?: FlowStageState | null): any {
    return value as any;
}

export function FlowStageStateToJSONTyped(value: any, ignoreDiscriminator: boolean): FlowStageState {
    return value as FlowStageState;
}

