/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FlowExpressionInfo } from './FlowExpressionInfo';
import {
    FlowExpressionInfoFromJSON,
    FlowExpressionInfoFromJSONTyped,
    FlowExpressionInfoToJSON,
    FlowExpressionInfoToJSONTyped,
} from './FlowExpressionInfo';
import type { FlowStageState } from './FlowStageState';
import {
    FlowStageStateFromJSON,
    FlowStageStateFromJSONTyped,
    FlowStageStateToJSON,
    FlowStageStateToJSONTyped,
} from './FlowStageState';

/**
 * 
 * @export
 * @interface FlowStageInfo
 */
export interface FlowStageInfo {
    /**
     * 
     */
    expression?: FlowExpressionInfo;
    /**
     * 
     */
    state?: FlowStageState;
    /**
     * 
     */
    message?: string;
}



/**
 * Check if a given object implements the FlowStageInfo interface.
 */
export function instanceOfFlowStageInfo(value: object): value is FlowStageInfo {
    return true;
}

export function FlowStageInfoFromJSON(json: any): FlowStageInfo {
    return FlowStageInfoFromJSONTyped(json, false);
}

export function FlowStageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowStageInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'expression': json['expression'] == null ? undefined : FlowExpressionInfoFromJSON(json['expression']),
        'state': json['state'] == null ? undefined : FlowStageStateFromJSON(json['state']),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function FlowStageInfoToJSON(json: any): FlowStageInfo {
    return FlowStageInfoToJSONTyped(json, false);
}

export function FlowStageInfoToJSONTyped(value?: FlowStageInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expression': FlowExpressionInfoToJSON(value['expression']),
        'state': FlowStageStateToJSON(value['state']),
        'message': value['message'],
    };
}

