/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeFormat } from './TimeFormat';
import {
    TimeFormatFromJSON,
    TimeFormatFromJSONTyped,
    TimeFormatToJSON,
    TimeFormatToJSONTyped,
} from './TimeFormat';
import type { DateFormat } from './DateFormat';
import {
    DateFormatFromJSON,
    DateFormatFromJSONTyped,
    DateFormatToJSON,
    DateFormatToJSONTyped,
} from './DateFormat';
import type { DefaultBase } from './DefaultBase';
import {
    DefaultBaseFromJSON,
    DefaultBaseFromJSONTyped,
    DefaultBaseToJSON,
    DefaultBaseToJSONTyped,
} from './DefaultBase';
import type { DiffView } from './DiffView';
import {
    DiffViewFromJSON,
    DiffViewFromJSONTyped,
    DiffViewToJSON,
    DiffViewToJSONTyped,
} from './DiffView';
import type { Theme } from './Theme';
import {
    ThemeFromJSON,
    ThemeFromJSONTyped,
    ThemeToJSON,
    ThemeToJSONTyped,
} from './Theme';
import type { MenuItem } from './MenuItem';
import {
    MenuItemFromJSON,
    MenuItemFromJSONTyped,
    MenuItemToJSON,
    MenuItemToJSONTyped,
} from './MenuItem';
import type { EmailFormat } from './EmailFormat';
import {
    EmailFormatFromJSON,
    EmailFormatFromJSONTyped,
    EmailFormatToJSON,
    EmailFormatToJSONTyped,
} from './EmailFormat';
import type { EmailStrategy } from './EmailStrategy';
import {
    EmailStrategyFromJSON,
    EmailStrategyFromJSONTyped,
    EmailStrategyToJSON,
    EmailStrategyToJSONTyped,
} from './EmailStrategy';

/**
 * 
 * @export
 * @interface GeneralPreferencesInfo
 */
export interface GeneralPreferencesInfo {
    /**
     * 
     */
    changesPerPage?: number;
    /**
     * 
     */
    downloadScheme?: string;
    /**
     * 
     */
    theme?: Theme;
    /**
     * 
     */
    dateFormat?: DateFormat;
    /**
     * 
     */
    timeFormat?: TimeFormat;
    /**
     * 
     */
    expandInlineDiffs?: boolean;
    /**
     * 
     */
    relativeDateInChangeTable?: boolean;
    /**
     * 
     */
    diffView?: DiffView;
    /**
     * 
     */
    sizeBarInChangeTable?: boolean;
    /**
     * 
     */
    legacycidInChangeTable?: boolean;
    /**
     * 
     */
    muteCommonPathPrefixes?: boolean;
    /**
     * 
     */
    signedOffBy?: boolean;
    /**
     * 
     */
    emailStrategy?: EmailStrategy;
    /**
     * 
     */
    emailFormat?: EmailFormat;
    /**
     * 
     */
    defaultBaseForMerges?: DefaultBase;
    /**
     * 
     */
    publishCommentsOnPush?: boolean;
    /**
     * 
     */
    disableKeyboardShortcuts?: boolean;
    /**
     * 
     */
    disableTokenHighlighting?: boolean;
    /**
     * 
     */
    workInProgressByDefault?: boolean;
    /**
     * 
     */
    my?: Array<MenuItem>;
    /**
     * 
     */
    changeTable?: Array<string>;
    /**
     * 
     */
    allowBrowserNotifications?: boolean;
    /**
     * 
     */
    allowSuggestCodeWhileCommenting?: boolean;
    /**
     * 
     */
    allowAutocompletingComments?: boolean;
    /**
     * 
     */
    aiChatSelectedModel?: string;
    /**
     * 
     */
    labelFilter?: string;
    /**
     * 
     */
    diffPageSidebar?: string;
}



/**
 * Check if a given object implements the GeneralPreferencesInfo interface.
 */
export function instanceOfGeneralPreferencesInfo(value: object): value is GeneralPreferencesInfo {
    return true;
}

export function GeneralPreferencesInfoFromJSON(json: any): GeneralPreferencesInfo {
    return GeneralPreferencesInfoFromJSONTyped(json, false);
}

export function GeneralPreferencesInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralPreferencesInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'changesPerPage': json['changes_per_page'] == null ? undefined : json['changes_per_page'],
        'downloadScheme': json['download_scheme'] == null ? undefined : json['download_scheme'],
        'theme': json['theme'] == null ? undefined : ThemeFromJSON(json['theme']),
        'dateFormat': json['date_format'] == null ? undefined : DateFormatFromJSON(json['date_format']),
        'timeFormat': json['time_format'] == null ? undefined : TimeFormatFromJSON(json['time_format']),
        'expandInlineDiffs': json['expand_inline_diffs'] == null ? undefined : json['expand_inline_diffs'],
        'relativeDateInChangeTable': json['relative_date_in_change_table'] == null ? undefined : json['relative_date_in_change_table'],
        'diffView': json['diff_view'] == null ? undefined : DiffViewFromJSON(json['diff_view']),
        'sizeBarInChangeTable': json['size_bar_in_change_table'] == null ? undefined : json['size_bar_in_change_table'],
        'legacycidInChangeTable': json['legacycid_in_change_table'] == null ? undefined : json['legacycid_in_change_table'],
        'muteCommonPathPrefixes': json['mute_common_path_prefixes'] == null ? undefined : json['mute_common_path_prefixes'],
        'signedOffBy': json['signed_off_by'] == null ? undefined : json['signed_off_by'],
        'emailStrategy': json['email_strategy'] == null ? undefined : EmailStrategyFromJSON(json['email_strategy']),
        'emailFormat': json['email_format'] == null ? undefined : EmailFormatFromJSON(json['email_format']),
        'defaultBaseForMerges': json['default_base_for_merges'] == null ? undefined : DefaultBaseFromJSON(json['default_base_for_merges']),
        'publishCommentsOnPush': json['publish_comments_on_push'] == null ? undefined : json['publish_comments_on_push'],
        'disableKeyboardShortcuts': json['disable_keyboard_shortcuts'] == null ? undefined : json['disable_keyboard_shortcuts'],
        'disableTokenHighlighting': json['disable_token_highlighting'] == null ? undefined : json['disable_token_highlighting'],
        'workInProgressByDefault': json['work_in_progress_by_default'] == null ? undefined : json['work_in_progress_by_default'],
        'my': json['my'] == null ? undefined : ((json['my'] as Array<any>).map(MenuItemFromJSON)),
        'changeTable': json['change_table'] == null ? undefined : json['change_table'],
        'allowBrowserNotifications': json['allow_browser_notifications'] == null ? undefined : json['allow_browser_notifications'],
        'allowSuggestCodeWhileCommenting': json['allow_suggest_code_while_commenting'] == null ? undefined : json['allow_suggest_code_while_commenting'],
        'allowAutocompletingComments': json['allow_autocompleting_comments'] == null ? undefined : json['allow_autocompleting_comments'],
        'aiChatSelectedModel': json['ai_chat_selected_model'] == null ? undefined : json['ai_chat_selected_model'],
        'labelFilter': json['label_filter'] == null ? undefined : json['label_filter'],
        'diffPageSidebar': json['diff_page_sidebar'] == null ? undefined : json['diff_page_sidebar'],
    };
}

export function GeneralPreferencesInfoToJSON(json: any): GeneralPreferencesInfo {
    return GeneralPreferencesInfoToJSONTyped(json, false);
}

export function GeneralPreferencesInfoToJSONTyped(value?: GeneralPreferencesInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'changes_per_page': value['changesPerPage'],
        'download_scheme': value['downloadScheme'],
        'theme': ThemeToJSON(value['theme']),
        'date_format': DateFormatToJSON(value['dateFormat']),
        'time_format': TimeFormatToJSON(value['timeFormat']),
        'expand_inline_diffs': value['expandInlineDiffs'],
        'relative_date_in_change_table': value['relativeDateInChangeTable'],
        'diff_view': DiffViewToJSON(value['diffView']),
        'size_bar_in_change_table': value['sizeBarInChangeTable'],
        'legacycid_in_change_table': value['legacycidInChangeTable'],
        'mute_common_path_prefixes': value['muteCommonPathPrefixes'],
        'signed_off_by': value['signedOffBy'],
        'email_strategy': EmailStrategyToJSON(value['emailStrategy']),
        'email_format': EmailFormatToJSON(value['emailFormat']),
        'default_base_for_merges': DefaultBaseToJSON(value['defaultBaseForMerges']),
        'publish_comments_on_push': value['publishCommentsOnPush'],
        'disable_keyboard_shortcuts': value['disableKeyboardShortcuts'],
        'disable_token_highlighting': value['disableTokenHighlighting'],
        'work_in_progress_by_default': value['workInProgressByDefault'],
        'my': value['my'] == null ? undefined : ((value['my'] as Array<any>).map(MenuItemToJSON)),
        'change_table': value['changeTable'],
        'allow_browser_notifications': value['allowBrowserNotifications'],
        'allow_suggest_code_while_commenting': value['allowSuggestCodeWhileCommenting'],
        'allow_autocompleting_comments': value['allowAutocompletingComments'],
        'ai_chat_selected_model': value['aiChatSelectedModel'],
        'label_filter': value['labelFilter'],
        'diff_page_sidebar': value['diffPageSidebar'],
    };
}

