/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeFormat } from './TimeFormat';
import {
    TimeFormatFromJSON,
    TimeFormatFromJSONTyped,
    TimeFormatToJSON,
    TimeFormatToJSONTyped,
} from './TimeFormat';
import type { DateFormat } from './DateFormat';
import {
    DateFormatFromJSON,
    DateFormatFromJSONTyped,
    DateFormatToJSON,
    DateFormatToJSONTyped,
} from './DateFormat';
import type { DefaultBase } from './DefaultBase';
import {
    DefaultBaseFromJSON,
    DefaultBaseFromJSONTyped,
    DefaultBaseToJSON,
    DefaultBaseToJSONTyped,
} from './DefaultBase';
import type { DiffView } from './DiffView';
import {
    DiffViewFromJSON,
    DiffViewFromJSONTyped,
    DiffViewToJSON,
    DiffViewToJSONTyped,
} from './DiffView';
import type { Theme } from './Theme';
import {
    ThemeFromJSON,
    ThemeFromJSONTyped,
    ThemeToJSON,
    ThemeToJSONTyped,
} from './Theme';
import type { MenuItem } from './MenuItem';
import {
    MenuItemFromJSON,
    MenuItemFromJSONTyped,
    MenuItemToJSON,
    MenuItemToJSONTyped,
} from './MenuItem';
import type { EmailFormat } from './EmailFormat';
import {
    EmailFormatFromJSON,
    EmailFormatFromJSONTyped,
    EmailFormatToJSON,
    EmailFormatToJSONTyped,
} from './EmailFormat';
import type { EmailStrategy } from './EmailStrategy';
import {
    EmailStrategyFromJSON,
    EmailStrategyFromJSONTyped,
    EmailStrategyToJSON,
    EmailStrategyToJSONTyped,
} from './EmailStrategy';

/**
 * 
 * @export
 * @interface GeneralPreferencesInfo
 */
export interface GeneralPreferencesInfo {
    /**
     * The number of changes to show on each page. Allowed values are 10, 25, 50, 100.
     */
    changesPerPage?: number;
    /**
     * The type of download URL the user prefers to use. May be any key from the schemes map in DownloadInfo.
     */
    downloadScheme?: string;
    /**
     * Which theme to use. Allowed values are AUTO or DARK or LIGHT.
     */
    theme?: Theme;
    /**
     * The format to display the date in. Allowed values are STD, US, ISO, EURO, UK.
     */
    dateFormat?: DateFormat;
    /**
     * The format to display the time in. Allowed values are HHMM_12, HHMM_24.
     */
    timeFormat?: TimeFormat;
    /**
     * Whether to expand diffs inline instead of opening as separate page (Gerrit web app UI only).
     */
    expandInlineDiffs?: boolean;
    /**
     * Whether to show relative dates in the changes table.
     */
    relativeDateInChangeTable?: boolean;
    /**
     * The type of diff view to show. Allowed values are SIDE_BY_SIDE, UNIFIED_DIFF.
     */
    diffView?: DiffView;
    /**
     * Whether to show the change sizes as colored bars in the change table.
     */
    sizeBarInChangeTable?: boolean;
    /**
     * Whether to show change number in the change table.
     */
    legacycidInChangeTable?: boolean;
    /**
     * Whether to mute common path prefixes in file names in the file table.
     */
    muteCommonPathPrefixes?: boolean;
    /**
     * Whether to insert Signed-off-by footer in changes created with the inline edit feature.
     */
    signedOffBy?: boolean;
    /**
     * The type of email strategy to use. On ENABLED, the user will receive emails from Gerrit. On CC_ON_OWN_COMMENTS the user will also receive emails for their own comments. On ATTENTION_SET_ONLY, on emails about changes, the user will receive emails only if they are in the attention set of that change.
     */
    emailStrategy?: EmailStrategy;
    /**
     * The format to use for outgoing email. Allowed values are PLAINTEXT and HTML_PLAINTEXT.
     */
    emailFormat?: EmailFormat;
    /**
     * The base which should be pre-selected in the 'Diff Against' drop-down list when the change screen is opened for a merge commit. Allowed values are AUTO_MERGE and FIRST_PARENT.
     */
    defaultBaseForMerges?: DefaultBase;
    /**
     * Whether to publish draft comments on push by default.
     */
    publishCommentsOnPush?: boolean;
    /**
     * Whether to disable all keyboard shortcuts.
     */
    disableKeyboardShortcuts?: boolean;
    /**
     * Whether to disable token highlighting on hover.
     */
    disableTokenHighlighting?: boolean;
    /**
     * Whether to set work-in-progress on push or on create changes online by default.
     */
    workInProgressByDefault?: boolean;
    /**
     * The menu items of the MY top menu as a list of TopMenuItemInfo entities.
     */
    my?: Array<MenuItem>;
    /**
     * The columns to display in the change table (Gerrit web app UI only). The default is empty, which will default columns as determined by the frontend.
     */
    changeTable?: Array<string>;
    /**
     * Whether to prompt user to enable browser notification in browser.
     */
    allowBrowserNotifications?: boolean;
    /**
     * Whether to receive suggested code while writing comments. This feature needs a plugin implementation.
     */
    allowSuggestCodeWhileCommenting?: boolean;
    /**
     * Whether to receive autocompletions while writing comments. This feature needs a plugin implementation.
     */
    allowAutocompletingComments?: boolean;
    /**
     * The name of the AI model selected for the AI chat. This feature needs a plugin implementation.
     */
    aiChatSelectedModel?: string;
    /**
     * A comma-separated list of label names that limits which label columns are shown in the change table. If empty, all labels are shown.
     */
    labelFilter?: string;
    /**
     * String indicating which sidebar should be open on the diff page. Set to "NONE" if no sidebars should be open. Plugin-supplied sidebars will be prefixed with "plugin-".
     */
    diffPageSidebar?: string;
}



/**
 * Check if a given object implements the GeneralPreferencesInfo interface.
 */
export function instanceOfGeneralPreferencesInfo(value: object): value is GeneralPreferencesInfo {
    return true;
}

export function GeneralPreferencesInfoFromJSON(json: any): GeneralPreferencesInfo {
    return GeneralPreferencesInfoFromJSONTyped(json, false);
}

export function GeneralPreferencesInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralPreferencesInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'changesPerPage': json['changes_per_page'] == null ? undefined : json['changes_per_page'],
        'downloadScheme': json['download_scheme'] == null ? undefined : json['download_scheme'],
        'theme': json['theme'] == null ? undefined : ThemeFromJSON(json['theme']),
        'dateFormat': json['date_format'] == null ? undefined : DateFormatFromJSON(json['date_format']),
        'timeFormat': json['time_format'] == null ? undefined : TimeFormatFromJSON(json['time_format']),
        'expandInlineDiffs': json['expand_inline_diffs'] == null ? undefined : json['expand_inline_diffs'],
        'relativeDateInChangeTable': json['relative_date_in_change_table'] == null ? undefined : json['relative_date_in_change_table'],
        'diffView': json['diff_view'] == null ? undefined : DiffViewFromJSON(json['diff_view']),
        'sizeBarInChangeTable': json['size_bar_in_change_table'] == null ? undefined : json['size_bar_in_change_table'],
        'legacycidInChangeTable': json['legacycid_in_change_table'] == null ? undefined : json['legacycid_in_change_table'],
        'muteCommonPathPrefixes': json['mute_common_path_prefixes'] == null ? undefined : json['mute_common_path_prefixes'],
        'signedOffBy': json['signed_off_by'] == null ? undefined : json['signed_off_by'],
        'emailStrategy': json['email_strategy'] == null ? undefined : EmailStrategyFromJSON(json['email_strategy']),
        'emailFormat': json['email_format'] == null ? undefined : EmailFormatFromJSON(json['email_format']),
        'defaultBaseForMerges': json['default_base_for_merges'] == null ? undefined : DefaultBaseFromJSON(json['default_base_for_merges']),
        'publishCommentsOnPush': json['publish_comments_on_push'] == null ? undefined : json['publish_comments_on_push'],
        'disableKeyboardShortcuts': json['disable_keyboard_shortcuts'] == null ? undefined : json['disable_keyboard_shortcuts'],
        'disableTokenHighlighting': json['disable_token_highlighting'] == null ? undefined : json['disable_token_highlighting'],
        'workInProgressByDefault': json['work_in_progress_by_default'] == null ? undefined : json['work_in_progress_by_default'],
        'my': json['my'] == null ? undefined : ((json['my'] as Array<any>).map(MenuItemFromJSON)),
        'changeTable': json['change_table'] == null ? undefined : json['change_table'],
        'allowBrowserNotifications': json['allow_browser_notifications'] == null ? undefined : json['allow_browser_notifications'],
        'allowSuggestCodeWhileCommenting': json['allow_suggest_code_while_commenting'] == null ? undefined : json['allow_suggest_code_while_commenting'],
        'allowAutocompletingComments': json['allow_autocompleting_comments'] == null ? undefined : json['allow_autocompleting_comments'],
        'aiChatSelectedModel': json['ai_chat_selected_model'] == null ? undefined : json['ai_chat_selected_model'],
        'labelFilter': json['label_filter'] == null ? undefined : json['label_filter'],
        'diffPageSidebar': json['diff_page_sidebar'] == null ? undefined : json['diff_page_sidebar'],
    };
}

export function GeneralPreferencesInfoToJSON(json: any): GeneralPreferencesInfo {
    return GeneralPreferencesInfoToJSONTyped(json, false);
}

export function GeneralPreferencesInfoToJSONTyped(value?: GeneralPreferencesInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'changes_per_page': value['changesPerPage'],
        'download_scheme': value['downloadScheme'],
        'theme': ThemeToJSON(value['theme']),
        'date_format': DateFormatToJSON(value['dateFormat']),
        'time_format': TimeFormatToJSON(value['timeFormat']),
        'expand_inline_diffs': value['expandInlineDiffs'],
        'relative_date_in_change_table': value['relativeDateInChangeTable'],
        'diff_view': DiffViewToJSON(value['diffView']),
        'size_bar_in_change_table': value['sizeBarInChangeTable'],
        'legacycid_in_change_table': value['legacycidInChangeTable'],
        'mute_common_path_prefixes': value['muteCommonPathPrefixes'],
        'signed_off_by': value['signedOffBy'],
        'email_strategy': EmailStrategyToJSON(value['emailStrategy']),
        'email_format': EmailFormatToJSON(value['emailFormat']),
        'default_base_for_merges': DefaultBaseToJSON(value['defaultBaseForMerges']),
        'publish_comments_on_push': value['publishCommentsOnPush'],
        'disable_keyboard_shortcuts': value['disableKeyboardShortcuts'],
        'disable_token_highlighting': value['disableTokenHighlighting'],
        'work_in_progress_by_default': value['workInProgressByDefault'],
        'my': value['my'] == null ? undefined : ((value['my'] as Array<any>).map(MenuItemToJSON)),
        'change_table': value['changeTable'],
        'allow_browser_notifications': value['allowBrowserNotifications'],
        'allow_suggest_code_while_commenting': value['allowSuggestCodeWhileCommenting'],
        'allow_autocompleting_comments': value['allowAutocompletingComments'],
        'ai_chat_selected_model': value['aiChatSelectedModel'],
        'label_filter': value['labelFilter'],
        'diff_page_sidebar': value['diffPageSidebar'],
    };
}

