/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetConfigServerVersion200ResponseOneOf
 */
export interface GetConfigServerVersion200ResponseOneOf {
    /**
     * 
     */
    gerritVersion?: string;
    /**
     * 
     */
    noteDbVersion?: number;
    /**
     * 
     */
    changeIndexVersion?: number;
    /**
     * 
     */
    accountIndexVersion?: number;
    /**
     * 
     */
    projectIndexVersion?: number;
    /**
     * 
     */
    groupIndexVersion?: number;
}

/**
 * Check if a given object implements the GetConfigServerVersion200ResponseOneOf interface.
 */
export function instanceOfGetConfigServerVersion200ResponseOneOf(value: object): value is GetConfigServerVersion200ResponseOneOf {
    return true;
}

export function GetConfigServerVersion200ResponseOneOfFromJSON(json: any): GetConfigServerVersion200ResponseOneOf {
    return GetConfigServerVersion200ResponseOneOfFromJSONTyped(json, false);
}

export function GetConfigServerVersion200ResponseOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConfigServerVersion200ResponseOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'gerritVersion': json['gerrit_version'] == null ? undefined : json['gerrit_version'],
        'noteDbVersion': json['note_db_version'] == null ? undefined : json['note_db_version'],
        'changeIndexVersion': json['change_index_version'] == null ? undefined : json['change_index_version'],
        'accountIndexVersion': json['account_index_version'] == null ? undefined : json['account_index_version'],
        'projectIndexVersion': json['project_index_version'] == null ? undefined : json['project_index_version'],
        'groupIndexVersion': json['group_index_version'] == null ? undefined : json['group_index_version'],
    };
}

export function GetConfigServerVersion200ResponseOneOfToJSON(json: any): GetConfigServerVersion200ResponseOneOf {
    return GetConfigServerVersion200ResponseOneOfToJSONTyped(json, false);
}

export function GetConfigServerVersion200ResponseOneOfToJSONTyped(value?: GetConfigServerVersion200ResponseOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gerrit_version': value['gerritVersion'],
        'note_db_version': value['noteDbVersion'],
        'change_index_version': value['changeIndexVersion'],
        'account_index_version': value['accountIndexVersion'],
        'project_index_version': value['projectIndexVersion'],
        'group_index_version': value['groupIndexVersion'],
    };
}

