/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiffWebLinkInfo } from './DiffWebLinkInfo';
import {
    DiffWebLinkInfoFromJSON,
    DiffWebLinkInfoFromJSONTyped,
    DiffWebLinkInfoToJSON,
    DiffWebLinkInfoToJSONTyped,
} from './DiffWebLinkInfo';

/**
 * 
 * @export
 * @interface GetMetaFileInfo
 */
export interface GetMetaFileInfo {
    /**
     * 
     */
    webLinks?: Array<DiffWebLinkInfo>;
}

/**
 * Check if a given object implements the GetMetaFileInfo interface.
 */
export function instanceOfGetMetaFileInfo(value: object): value is GetMetaFileInfo {
    return true;
}

export function GetMetaFileInfoFromJSON(json: any): GetMetaFileInfo {
    return GetMetaFileInfoFromJSONTyped(json, false);
}

export function GetMetaFileInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMetaFileInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'webLinks': json['web_links'] == null ? undefined : ((json['web_links'] as Array<any>).map(DiffWebLinkInfoFromJSON)),
    };
}

export function GetMetaFileInfoToJSON(json: any): GetMetaFileInfo {
    return GetMetaFileInfoToJSONTyped(json, false);
}

export function GetMetaFileInfoToJSONTyped(value?: GetMetaFileInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'web_links': value['webLinks'] == null ? undefined : ((value['webLinks'] as Array<any>).map(DiffWebLinkInfoToJSON)),
    };
}

