/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { ProjectInfo } from './ProjectInfo';
import {
    instanceOfProjectInfo,
    ProjectInfoFromJSON,
    ProjectInfoFromJSONTyped,
    ProjectInfoToJSON,
} from './ProjectInfo';
import type { any } from './any';
import {
    instanceOfany,
    anyFromJSON,
    anyFromJSONTyped,
    anyToJSON,
} from './any';

/**
 * @type GetProjectsDefaultResponse
 * 
 * @export
 */
export type GetProjectsDefaultResponse = Array<ProjectInfo> | { [key: string]: ProjectInfo; };

export function GetProjectsDefaultResponseFromJSON(json: any): GetProjectsDefaultResponse {
    return GetProjectsDefaultResponseFromJSONTyped(json, false);
}

export function GetProjectsDefaultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProjectsDefaultResponse {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfany(json)) {
        return anyFromJSONTyped(json, true);
    }
    if (Array.isArray(json)) {
        if (json.every(item => typeof item === 'object')) {
            if (json.every(item => instanceOfProjectInfo(item))) {
                return json.map(value => ProjectInfoFromJSONTyped(value, true));
            }
        }
    }
    if (Array.isArray(json)) {
        return json;
    }
    return {} as any;
}

export function GetProjectsDefaultResponseToJSON(json: any): any {
    return GetProjectsDefaultResponseToJSONTyped(json, false);
}

export function GetProjectsDefaultResponseToJSONTyped(value?: GetProjectsDefaultResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfany(value)) {
        return anyToJSON(value as any);
    }
    if (Array.isArray(value)) {
        if (value.every(item => typeof item === 'object')) {
            if (value.every(item => instanceOfProjectInfo(item))) {
                return value.map(value => ProjectInfoToJSON(value as ProjectInfo));
            }
        }
    }
    if (Array.isArray(value)) {
        return value;
    }
    return {};
}

