/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GitBasicAuthPolicy = {
    Http: 'HTTP',
    Ldap: 'LDAP',
    HttpLdap: 'HTTP_LDAP',
    Oauth: 'OAUTH',
} as const;
export type GitBasicAuthPolicy = typeof GitBasicAuthPolicy[keyof typeof GitBasicAuthPolicy];


export function instanceOfGitBasicAuthPolicy(value: any): boolean {
    for (const key in GitBasicAuthPolicy) {
        if (Object.prototype.hasOwnProperty.call(GitBasicAuthPolicy, key)) {
            if (GitBasicAuthPolicy[key as keyof typeof GitBasicAuthPolicy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GitBasicAuthPolicyFromJSON(json: any): GitBasicAuthPolicy {
    return GitBasicAuthPolicyFromJSONTyped(json, false);
}

export function GitBasicAuthPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitBasicAuthPolicy {
    return json as GitBasicAuthPolicy;
}

export function GitBasicAuthPolicyToJSON(value?: GitBasicAuthPolicy | null): any {
    return value as any;
}

export function GitBasicAuthPolicyToJSONTyped(value: any, ignoreDiscriminator: boolean): GitBasicAuthPolicy {
    return value as GitBasicAuthPolicy;
}

