/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GpgKeyInfoStatus } from './GpgKeyInfoStatus';
import {
    GpgKeyInfoStatusFromJSON,
    GpgKeyInfoStatusFromJSONTyped,
    GpgKeyInfoStatusToJSON,
    GpgKeyInfoStatusToJSONTyped,
} from './GpgKeyInfoStatus';

/**
 * 
 * @export
 * @interface GpgKeyInfo
 */
export interface GpgKeyInfo {
    /**
     * The 8-char hex GPG key ID.
     */
    id?: string;
    /**
     * The 40-char (plus spaces) hex GPG key fingerprint.
     */
    fingerprint?: string;
    /**
     * OpenPGP User IDs,role=external,window=_blank associated with the public key.
     */
    userIds?: Array<string>;
    /**
     * ASCII armored public key material.
     */
    key?: string;
    /**
     * The result of server-side checks on the key; one of BAD, OK, or TRUSTED. BAD keys have serious problems and should not be used. If a key is OK, inspecting only that key found no problems, but the system does not fully trust the key's origin.
     */
    status?: GpgKeyInfoStatus;
    /**
     * A list of human-readable problem strings found in the course of checking whether the key is valid and trusted.
     */
    problems?: Array<string>;
}



/**
 * Check if a given object implements the GpgKeyInfo interface.
 */
export function instanceOfGpgKeyInfo(value: object): value is GpgKeyInfo {
    return true;
}

export function GpgKeyInfoFromJSON(json: any): GpgKeyInfo {
    return GpgKeyInfoFromJSONTyped(json, false);
}

export function GpgKeyInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GpgKeyInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fingerprint': json['fingerprint'] == null ? undefined : json['fingerprint'],
        'userIds': json['user_ids'] == null ? undefined : json['user_ids'],
        'key': json['key'] == null ? undefined : json['key'],
        'status': json['status'] == null ? undefined : GpgKeyInfoStatusFromJSON(json['status']),
        'problems': json['problems'] == null ? undefined : json['problems'],
    };
}

export function GpgKeyInfoToJSON(json: any): GpgKeyInfo {
    return GpgKeyInfoToJSONTyped(json, false);
}

export function GpgKeyInfoToJSONTyped(value?: GpgKeyInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'fingerprint': value['fingerprint'],
        'user_ids': value['userIds'],
        'key': value['key'],
        'status': GpgKeyInfoStatusToJSON(value['status']),
        'problems': value['problems'],
    };
}

