/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GpgKeysInput
 */
export interface GpgKeysInput {
    /**
     * List of ASCII armored public key strings to add.
     */
    add?: Array<string>;
    /**
     * List of \{gpg-key-id\}s to delete.
     */
    _delete?: Array<string>;
}

/**
 * Check if a given object implements the GpgKeysInput interface.
 */
export function instanceOfGpgKeysInput(value: object): value is GpgKeysInput {
    return true;
}

export function GpgKeysInputFromJSON(json: any): GpgKeysInput {
    return GpgKeysInputFromJSONTyped(json, false);
}

export function GpgKeysInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GpgKeysInput {
    if (json == null) {
        return json;
    }
    return {
        
        'add': json['add'] == null ? undefined : json['add'],
        '_delete': json['delete'] == null ? undefined : json['delete'],
    };
}

export function GpgKeysInputToJSON(json: any): GpgKeysInput {
    return GpgKeysInputToJSONTyped(json, false);
}

export function GpgKeysInputToJSONTyped(value?: GpgKeysInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'add': value['add'],
        'delete': value['_delete'],
    };
}

