/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupOptionsInfo } from './GroupOptionsInfo';
import {
    GroupOptionsInfoFromJSON,
    GroupOptionsInfoFromJSONTyped,
    GroupOptionsInfoToJSON,
    GroupOptionsInfoToJSONTyped,
} from './GroupOptionsInfo';
import type { AccountInfo } from './AccountInfo';
import {
    AccountInfoFromJSON,
    AccountInfoFromJSONTyped,
    AccountInfoToJSON,
    AccountInfoToJSONTyped,
} from './AccountInfo';

/**
 * 
 * @export
 * @interface GroupInfo
 */
export interface GroupInfo {
    /**
     * URL to information about the group. Typically a URL to a web page that permits users to apply to join the group, or manage their membership.
     */
    url?: string;
    /**
     * Options of the group
     */
    options?: GroupOptionsInfo;
    /**
     * The description of the group.
     */
    description?: string;
    /**
     * The numeric ID of the group.
     */
    groupId?: number;
    /**
     * The name of the owner group.
     */
    owner?: string;
    /**
     * The URL encoded UUID of the owner group.
     */
    ownerId?: string;
    /**
     * The timestamp of when the group was created.
     */
    createdOn?: string;
    /**
     * Whether the query would deliver more results if not limited. + Only set on the last group that is returned by a group query.
     */
    moreGroups?: boolean;
    /**
     * A list of AccountInfo entities describing the direct members. + Only set if members are requested.
     */
    members?: Array<AccountInfo>;
    /**
     * A list of GroupInfo entities describing the direct subgroups. + Only set if subgroups are requested.
     */
    includes?: Array<GroupInfo>;
    /**
     * The URL encoded UUID of the group.
     */
    id?: string;
    /**
     * The name of the group. + For external groups the group name is missing if there is no group backend that can resolve the group UUID. E.g. this can happen when a plugin that provided a group backend was uninstalled.
     */
    name?: string;
}

/**
 * Check if a given object implements the GroupInfo interface.
 */
export function instanceOfGroupInfo(value: object): value is GroupInfo {
    return true;
}

export function GroupInfoFromJSON(json: any): GroupInfo {
    return GroupInfoFromJSONTyped(json, false);
}

export function GroupInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'options': json['options'] == null ? undefined : GroupOptionsInfoFromJSON(json['options']),
        'description': json['description'] == null ? undefined : json['description'],
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'createdOn': json['created_on'] == null ? undefined : json['created_on'],
        'moreGroups': json['_more_groups'] == null ? undefined : json['_more_groups'],
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(AccountInfoFromJSON)),
        'includes': json['includes'] == null ? undefined : ((json['includes'] as Array<any>).map(GroupInfoFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function GroupInfoToJSON(json: any): GroupInfo {
    return GroupInfoToJSONTyped(json, false);
}

export function GroupInfoToJSONTyped(value?: GroupInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'options': GroupOptionsInfoToJSON(value['options']),
        'description': value['description'],
        'group_id': value['groupId'],
        'owner': value['owner'],
        'owner_id': value['ownerId'],
        'created_on': value['createdOn'],
        '_more_groups': value['moreGroups'],
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(AccountInfoToJSON)),
        'includes': value['includes'] == null ? undefined : ((value['includes'] as Array<any>).map(GroupInfoToJSON)),
        'id': value['id'],
        'name': value['name'],
    };
}

