/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Type } from './Type';
import {
    TypeFromJSON,
    TypeFromJSONTyped,
    TypeToJSON,
    TypeToJSONTyped,
} from './Type';
import type { AccountInfo } from './AccountInfo';
import {
    AccountInfoFromJSON,
    AccountInfoFromJSONTyped,
    AccountInfoToJSON,
    AccountInfoToJSONTyped,
} from './AccountInfo';

/**
 * 
 * @export
 * @interface GroupAuditEventInfo
 */
export interface GroupAuditEventInfo {
    /**
     * The event type, can be: ADD_USER, REMOVE_USER, ADD_GROUP or REMOVE_GROUP. ADD_USER: A user was added as member to the group. REMOVE_USER: A user member was removed from the group. ADD_GROUP: A group was included as member in the group. REMOVE_GROUP: An included group was removed from the group.
     */
    type?: Type;
    /**
     * The user that did the add/remove as detailed AccountInfo entity.
     */
    user?: AccountInfo;
    /**
     * The timestamp of the event.
     */
    date?: string;
}



/**
 * Check if a given object implements the GroupAuditEventInfo interface.
 */
export function instanceOfGroupAuditEventInfo(value: object): value is GroupAuditEventInfo {
    return true;
}

export function GroupAuditEventInfoFromJSON(json: any): GroupAuditEventInfo {
    return GroupAuditEventInfoFromJSONTyped(json, false);
}

export function GroupAuditEventInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupAuditEventInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : TypeFromJSON(json['type']),
        'user': json['user'] == null ? undefined : AccountInfoFromJSON(json['user']),
        'date': json['date'] == null ? undefined : json['date'],
    };
}

export function GroupAuditEventInfoToJSON(json: any): GroupAuditEventInfo {
    return GroupAuditEventInfoToJSONTyped(json, false);
}

export function GroupAuditEventInfoToJSONTyped(value?: GroupAuditEventInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': TypeToJSON(value['type']),
        'user': AccountInfoToJSON(value['user']),
        'date': value['date'],
    };
}

