/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupBaseInfo
 */
export interface GroupBaseInfo {
    /**
     * The UUID of the group.
     */
    id?: string;
    /**
     * The name of the group.
     */
    name?: string;
}

/**
 * Check if a given object implements the GroupBaseInfo interface.
 */
export function instanceOfGroupBaseInfo(value: object): value is GroupBaseInfo {
    return true;
}

export function GroupBaseInfoFromJSON(json: any): GroupBaseInfo {
    return GroupBaseInfoFromJSONTyped(json, false);
}

export function GroupBaseInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupBaseInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function GroupBaseInfoToJSON(json: any): GroupBaseInfo {
    return GroupBaseInfoToJSONTyped(json, false);
}

export function GroupBaseInfoToJSONTyped(value?: GroupBaseInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

