/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HeadInput
 */
export interface HeadInput {
    /**
     * 
     */
    ref?: string;
}

/**
 * Check if a given object implements the HeadInput interface.
 */
export function instanceOfHeadInput(value: object): value is HeadInput {
    return true;
}

export function HeadInputFromJSON(json: any): HeadInput {
    return HeadInputFromJSONTyped(json, false);
}

export function HeadInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeadInput {
    if (json == null) {
        return json;
    }
    return {
        
        'ref': json['ref'] == null ? undefined : json['ref'],
    };
}

export function HeadInputToJSON(json: any): HeadInput {
    return HeadInputToJSONTyped(json, false);
}

export function HeadInputToJSONTyped(value?: HeadInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ref': value['ref'],
    };
}

