/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HttpPasswordInput
 */
export interface HttpPasswordInput {
    /**
     * The new HTTP password. Only Gerrit administrators may set the HTTP password directly. + If empty or not set and generate is false or not set, the HTTP password is deleted.
     */
    httpPassword?: string;
    /**
     * Whether a new HTTP password should be generated
     */
    generate?: boolean;
}

/**
 * Check if a given object implements the HttpPasswordInput interface.
 */
export function instanceOfHttpPasswordInput(value: object): value is HttpPasswordInput {
    return true;
}

export function HttpPasswordInputFromJSON(json: any): HttpPasswordInput {
    return HttpPasswordInputFromJSONTyped(json, false);
}

export function HttpPasswordInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpPasswordInput {
    if (json == null) {
        return json;
    }
    return {
        
        'httpPassword': json['http_password'] == null ? undefined : json['http_password'],
        'generate': json['generate'] == null ? undefined : json['generate'],
    };
}

export function HttpPasswordInputToJSON(json: any): HttpPasswordInput {
    return HttpPasswordInputToJSONTyped(json, false);
}

export function HttpPasswordInputToJSONTyped(value?: HttpPasswordInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'http_password': value['httpPassword'],
        'generate': value['generate'],
    };
}

