/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IncludedInInfo
 */
export interface IncludedInInfo {
    /**
     * The list of branches this change was merged into. Each branch is listed without the 'refs/head/' prefix.
     */
    branches?: Array<string>;
    /**
     * The list of tags this change was tagged with. Each tag is listed without the 'refs/tags/' prefix.
     */
    tags?: Array<string>;
    /**
     * A map that maps a name to a list of external systems that include this change, e.g. a list of servers on which this change is deployed.
     */
    external?: { [key: string]: Array<string>; };
}

/**
 * Check if a given object implements the IncludedInInfo interface.
 */
export function instanceOfIncludedInInfo(value: object): value is IncludedInInfo {
    return true;
}

export function IncludedInInfoFromJSON(json: any): IncludedInInfo {
    return IncludedInInfoFromJSONTyped(json, false);
}

export function IncludedInInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncludedInInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'branches': json['branches'] == null ? undefined : json['branches'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'external': json['external'] == null ? undefined : json['external'],
    };
}

export function IncludedInInfoToJSON(json: any): IncludedInInfo {
    return IncludedInInfoToJSONTyped(json, false);
}

export function IncludedInInfoToJSONTyped(value?: IncludedInInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branches': value['branches'],
        'tags': value['tags'],
        'external': value['external'],
    };
}

