/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndexProjectInput
 */
export interface IndexProjectInput {
    /**
     * 
     */
    indexChildren?: boolean;
    /**
     * 
     */
    async?: boolean;
}

/**
 * Check if a given object implements the IndexProjectInput interface.
 */
export function instanceOfIndexProjectInput(value: object): value is IndexProjectInput {
    return true;
}

export function IndexProjectInputFromJSON(json: any): IndexProjectInput {
    return IndexProjectInputFromJSONTyped(json, false);
}

export function IndexProjectInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexProjectInput {
    if (json == null) {
        return json;
    }
    return {
        
        'indexChildren': json['index_children'] == null ? undefined : json['index_children'],
        'async': json['async'] == null ? undefined : json['async'],
    };
}

export function IndexProjectInputToJSON(json: any): IndexProjectInput {
    return IndexProjectInputToJSONTyped(json, false);
}

export function IndexProjectInputToJSONTyped(value?: IndexProjectInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index_children': value['indexChildren'],
        'async': value['async'],
    };
}

