/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const InheritableBoolean = {
    True: 'TRUE',
    False: 'FALSE',
    Inherit: 'INHERIT',
} as const;
export type InheritableBoolean = typeof InheritableBoolean[keyof typeof InheritableBoolean];


export function instanceOfInheritableBoolean(value: any): boolean {
    for (const key in InheritableBoolean) {
        if (Object.prototype.hasOwnProperty.call(InheritableBoolean, key)) {
            if (InheritableBoolean[key as keyof typeof InheritableBoolean] === value) {
                return true;
            }
        }
    }
    return false;
}

export function InheritableBooleanFromJSON(json: any): InheritableBoolean {
    return InheritableBooleanFromJSONTyped(json, false);
}

export function InheritableBooleanFromJSONTyped(json: any, ignoreDiscriminator: boolean): InheritableBoolean {
    return json as InheritableBoolean;
}

export function InheritableBooleanToJSON(value?: InheritableBoolean | null): any {
    return value as any;
}

export function InheritableBooleanToJSONTyped(value: any, ignoreDiscriminator: boolean): InheritableBoolean {
    return value as InheritableBoolean;
}

