/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InputWithCommitMessage
 */
export interface InputWithCommitMessage {
    /**
     * 
     */
    commitMessage?: string;
}

/**
 * Check if a given object implements the InputWithCommitMessage interface.
 */
export function instanceOfInputWithCommitMessage(value: object): value is InputWithCommitMessage {
    return true;
}

export function InputWithCommitMessageFromJSON(json: any): InputWithCommitMessage {
    return InputWithCommitMessageFromJSONTyped(json, false);
}

export function InputWithCommitMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): InputWithCommitMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'commitMessage': json['commit_message'] == null ? undefined : json['commit_message'],
    };
}

export function InputWithCommitMessageToJSON(json: any): InputWithCommitMessage {
    return InputWithCommitMessageToJSONTyped(json, false);
}

export function InputWithCommitMessageToJSONTyped(value?: InputWithCommitMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commit_message': value['commitMessage'],
    };
}

