/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JvmSummaryInfo
 */
export interface JvmSummaryInfo {
    /**
     * 
     */
    vmVendor?: string;
    /**
     * 
     */
    vmName?: string;
    /**
     * 
     */
    vmVersion?: string;
    /**
     * 
     */
    osName?: string;
    /**
     * 
     */
    osVersion?: string;
    /**
     * 
     */
    osArch?: string;
    /**
     * 
     */
    user?: string;
    /**
     * 
     */
    host?: string;
    /**
     * 
     */
    currentWorkingDirectory?: string;
    /**
     * 
     */
    site?: string;
}

/**
 * Check if a given object implements the JvmSummaryInfo interface.
 */
export function instanceOfJvmSummaryInfo(value: object): value is JvmSummaryInfo {
    return true;
}

export function JvmSummaryInfoFromJSON(json: any): JvmSummaryInfo {
    return JvmSummaryInfoFromJSONTyped(json, false);
}

export function JvmSummaryInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JvmSummaryInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'vmVendor': json['vm_vendor'] == null ? undefined : json['vm_vendor'],
        'vmName': json['vm_name'] == null ? undefined : json['vm_name'],
        'vmVersion': json['vm_version'] == null ? undefined : json['vm_version'],
        'osName': json['os_name'] == null ? undefined : json['os_name'],
        'osVersion': json['os_version'] == null ? undefined : json['os_version'],
        'osArch': json['os_arch'] == null ? undefined : json['os_arch'],
        'user': json['user'] == null ? undefined : json['user'],
        'host': json['host'] == null ? undefined : json['host'],
        'currentWorkingDirectory': json['current_working_directory'] == null ? undefined : json['current_working_directory'],
        'site': json['site'] == null ? undefined : json['site'],
    };
}

export function JvmSummaryInfoToJSON(json: any): JvmSummaryInfo {
    return JvmSummaryInfoToJSONTyped(json, false);
}

export function JvmSummaryInfoToJSONTyped(value?: JvmSummaryInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vm_vendor': value['vmVendor'],
        'vm_name': value['vmName'],
        'vm_version': value['vmVersion'],
        'os_name': value['osName'],
        'os_version': value['osVersion'],
        'os_arch': value['osArch'],
        'user': value['user'],
        'host': value['host'],
        'current_working_directory': value['currentWorkingDirectory'],
        'site': value['site'],
    };
}

