/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LabelTypeInfo
 */
export interface LabelTypeInfo {
    /**
     * Map of the available values to their description.
     */
    values?: { [key: string]: string; };
    /**
     * The default value of this label.
     */
    defaultValue?: number;
}

/**
 * Check if a given object implements the LabelTypeInfo interface.
 */
export function instanceOfLabelTypeInfo(value: object): value is LabelTypeInfo {
    return true;
}

export function LabelTypeInfoFromJSON(json: any): LabelTypeInfo {
    return LabelTypeInfoFromJSONTyped(json, false);
}

export function LabelTypeInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelTypeInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'values': json['values'] == null ? undefined : json['values'],
        'defaultValue': json['default_value'] == null ? undefined : json['default_value'],
    };
}

export function LabelTypeInfoToJSON(json: any): LabelTypeInfo {
    return LabelTypeInfoToJSONTyped(json, false);
}

export function LabelTypeInfoToJSONTyped(value?: LabelTypeInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'values': value['values'],
        'default_value': value['defaultValue'],
    };
}

