/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LabelStatus = {
    Ok: 'OK',
    Reject: 'REJECT',
    Need: 'NEED',
    May: 'MAY',
    Impossible: 'IMPOSSIBLE',
} as const;
export type LabelStatus = typeof LabelStatus[keyof typeof LabelStatus];


export function instanceOfLabelStatus(value: any): boolean {
    for (const key in LabelStatus) {
        if (Object.prototype.hasOwnProperty.call(LabelStatus, key)) {
            if (LabelStatus[key as keyof typeof LabelStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LabelStatusFromJSON(json: any): LabelStatus {
    return LabelStatusFromJSONTyped(json, false);
}

export function LabelStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelStatus {
    return json as LabelStatus;
}

export function LabelStatusToJSON(value?: LabelStatus | null): any {
    return value as any;
}

export function LabelStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): LabelStatus {
    return value as LabelStatus;
}

