/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LabelDefinitionInput
 */
export interface LabelDefinitionInput {
    /**
     * The new name of the label.+ For label creation the name is required if this LabelDefinitionInput entity is contained in a BatchLabelInput entity.
     */
    name?: string;
    /**
     * The new description for the label.
     */
    description?: string;
    /**
     * The new function of the label (can be NoOp/NoBlock and PatchSetLock). By default NoOp when creating new labels.
     */
    _function?: string;
    /**
     * The new values of the label as a map of label value to value description. The label values are formatted strings, e.g. "+1" instead of "1", " 0" instead of "0".
     */
    values?: { [key: string]: string; };
    /**
     * The new default value of the label (as integer).
     */
    defaultValue?: number;
    /**
     * The new branches for which the label applies as a list of branches. A branch can be a ref, a ref pattern or a regular expression. If not set, the label applies for all branches.
     */
    branches?: Array<string>;
    /**
     * Whether this label can be overridden by child projects.
     */
    canOverride?: boolean;
    /**
     * See copyCondition.
     */
    copyCondition?: string;
    /**
     * If true, clears the value stored in copy_condition.
     */
    unsetCopyCondition?: boolean;
    /**
     * Whether allowPostSubmit is set on the label.
     */
    allowPostSubmit?: boolean;
    /**
     * Whether ignoreSelfApproval is set on the label.
     */
    ignoreSelfApproval?: boolean;
    /**
     * Message that should be used to commit the change of the label in the project.config file to the refs/meta/config branch.+ Must not be set if this LabelDefinitionInput entity is contained in a BatchLabelInput entity.
     */
    commitMessage?: string;
}

/**
 * Check if a given object implements the LabelDefinitionInput interface.
 */
export function instanceOfLabelDefinitionInput(value: object): value is LabelDefinitionInput {
    return true;
}

export function LabelDefinitionInputFromJSON(json: any): LabelDefinitionInput {
    return LabelDefinitionInputFromJSONTyped(json, false);
}

export function LabelDefinitionInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelDefinitionInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        '_function': json['function'] == null ? undefined : json['function'],
        'values': json['values'] == null ? undefined : json['values'],
        'defaultValue': json['default_value'] == null ? undefined : json['default_value'],
        'branches': json['branches'] == null ? undefined : json['branches'],
        'canOverride': json['can_override'] == null ? undefined : json['can_override'],
        'copyCondition': json['copy_condition'] == null ? undefined : json['copy_condition'],
        'unsetCopyCondition': json['unset_copy_condition'] == null ? undefined : json['unset_copy_condition'],
        'allowPostSubmit': json['allow_post_submit'] == null ? undefined : json['allow_post_submit'],
        'ignoreSelfApproval': json['ignore_self_approval'] == null ? undefined : json['ignore_self_approval'],
        'commitMessage': json['commit_message'] == null ? undefined : json['commit_message'],
    };
}

export function LabelDefinitionInputToJSON(json: any): LabelDefinitionInput {
    return LabelDefinitionInputToJSONTyped(json, false);
}

export function LabelDefinitionInputToJSONTyped(value?: LabelDefinitionInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'function': value['_function'],
        'values': value['values'],
        'default_value': value['defaultValue'],
        'branches': value['branches'],
        'can_override': value['canOverride'],
        'copy_condition': value['copyCondition'],
        'unset_copy_condition': value['unsetCopyCondition'],
        'allow_post_submit': value['allowPostSubmit'],
        'ignore_self_approval': value['ignoreSelfApproval'],
        'commit_message': value['commitMessage'],
    };
}

