/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubmitType } from './SubmitType';
import {
    SubmitTypeFromJSON,
    SubmitTypeFromJSONTyped,
    SubmitTypeToJSON,
    SubmitTypeToJSONTyped,
} from './SubmitType';

/**
 * 
 * @export
 * @interface MergeableInfo
 */
export interface MergeableInfo {
    /**
     * 
     */
    submitType?: SubmitType;
    /**
     * 
     */
    strategy?: string;
    /**
     * 
     */
    mergeable?: boolean;
    /**
     * 
     */
    commitMerged?: boolean;
    /**
     * 
     */
    contentMerged?: boolean;
    /**
     * 
     */
    conflicts?: Array<string>;
    /**
     * 
     */
    mergeableInto?: Array<string>;
}



/**
 * Check if a given object implements the MergeableInfo interface.
 */
export function instanceOfMergeableInfo(value: object): value is MergeableInfo {
    return true;
}

export function MergeableInfoFromJSON(json: any): MergeableInfo {
    return MergeableInfoFromJSONTyped(json, false);
}

export function MergeableInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MergeableInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'submitType': json['submit_type'] == null ? undefined : SubmitTypeFromJSON(json['submit_type']),
        'strategy': json['strategy'] == null ? undefined : json['strategy'],
        'mergeable': json['mergeable'] == null ? undefined : json['mergeable'],
        'commitMerged': json['commit_merged'] == null ? undefined : json['commit_merged'],
        'contentMerged': json['content_merged'] == null ? undefined : json['content_merged'],
        'conflicts': json['conflicts'] == null ? undefined : json['conflicts'],
        'mergeableInto': json['mergeable_into'] == null ? undefined : json['mergeable_into'],
    };
}

export function MergeableInfoToJSON(json: any): MergeableInfo {
    return MergeableInfoToJSONTyped(json, false);
}

export function MergeableInfoToJSONTyped(value?: MergeableInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'submit_type': SubmitTypeToJSON(value['submitType']),
        'strategy': value['strategy'],
        'mergeable': value['mergeable'],
        'commit_merged': value['commitMerged'],
        'content_merged': value['contentMerged'],
        'conflicts': value['conflicts'],
        'mergeable_into': value['mergeableInto'],
    };
}

