/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MergeInput
 */
export interface MergeInput {
    /**
     * 
     */
    source?: string;
    /**
     * 
     */
    sourceBranch?: string;
    /**
     * 
     */
    strategy?: string;
    /**
     * 
     */
    allowConflicts?: boolean;
}

/**
 * Check if a given object implements the MergeInput interface.
 */
export function instanceOfMergeInput(value: object): value is MergeInput {
    return true;
}

export function MergeInputFromJSON(json: any): MergeInput {
    return MergeInputFromJSONTyped(json, false);
}

export function MergeInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): MergeInput {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'] == null ? undefined : json['source'],
        'sourceBranch': json['source_branch'] == null ? undefined : json['source_branch'],
        'strategy': json['strategy'] == null ? undefined : json['strategy'],
        'allowConflicts': json['allow_conflicts'] == null ? undefined : json['allow_conflicts'],
    };
}

export function MergeInputToJSON(json: any): MergeInput {
    return MergeInputToJSONTyped(json, false);
}

export function MergeInputToJSONTyped(value?: MergeInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'source_branch': value['sourceBranch'],
        'strategy': value['strategy'],
        'allow_conflicts': value['allowConflicts'],
    };
}

