/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FieldJson } from './FieldJson';
import {
    FieldJsonFromJSON,
    FieldJsonFromJSONTyped,
    FieldJsonToJSON,
    FieldJsonToJSONTyped,
} from './FieldJson';

/**
 * 
 * @export
 * @interface MetricJson
 */
export interface MetricJson {
    /**
     * The description of the metric.
     */
    description?: string;
    /**
     * The unit of measurement of the recorded values.
     */
    unit?: string;
    /**
     * Whether the metric reports a single constant value.
     */
    constant?: boolean;
    /**
     * Whether the metric reports a rate.
     */
    rate?: boolean;
    /**
     * Whether the metric is a gauge that reports an instantaneous value.
     */
    gauge?: boolean;
    /**
     * Whether the metric accumulates over time.
     */
    cumulative?: boolean;
    /**
     * The number of recorded events.
     */
    count?: number;
    /**
     * The current value, for constant metrics and gauges.
     */
    value?: object;
    /**
     * The one-minute moving average rate.
     */
    rate1m?: number;
    /**
     * The five-minute moving average rate.
     */
    rate5m?: number;
    /**
     * The fifteen-minute moving average rate.
     */
    rate15m?: number;
    /**
     * The mean rate since the metric was registered.
     */
    rateMean?: number;
    /**
     * The median (50th percentile) of the recorded values.
     */
    p50?: number;
    /**
     * The 75th percentile of the recorded values.
     */
    p75?: number;
    /**
     * The 95th percentile of the recorded values.
     */
    p95?: number;
    /**
     * The 98th percentile of the recorded values.
     */
    p98?: number;
    /**
     * The 99th percentile of the recorded values.
     */
    p99?: number;
    /**
     * The 99.9th percentile of the recorded values.
     */
    p999?: number;
    /**
     * The minimum recorded value.
     */
    min?: number;
    /**
     * The average of the recorded values.
     */
    avg?: number;
    /**
     * The maximum recorded value.
     */
    max?: number;
    /**
     * The sum of the recorded values.
     */
    sum?: number;
    /**
     * The standard deviation of the recorded values.
     */
    stdDev?: number;
    /**
     * The fields of the metric as a list of FieldJson entities.
     */
    fields?: Array<FieldJson>;
    /**
     * The per-field-value breakdown of the metric, as a map of field values to the recorded value for that combination.
     */
    buckets?: { [key: string]: object; };
}

/**
 * Check if a given object implements the MetricJson interface.
 */
export function instanceOfMetricJson(value: object): value is MetricJson {
    return true;
}

export function MetricJsonFromJSON(json: any): MetricJson {
    return MetricJsonFromJSONTyped(json, false);
}

export function MetricJsonFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricJson {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'constant': json['constant'] == null ? undefined : json['constant'],
        'rate': json['rate'] == null ? undefined : json['rate'],
        'gauge': json['gauge'] == null ? undefined : json['gauge'],
        'cumulative': json['cumulative'] == null ? undefined : json['cumulative'],
        'count': json['count'] == null ? undefined : json['count'],
        'value': json['value'] == null ? undefined : json['value'],
        'rate1m': json['rate_1m'] == null ? undefined : json['rate_1m'],
        'rate5m': json['rate_5m'] == null ? undefined : json['rate_5m'],
        'rate15m': json['rate_15m'] == null ? undefined : json['rate_15m'],
        'rateMean': json['rate_mean'] == null ? undefined : json['rate_mean'],
        'p50': json['p50'] == null ? undefined : json['p50'],
        'p75': json['p75'] == null ? undefined : json['p75'],
        'p95': json['p95'] == null ? undefined : json['p95'],
        'p98': json['p98'] == null ? undefined : json['p98'],
        'p99': json['p99'] == null ? undefined : json['p99'],
        'p999': json['p99_9'] == null ? undefined : json['p99_9'],
        'min': json['min'] == null ? undefined : json['min'],
        'avg': json['avg'] == null ? undefined : json['avg'],
        'max': json['max'] == null ? undefined : json['max'],
        'sum': json['sum'] == null ? undefined : json['sum'],
        'stdDev': json['std_dev'] == null ? undefined : json['std_dev'],
        'fields': json['fields'] == null ? undefined : ((json['fields'] as Array<any>).map(FieldJsonFromJSON)),
        'buckets': json['buckets'] == null ? undefined : json['buckets'],
    };
}

export function MetricJsonToJSON(json: any): MetricJson {
    return MetricJsonToJSONTyped(json, false);
}

export function MetricJsonToJSONTyped(value?: MetricJson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'unit': value['unit'],
        'constant': value['constant'],
        'rate': value['rate'],
        'gauge': value['gauge'],
        'cumulative': value['cumulative'],
        'count': value['count'],
        'value': value['value'],
        'rate_1m': value['rate1m'],
        'rate_5m': value['rate5m'],
        'rate_15m': value['rate15m'],
        'rate_mean': value['rateMean'],
        'p50': value['p50'],
        'p75': value['p75'],
        'p95': value['p95'],
        'p98': value['p98'],
        'p99': value['p99'],
        'p99_9': value['p999'],
        'min': value['min'],
        'avg': value['avg'],
        'max': value['max'],
        'sum': value['sum'],
        'std_dev': value['stdDev'],
        'fields': value['fields'] == null ? undefined : ((value['fields'] as Array<any>).map(FieldJsonToJSON)),
        'buckets': value['buckets'],
    };
}

