/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MigrateLabelFunctionsToSubmitRequirementStatus = {
    Migrated: 'MIGRATED',
    HasProlog: 'HAS_PROLOG',
    PreviouslyMigrated: 'PREVIOUSLY_MIGRATED',
    NoChange: 'NO_CHANGE',
} as const;
export type MigrateLabelFunctionsToSubmitRequirementStatus = typeof MigrateLabelFunctionsToSubmitRequirementStatus[keyof typeof MigrateLabelFunctionsToSubmitRequirementStatus];


export function instanceOfMigrateLabelFunctionsToSubmitRequirementStatus(value: any): boolean {
    for (const key in MigrateLabelFunctionsToSubmitRequirementStatus) {
        if (Object.prototype.hasOwnProperty.call(MigrateLabelFunctionsToSubmitRequirementStatus, key)) {
            if (MigrateLabelFunctionsToSubmitRequirementStatus[key as keyof typeof MigrateLabelFunctionsToSubmitRequirementStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MigrateLabelFunctionsToSubmitRequirementStatusFromJSON(json: any): MigrateLabelFunctionsToSubmitRequirementStatus {
    return MigrateLabelFunctionsToSubmitRequirementStatusFromJSONTyped(json, false);
}

export function MigrateLabelFunctionsToSubmitRequirementStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MigrateLabelFunctionsToSubmitRequirementStatus {
    return json as MigrateLabelFunctionsToSubmitRequirementStatus;
}

export function MigrateLabelFunctionsToSubmitRequirementStatusToJSON(value?: MigrateLabelFunctionsToSubmitRequirementStatus | null): any {
    return value as any;
}

export function MigrateLabelFunctionsToSubmitRequirementStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): MigrateLabelFunctionsToSubmitRequirementStatus {
    return value as MigrateLabelFunctionsToSubmitRequirementStatus;
}

