/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MoveInput
 */
export interface MoveInput {
    /**
     * 
     */
    message?: string;
    /**
     * 
     */
    destinationBranch?: string;
    /**
     * 
     */
    keepAllVotes?: boolean;
}

/**
 * Check if a given object implements the MoveInput interface.
 */
export function instanceOfMoveInput(value: object): value is MoveInput {
    return true;
}

export function MoveInputFromJSON(json: any): MoveInput {
    return MoveInputFromJSONTyped(json, false);
}

export function MoveInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoveInput {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'destinationBranch': json['destination_branch'] == null ? undefined : json['destination_branch'],
        'keepAllVotes': json['keep_all_votes'] == null ? undefined : json['keep_all_votes'],
    };
}

export function MoveInputToJSON(json: any): MoveInput {
    return MoveInputToJSONTyped(json, false);
}

export function MoveInputToJSONTyped(value?: MoveInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'destination_branch': value['destinationBranch'],
        'keep_all_votes': value['keepAllVotes'],
    };
}

