/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NameInput
 */
export interface NameInput {
    /**
     * The new full name of the account. + If not set or if set to an empty string, the account name is deleted.
     */
    name?: string;
}

/**
 * Check if a given object implements the NameInput interface.
 */
export function instanceOfNameInput(value: object): value is NameInput {
    return true;
}

export function NameInputFromJSON(json: any): NameInput {
    return NameInputFromJSONTyped(json, false);
}

export function NameInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): NameInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function NameInputToJSON(json: any): NameInput {
    return NameInputToJSONTyped(json, false);
}

export function NameInputToJSONTyped(value?: NameInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

