/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NoMergeBaseReason = {
    HistoricDataWithoutBase: 'HISTORIC_DATA_WITHOUT_BASE',
    NoCommonAncestor: 'NO_COMMON_ANCESTOR',
    ComputedBase: 'COMPUTED_BASE',
    OneSidedMergeStrategy: 'ONE_SIDED_MERGE_STRATEGY',
    NoMergePerformed: 'NO_MERGE_PERFORMED',
} as const;
export type NoMergeBaseReason = typeof NoMergeBaseReason[keyof typeof NoMergeBaseReason];


export function instanceOfNoMergeBaseReason(value: any): boolean {
    for (const key in NoMergeBaseReason) {
        if (Object.prototype.hasOwnProperty.call(NoMergeBaseReason, key)) {
            if (NoMergeBaseReason[key as keyof typeof NoMergeBaseReason] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NoMergeBaseReasonFromJSON(json: any): NoMergeBaseReason {
    return NoMergeBaseReasonFromJSONTyped(json, false);
}

export function NoMergeBaseReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoMergeBaseReason {
    return json as NoMergeBaseReason;
}

export function NoMergeBaseReasonToJSON(value?: NoMergeBaseReason | null): any {
    return value as any;
}

export function NoMergeBaseReasonToJSONTyped(value: any, ignoreDiscriminator: boolean): NoMergeBaseReason {
    return value as NoMergeBaseReason;
}

