/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParentInput
 */
export interface ParentInput {
    /**
     * 
     */
    parent?: string;
    /**
     * 
     */
    commitMessage?: string;
}

/**
 * Check if a given object implements the ParentInput interface.
 */
export function instanceOfParentInput(value: object): value is ParentInput {
    return true;
}

export function ParentInputFromJSON(json: any): ParentInput {
    return ParentInputFromJSONTyped(json, false);
}

export function ParentInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParentInput {
    if (json == null) {
        return json;
    }
    return {
        
        'parent': json['parent'] == null ? undefined : json['parent'],
        'commitMessage': json['commit_message'] == null ? undefined : json['commit_message'],
    };
}

export function ParentInputToJSON(json: any): ParentInput {
    return ParentInputToJSONTyped(json, false);
}

export function ParentInputToJSONTyped(value?: ParentInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parent': value['parent'],
        'commit_message': value['commitMessage'],
    };
}

