/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParentInfo
 */
export interface ParentInfo {
    /**
     * 
     */
    branchName?: string;
    /**
     * 
     */
    commitId?: string;
    /**
     * 
     */
    isMergedInTargetBranch?: boolean;
    /**
     * 
     */
    changeId?: string;
    /**
     * 
     */
    changeNumber?: number;
    /**
     * 
     */
    patchSetNumber?: number;
    /**
     * 
     */
    changeStatus?: string;
}

/**
 * Check if a given object implements the ParentInfo interface.
 */
export function instanceOfParentInfo(value: object): value is ParentInfo {
    return true;
}

export function ParentInfoFromJSON(json: any): ParentInfo {
    return ParentInfoFromJSONTyped(json, false);
}

export function ParentInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParentInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'branchName': json['branch_name'] == null ? undefined : json['branch_name'],
        'commitId': json['commit_id'] == null ? undefined : json['commit_id'],
        'isMergedInTargetBranch': json['is_merged_in_target_branch'] == null ? undefined : json['is_merged_in_target_branch'],
        'changeId': json['change_id'] == null ? undefined : json['change_id'],
        'changeNumber': json['change_number'] == null ? undefined : json['change_number'],
        'patchSetNumber': json['patch_set_number'] == null ? undefined : json['patch_set_number'],
        'changeStatus': json['change_status'] == null ? undefined : json['change_status'],
    };
}

export function ParentInfoToJSON(json: any): ParentInfo {
    return ParentInfoToJSONTyped(json, false);
}

export function ParentInfoToJSONTyped(value?: ParentInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branch_name': value['branchName'],
        'commit_id': value['commitId'],
        'is_merged_in_target_branch': value['isMergedInTargetBranch'],
        'change_id': value['changeId'],
        'change_number': value['changeNumber'],
        'patch_set_number': value['patchSetNumber'],
        'change_status': value['changeStatus'],
    };
}

