/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Action } from './Action';
import {
    ActionFromJSON,
    ActionFromJSONTyped,
    ActionToJSON,
    ActionToJSONTyped,
} from './Action';

/**
 * 
 * @export
 * @interface PermissionRuleInfo
 */
export interface PermissionRuleInfo {
    /**
     * 
     */
    action?: Action;
    /**
     * 
     */
    force?: boolean;
    /**
     * 
     */
    min?: number;
    /**
     * 
     */
    max?: number;
}



/**
 * Check if a given object implements the PermissionRuleInfo interface.
 */
export function instanceOfPermissionRuleInfo(value: object): value is PermissionRuleInfo {
    return true;
}

export function PermissionRuleInfoFromJSON(json: any): PermissionRuleInfo {
    return PermissionRuleInfoFromJSONTyped(json, false);
}

export function PermissionRuleInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionRuleInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'] == null ? undefined : ActionFromJSON(json['action']),
        'force': json['force'] == null ? undefined : json['force'],
        'min': json['min'] == null ? undefined : json['min'],
        'max': json['max'] == null ? undefined : json['max'],
    };
}

export function PermissionRuleInfoToJSON(json: any): PermissionRuleInfo {
    return PermissionRuleInfoToJSONTyped(json, false);
}

export function PermissionRuleInfoToJSONTyped(value?: PermissionRuleInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': ActionToJSON(value['action']),
        'force': value['force'],
        'min': value['min'],
        'max': value['max'],
    };
}

