/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PluginDefinedInfo
 */
export interface PluginDefinedInfo {
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    message?: string;
}

/**
 * Check if a given object implements the PluginDefinedInfo interface.
 */
export function instanceOfPluginDefinedInfo(value: object): value is PluginDefinedInfo {
    return true;
}

export function PluginDefinedInfoFromJSON(json: any): PluginDefinedInfo {
    return PluginDefinedInfoFromJSONTyped(json, false);
}

export function PluginDefinedInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginDefinedInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PluginDefinedInfoToJSON(json: any): PluginDefinedInfo {
    return PluginDefinedInfoToJSONTyped(json, false);
}

export function PluginDefinedInfoToJSONTyped(value?: PluginDefinedInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'message': value['message'],
    };
}

