/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PluginInfo
 */
export interface PluginInfo {
    /**
     * The ID of the plugin.
     */
    id?: string;
    /**
     * The version of the plugin.
     */
    version?: string;
    /**
     * The version of the Gerrit Api used by the plugin.
     */
    apiVersion?: string;
    /**
     * URL of the plugin's default page.
     */
    indexUrl?: string;
    /**
     * The plugin's filename.
     */
    filename?: string;
    /**
     * Whether the plugin is disabled.
     */
    disabled?: boolean;
}

/**
 * Check if a given object implements the PluginInfo interface.
 */
export function instanceOfPluginInfo(value: object): value is PluginInfo {
    return true;
}

export function PluginInfoFromJSON(json: any): PluginInfo {
    return PluginInfoFromJSONTyped(json, false);
}

export function PluginInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'version': json['version'] == null ? undefined : json['version'],
        'apiVersion': json['api_version'] == null ? undefined : json['api_version'],
        'indexUrl': json['index_url'] == null ? undefined : json['index_url'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'disabled': json['disabled'] == null ? undefined : json['disabled'],
    };
}

export function PluginInfoToJSON(json: any): PluginInfo {
    return PluginInfoToJSONTyped(json, false);
}

export function PluginInfoToJSONTyped(value?: PluginInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'version': value['version'],
        'api_version': value['apiVersion'],
        'index_url': value['indexUrl'],
        'filename': value['filename'],
        'disabled': value['disabled'],
    };
}

