/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Operation } from './Operation';
import {
    OperationFromJSON,
    OperationFromJSONTyped,
    OperationToJSON,
    OperationToJSONTyped,
} from './Operation';

/**
 * 
 * @export
 * @interface PostCachesInput
 */
export interface PostCachesInput {
    /**
     * The cache operation that should be executed: FLUSH_ALL: Flushes all caches, except the web_sessions cache. FLUSH: Flushes the specified caches.
     */
    operation?: Operation;
    /**
     * A list of cache names. This list defines the caches on which the specified operation should be executed. Whether this list must be specified depends on the operation being executed.
     */
    caches?: Array<string>;
}



/**
 * Check if a given object implements the PostCachesInput interface.
 */
export function instanceOfPostCachesInput(value: object): value is PostCachesInput {
    return true;
}

export function PostCachesInputFromJSON(json: any): PostCachesInput {
    return PostCachesInputFromJSONTyped(json, false);
}

export function PostCachesInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCachesInput {
    if (json == null) {
        return json;
    }
    return {
        
        'operation': json['operation'] == null ? undefined : OperationFromJSON(json['operation']),
        'caches': json['caches'] == null ? undefined : json['caches'],
    };
}

export function PostCachesInputToJSON(json: any): PostCachesInput {
    return PostCachesInputToJSONTyped(json, false);
}

export function PostCachesInputToJSONTyped(value?: PostCachesInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operation': OperationToJSON(value['operation']),
        'caches': value['caches'],
    };
}

