/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProblemInfoStatus = {
    Fixed: 'FIXED',
    FixFailed: 'FIX_FAILED',
} as const;
export type ProblemInfoStatus = typeof ProblemInfoStatus[keyof typeof ProblemInfoStatus];


export function instanceOfProblemInfoStatus(value: any): boolean {
    for (const key in ProblemInfoStatus) {
        if (Object.prototype.hasOwnProperty.call(ProblemInfoStatus, key)) {
            if (ProblemInfoStatus[key as keyof typeof ProblemInfoStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProblemInfoStatusFromJSON(json: any): ProblemInfoStatus {
    return ProblemInfoStatusFromJSONTyped(json, false);
}

export function ProblemInfoStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemInfoStatus {
    return json as ProblemInfoStatus;
}

export function ProblemInfoStatusToJSON(value?: ProblemInfoStatus | null): any {
    return value as any;
}

export function ProblemInfoStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ProblemInfoStatus {
    return value as ProblemInfoStatus;
}

