/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProjectState = {
    Active: 'ACTIVE',
    ReadOnly: 'READ_ONLY',
    Hidden: 'HIDDEN',
} as const;
export type ProjectState = typeof ProjectState[keyof typeof ProjectState];


export function instanceOfProjectState(value: any): boolean {
    for (const key in ProjectState) {
        if (Object.prototype.hasOwnProperty.call(ProjectState, key)) {
            if (ProjectState[key as keyof typeof ProjectState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProjectStateFromJSON(json: any): ProjectState {
    return ProjectStateFromJSONTyped(json, false);
}

export function ProjectStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectState {
    return json as ProjectState;
}

export function ProjectStateToJSON(value?: ProjectState | null): any {
    return value as any;
}

export function ProjectStateToJSONTyped(value: any, ignoreDiscriminator: boolean): ProjectState {
    return value as ProjectState;
}

