/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessSectionInfo } from './AccessSectionInfo';
import {
    AccessSectionInfoFromJSON,
    AccessSectionInfoFromJSONTyped,
    AccessSectionInfoToJSON,
    AccessSectionInfoToJSONTyped,
} from './AccessSectionInfo';

/**
 * 
 * @export
 * @interface ProjectAccessInput
 */
export interface ProjectAccessInput {
    /**
     * 
     */
    remove?: { [key: string]: AccessSectionInfo; };
    /**
     * 
     */
    add?: { [key: string]: AccessSectionInfo; };
    /**
     * 
     */
    parent?: string;
    /**
     * 
     */
    message?: string;
}

/**
 * Check if a given object implements the ProjectAccessInput interface.
 */
export function instanceOfProjectAccessInput(value: object): value is ProjectAccessInput {
    return true;
}

export function ProjectAccessInputFromJSON(json: any): ProjectAccessInput {
    return ProjectAccessInputFromJSONTyped(json, false);
}

export function ProjectAccessInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectAccessInput {
    if (json == null) {
        return json;
    }
    return {
        
        'remove': json['remove'] == null ? undefined : (mapValues(json['remove'], AccessSectionInfoFromJSON)),
        'add': json['add'] == null ? undefined : (mapValues(json['add'], AccessSectionInfoFromJSON)),
        'parent': json['parent'] == null ? undefined : json['parent'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ProjectAccessInputToJSON(json: any): ProjectAccessInput {
    return ProjectAccessInputToJSONTyped(json, false);
}

export function ProjectAccessInputToJSONTyped(value?: ProjectAccessInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'remove': value['remove'] == null ? undefined : (mapValues(value['remove'], AccessSectionInfoToJSON)),
        'add': value['add'] == null ? undefined : (mapValues(value['add'], AccessSectionInfoToJSON)),
        'parent': value['parent'],
        'message': value['message'],
    };
}

