/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProjectConfigEntryType = {
    String: 'STRING',
    Int: 'INT',
    Long: 'LONG',
    Boolean: 'BOOLEAN',
    List: 'LIST',
    Array: 'ARRAY',
} as const;
export type ProjectConfigEntryType = typeof ProjectConfigEntryType[keyof typeof ProjectConfigEntryType];


export function instanceOfProjectConfigEntryType(value: any): boolean {
    for (const key in ProjectConfigEntryType) {
        if (Object.prototype.hasOwnProperty.call(ProjectConfigEntryType, key)) {
            if (ProjectConfigEntryType[key as keyof typeof ProjectConfigEntryType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProjectConfigEntryTypeFromJSON(json: any): ProjectConfigEntryType {
    return ProjectConfigEntryTypeFromJSONTyped(json, false);
}

export function ProjectConfigEntryTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectConfigEntryType {
    return json as ProjectConfigEntryType;
}

export function ProjectConfigEntryTypeToJSON(value?: ProjectConfigEntryType | null): any {
    return value as any;
}

export function ProjectConfigEntryTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ProjectConfigEntryType {
    return value as ProjectConfigEntryType;
}

