/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebLinkInfo } from './WebLinkInfo';
import {
    WebLinkInfoFromJSON,
    WebLinkInfoFromJSONTyped,
    WebLinkInfoToJSON,
    WebLinkInfoToJSONTyped,
} from './WebLinkInfo';
import type { ProjectState } from './ProjectState';
import {
    ProjectStateFromJSON,
    ProjectStateFromJSONTyped,
    ProjectStateToJSON,
    ProjectStateToJSONTyped,
} from './ProjectState';
import type { LabelTypeInfo } from './LabelTypeInfo';
import {
    LabelTypeInfoFromJSON,
    LabelTypeInfoFromJSONTyped,
    LabelTypeInfoToJSON,
    LabelTypeInfoToJSONTyped,
} from './LabelTypeInfo';

/**
 * 
 * @export
 * @interface ProjectInfo
 */
export interface ProjectInfo {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    parent?: string;
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    state?: ProjectState;
    /**
     * 
     */
    branches?: { [key: string]: string; };
    /**
     * 
     */
    webLinks?: Array<WebLinkInfo>;
    /**
     * 
     */
    labels?: { [key: string]: LabelTypeInfo; };
    /**
     * 
     */
    moreProjects?: boolean;
}



/**
 * Check if a given object implements the ProjectInfo interface.
 */
export function instanceOfProjectInfo(value: object): value is ProjectInfo {
    return true;
}

export function ProjectInfoFromJSON(json: any): ProjectInfo {
    return ProjectInfoFromJSONTyped(json, false);
}

export function ProjectInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'description': json['description'] == null ? undefined : json['description'],
        'state': json['state'] == null ? undefined : ProjectStateFromJSON(json['state']),
        'branches': json['branches'] == null ? undefined : json['branches'],
        'webLinks': json['web_links'] == null ? undefined : ((json['web_links'] as Array<any>).map(WebLinkInfoFromJSON)),
        'labels': json['labels'] == null ? undefined : (mapValues(json['labels'], LabelTypeInfoFromJSON)),
        'moreProjects': json['_more_projects'] == null ? undefined : json['_more_projects'],
    };
}

export function ProjectInfoToJSON(json: any): ProjectInfo {
    return ProjectInfoToJSONTyped(json, false);
}

export function ProjectInfoToJSONTyped(value?: ProjectInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'parent': value['parent'],
        'description': value['description'],
        'state': ProjectStateToJSON(value['state']),
        'branches': value['branches'],
        'web_links': value['webLinks'] == null ? undefined : ((value['webLinks'] as Array<any>).map(WebLinkInfoToJSON)),
        'labels': value['labels'] == null ? undefined : (mapValues(value['labels'], LabelTypeInfoToJSON)),
        '_more_projects': value['moreProjects'],
    };
}

