/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectWatchInfo
 */
export interface ProjectWatchInfo {
    /**
     * The name of the project.
     */
    project?: string;
    /**
     * A filter string to be applied to the project.
     */
    filter?: string;
    /**
     * An error message when project is for example hidden or deleted.
     */
    problem?: string;
    /**
     * Notify on new changes.
     */
    notifyNewChanges?: boolean;
    /**
     * Notify on new patch sets.
     */
    notifyNewPatchSets?: boolean;
    /**
     * Notify on comments.
     */
    notifyAllComments?: boolean;
    /**
     * Notify on submitted changes.
     */
    notifySubmittedChanges?: boolean;
    /**
     * Notify on abandoned changes.
     */
    notifyAbandonedChanges?: boolean;
}

/**
 * Check if a given object implements the ProjectWatchInfo interface.
 */
export function instanceOfProjectWatchInfo(value: object): value is ProjectWatchInfo {
    return true;
}

export function ProjectWatchInfoFromJSON(json: any): ProjectWatchInfo {
    return ProjectWatchInfoFromJSONTyped(json, false);
}

export function ProjectWatchInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectWatchInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'project': json['project'] == null ? undefined : json['project'],
        'filter': json['filter'] == null ? undefined : json['filter'],
        'problem': json['problem'] == null ? undefined : json['problem'],
        'notifyNewChanges': json['notify_new_changes'] == null ? undefined : json['notify_new_changes'],
        'notifyNewPatchSets': json['notify_new_patch_sets'] == null ? undefined : json['notify_new_patch_sets'],
        'notifyAllComments': json['notify_all_comments'] == null ? undefined : json['notify_all_comments'],
        'notifySubmittedChanges': json['notify_submitted_changes'] == null ? undefined : json['notify_submitted_changes'],
        'notifyAbandonedChanges': json['notify_abandoned_changes'] == null ? undefined : json['notify_abandoned_changes'],
    };
}

export function ProjectWatchInfoToJSON(json: any): ProjectWatchInfo {
    return ProjectWatchInfoToJSONTyped(json, false);
}

export function ProjectWatchInfoToJSONTyped(value?: ProjectWatchInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project': value['project'],
        'filter': value['filter'],
        'problem': value['problem'],
        'notify_new_changes': value['notifyNewChanges'],
        'notify_new_patch_sets': value['notifyNewPatchSets'],
        'notify_all_comments': value['notifyAllComments'],
        'notify_submitted_changes': value['notifySubmittedChanges'],
        'notify_abandoned_changes': value['notifyAbandonedChanges'],
    };
}

