/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectsDescriptionInput
 */
export interface ProjectsDescriptionInput {
    /**
     * 
     */
    commitMessage?: string;
}

/**
 * Check if a given object implements the ProjectsDescriptionInput interface.
 */
export function instanceOfProjectsDescriptionInput(value: object): value is ProjectsDescriptionInput {
    return true;
}

export function ProjectsDescriptionInputFromJSON(json: any): ProjectsDescriptionInput {
    return ProjectsDescriptionInputFromJSONTyped(json, false);
}

export function ProjectsDescriptionInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectsDescriptionInput {
    if (json == null) {
        return json;
    }
    return {
        
        'commitMessage': json['commit_message'] == null ? undefined : json['commit_message'],
    };
}

export function ProjectsDescriptionInputToJSON(json: any): ProjectsDescriptionInput {
    return ProjectsDescriptionInputToJSONTyped(json, false);
}

export function ProjectsDescriptionInputToJSONTyped(value?: ProjectsDescriptionInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commit_message': value['commitMessage'],
    };
}

