/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotifyInfo } from './NotifyInfo';
import {
    NotifyInfoFromJSON,
    NotifyInfoFromJSONTyped,
    NotifyInfoToJSON,
    NotifyInfoToJSONTyped,
} from './NotifyInfo';
import type { NotifyHandling } from './NotifyHandling';
import {
    NotifyHandlingFromJSON,
    NotifyHandlingFromJSONTyped,
    NotifyHandlingToJSON,
    NotifyHandlingToJSONTyped,
} from './NotifyHandling';

/**
 * 
 * @export
 * @interface PublishChangeEditInput
 */
export interface PublishChangeEditInput {
    /**
     * Notify handling that defines to whom email notifications should be sent after the change edit is published. + Allowed values are NONE and ALL. + If not set, the default is ALL.
     */
    notify?: NotifyHandling;
    /**
     * Additional information about whom to notify about the update as a map of recipient type to NotifyInfo entity.
     */
    notifyDetails?: { [key: string]: NotifyInfo; };
}



/**
 * Check if a given object implements the PublishChangeEditInput interface.
 */
export function instanceOfPublishChangeEditInput(value: object): value is PublishChangeEditInput {
    return true;
}

export function PublishChangeEditInputFromJSON(json: any): PublishChangeEditInput {
    return PublishChangeEditInputFromJSONTyped(json, false);
}

export function PublishChangeEditInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishChangeEditInput {
    if (json == null) {
        return json;
    }
    return {
        
        'notify': json['notify'] == null ? undefined : NotifyHandlingFromJSON(json['notify']),
        'notifyDetails': json['notify_details'] == null ? undefined : (mapValues(json['notify_details'], NotifyInfoFromJSON)),
    };
}

export function PublishChangeEditInputToJSON(json: any): PublishChangeEditInput {
    return PublishChangeEditInputToJSONTyped(json, false);
}

export function PublishChangeEditInputToJSONTyped(value?: PublishChangeEditInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notify': NotifyHandlingToJSON(value['notify']),
        'notify_details': value['notifyDetails'] == null ? undefined : (mapValues(value['notifyDetails'], NotifyInfoToJSON)),
    };
}

