/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RangeInfo
 */
export interface RangeInfo {
    /**
     * 
     */
    start?: number;
    /**
     * 
     */
    end?: number;
}

/**
 * Check if a given object implements the RangeInfo interface.
 */
export function instanceOfRangeInfo(value: object): value is RangeInfo {
    return true;
}

export function RangeInfoFromJSON(json: any): RangeInfo {
    return RangeInfoFromJSONTyped(json, false);
}

export function RangeInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RangeInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'] == null ? undefined : json['start'],
        'end': json['end'] == null ? undefined : json['end'],
    };
}

export function RangeInfoToJSON(json: any): RangeInfo {
    return RangeInfoToJSONTyped(json, false);
}

export function RangeInfoToJSONTyped(value?: RangeInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'],
        'end': value['end'],
    };
}

