/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChangeInfo } from './ChangeInfo';
import {
    ChangeInfoFromJSON,
    ChangeInfoFromJSONTyped,
    ChangeInfoToJSON,
    ChangeInfoToJSONTyped,
} from './ChangeInfo';

/**
 * 
 * @export
 * @interface RebaseChainInfo
 */
export interface RebaseChainInfo {
    /**
     * List of the unsubmitted ancestors, as ChangeInfo entities. Includes both rebased changes, and previously up-to-date ancestors. The list is ordered by ancestry, where the oldest ancestor is the first.
     */
    rebasedChanges?: Array<ChangeInfo>;
    /**
     * Whether any of the rebased changes has conflicts due to rebasing.
     */
    containsGitConflicts?: boolean;
}

/**
 * Check if a given object implements the RebaseChainInfo interface.
 */
export function instanceOfRebaseChainInfo(value: object): value is RebaseChainInfo {
    return true;
}

export function RebaseChainInfoFromJSON(json: any): RebaseChainInfo {
    return RebaseChainInfoFromJSONTyped(json, false);
}

export function RebaseChainInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RebaseChainInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'rebasedChanges': json['rebased_changes'] == null ? undefined : ((json['rebased_changes'] as Array<any>).map(ChangeInfoFromJSON)),
        'containsGitConflicts': json['contains_git_conflicts'] == null ? undefined : json['contains_git_conflicts'],
    };
}

export function RebaseChainInfoToJSON(json: any): RebaseChainInfo {
    return RebaseChainInfoToJSONTyped(json, false);
}

export function RebaseChainInfoToJSONTyped(value?: RebaseChainInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rebased_changes': value['rebasedChanges'] == null ? undefined : ((value['rebasedChanges'] as Array<any>).map(ChangeInfoToJSON)),
        'contains_git_conflicts': value['containsGitConflicts'],
    };
}

