/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReceiveInfo
 */
export interface ReceiveInfo {
    /**
     * Whether signed push validation support is enabled on the server; see the global configuration for details.
     */
    enableSignedPush?: boolean;
}

/**
 * Check if a given object implements the ReceiveInfo interface.
 */
export function instanceOfReceiveInfo(value: object): value is ReceiveInfo {
    return true;
}

export function ReceiveInfoFromJSON(json: any): ReceiveInfo {
    return ReceiveInfoFromJSONTyped(json, false);
}

export function ReceiveInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiveInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'enableSignedPush': json['enable_signed_push'] == null ? undefined : json['enable_signed_push'],
    };
}

export function ReceiveInfoToJSON(json: any): ReceiveInfo {
    return ReceiveInfoToJSONTyped(json, false);
}

export function ReceiveInfoToJSONTyped(value?: ReceiveInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enable_signed_push': value['enableSignedPush'],
    };
}

