/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReduceMaxTokenLifetimeInput
 */
export interface ReduceMaxTokenLifetimeInput {
    /**
     * The new maximum lifetime that will be applied to authentication tokens.
     */
    lifetime?: string;
}

/**
 * Check if a given object implements the ReduceMaxTokenLifetimeInput interface.
 */
export function instanceOfReduceMaxTokenLifetimeInput(value: object): value is ReduceMaxTokenLifetimeInput {
    return true;
}

export function ReduceMaxTokenLifetimeInputFromJSON(json: any): ReduceMaxTokenLifetimeInput {
    return ReduceMaxTokenLifetimeInputFromJSONTyped(json, false);
}

export function ReduceMaxTokenLifetimeInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReduceMaxTokenLifetimeInput {
    if (json == null) {
        return json;
    }
    return {
        
        'lifetime': json['lifetime'] == null ? undefined : json['lifetime'],
    };
}

export function ReduceMaxTokenLifetimeInputToJSON(json: any): ReduceMaxTokenLifetimeInput {
    return ReduceMaxTokenLifetimeInputToJSONTyped(json, false);
}

export function ReduceMaxTokenLifetimeInputToJSONTyped(value?: ReduceMaxTokenLifetimeInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lifetime': value['lifetime'],
    };
}

