/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GitPerson } from './GitPerson';
import {
    GitPersonFromJSON,
    GitPersonFromJSONTyped,
    GitPersonToJSON,
    GitPersonToJSONTyped,
} from './GitPerson';

/**
 * 
 * @export
 * @interface ReflogEntryInfo
 */
export interface ReflogEntryInfo {
    /**
     * 
     */
    oldId?: string;
    /**
     * 
     */
    newId?: string;
    /**
     * 
     */
    who?: GitPerson;
    /**
     * 
     */
    comment?: string;
}

/**
 * Check if a given object implements the ReflogEntryInfo interface.
 */
export function instanceOfReflogEntryInfo(value: object): value is ReflogEntryInfo {
    return true;
}

export function ReflogEntryInfoFromJSON(json: any): ReflogEntryInfo {
    return ReflogEntryInfoFromJSONTyped(json, false);
}

export function ReflogEntryInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReflogEntryInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'oldId': json['old_id'] == null ? undefined : json['old_id'],
        'newId': json['new_id'] == null ? undefined : json['new_id'],
        'who': json['who'] == null ? undefined : GitPersonFromJSON(json['who']),
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function ReflogEntryInfoToJSON(json: any): ReflogEntryInfo {
    return ReflogEntryInfoToJSONTyped(json, false);
}

export function ReflogEntryInfoToJSONTyped(value?: ReflogEntryInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'old_id': value['oldId'],
        'new_id': value['newId'],
        'who': GitPersonToJSON(value['who']),
        'comment': value['comment'],
    };
}

