/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RelatedChangeAndCommitInfo } from './RelatedChangeAndCommitInfo';
import {
    RelatedChangeAndCommitInfoFromJSON,
    RelatedChangeAndCommitInfoFromJSONTyped,
    RelatedChangeAndCommitInfoToJSON,
    RelatedChangeAndCommitInfoToJSONTyped,
} from './RelatedChangeAndCommitInfo';

/**
 * 
 * @export
 * @interface RelatedChangesInfo
 */
export interface RelatedChangesInfo {
    /**
     * A list of RelatedChangeAndCommitInfo entities describing the related changes. Sorted by git commit order, newest to oldest. Empty if there are no related changes.
     */
    changes?: Array<RelatedChangeAndCommitInfo>;
}

/**
 * Check if a given object implements the RelatedChangesInfo interface.
 */
export function instanceOfRelatedChangesInfo(value: object): value is RelatedChangesInfo {
    return true;
}

export function RelatedChangesInfoFromJSON(json: any): RelatedChangesInfo {
    return RelatedChangesInfoFromJSONTyped(json, false);
}

export function RelatedChangesInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelatedChangesInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'changes': json['changes'] == null ? undefined : ((json['changes'] as Array<any>).map(RelatedChangeAndCommitInfoFromJSON)),
    };
}

export function RelatedChangesInfoToJSON(json: any): RelatedChangesInfo {
    return RelatedChangesInfoToJSONTyped(json, false);
}

export function RelatedChangesInfoToJSONTyped(value?: RelatedChangesInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'changes': value['changes'] == null ? undefined : ((value['changes'] as Array<any>).map(RelatedChangeAndCommitInfoToJSON)),
    };
}

