/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommitInfo } from './CommitInfo';
import {
    CommitInfoFromJSON,
    CommitInfoFromJSONTyped,
    CommitInfoToJSON,
    CommitInfoToJSONTyped,
} from './CommitInfo';

/**
 * 
 * @export
 * @interface RelatedChangeAndCommitInfo
 */
export interface RelatedChangeAndCommitInfo {
    /**
     * 
     */
    project?: string;
    /**
     * 
     */
    changeId?: string;
    /**
     * 
     */
    commit?: CommitInfo;
    /**
     * 
     */
    changeNumber?: number;
    /**
     * 
     */
    revisionNumber?: number;
    /**
     * 
     */
    currentRevisionNumber?: number;
    /**
     * 
     */
    status?: string;
    /**
     * 
     */
    submittable?: boolean;
    /**
     * 
     */
    workInProgress?: boolean;
}

/**
 * Check if a given object implements the RelatedChangeAndCommitInfo interface.
 */
export function instanceOfRelatedChangeAndCommitInfo(value: object): value is RelatedChangeAndCommitInfo {
    return true;
}

export function RelatedChangeAndCommitInfoFromJSON(json: any): RelatedChangeAndCommitInfo {
    return RelatedChangeAndCommitInfoFromJSONTyped(json, false);
}

export function RelatedChangeAndCommitInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelatedChangeAndCommitInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'project': json['project'] == null ? undefined : json['project'],
        'changeId': json['change_id'] == null ? undefined : json['change_id'],
        'commit': json['commit'] == null ? undefined : CommitInfoFromJSON(json['commit']),
        'changeNumber': json['_change_number'] == null ? undefined : json['_change_number'],
        'revisionNumber': json['_revision_number'] == null ? undefined : json['_revision_number'],
        'currentRevisionNumber': json['_current_revision_number'] == null ? undefined : json['_current_revision_number'],
        'status': json['status'] == null ? undefined : json['status'],
        'submittable': json['submittable'] == null ? undefined : json['submittable'],
        'workInProgress': json['work_in_progress'] == null ? undefined : json['work_in_progress'],
    };
}

export function RelatedChangeAndCommitInfoToJSON(json: any): RelatedChangeAndCommitInfo {
    return RelatedChangeAndCommitInfoToJSONTyped(json, false);
}

export function RelatedChangeAndCommitInfoToJSONTyped(value?: RelatedChangeAndCommitInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project': value['project'],
        'change_id': value['changeId'],
        'commit': CommitInfoToJSON(value['commit']),
        '_change_number': value['changeNumber'],
        '_revision_number': value['revisionNumber'],
        '_current_revision_number': value['currentRevisionNumber'],
        'status': value['status'],
        'submittable': value['submittable'],
        'work_in_progress': value['workInProgress'],
    };
}

