/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ResponsiveMode = {
    None: 'NONE',
    ShrinkOnly: 'SHRINK_ONLY',
    FullResponsive: 'FULL_RESPONSIVE',
} as const;
export type ResponsiveMode = typeof ResponsiveMode[keyof typeof ResponsiveMode];


export function instanceOfResponsiveMode(value: any): boolean {
    for (const key in ResponsiveMode) {
        if (Object.prototype.hasOwnProperty.call(ResponsiveMode, key)) {
            if (ResponsiveMode[key as keyof typeof ResponsiveMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ResponsiveModeFromJSON(json: any): ResponsiveMode {
    return ResponsiveModeFromJSONTyped(json, false);
}

export function ResponsiveModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsiveMode {
    return json as ResponsiveMode;
}

export function ResponsiveModeToJSON(value?: ResponsiveMode | null): any {
    return value as any;
}

export function ResponsiveModeToJSONTyped(value: any, ignoreDiscriminator: boolean): ResponsiveMode {
    return value as ResponsiveMode;
}

