/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotifyInfo } from './NotifyInfo';
import {
    NotifyInfoFromJSON,
    NotifyInfoFromJSONTyped,
    NotifyInfoToJSON,
    NotifyInfoToJSONTyped,
} from './NotifyInfo';
import type { NotifyHandling } from './NotifyHandling';
import {
    NotifyHandlingFromJSON,
    NotifyHandlingFromJSONTyped,
    NotifyHandlingToJSON,
    NotifyHandlingToJSONTyped,
} from './NotifyHandling';

/**
 * 
 * @export
 * @interface RevertInput
 */
export interface RevertInput {
    /**
     * 
     */
    message?: string;
    /**
     * 
     */
    notify?: NotifyHandling;
    /**
     * 
     */
    notifyDetails?: { [key: string]: NotifyInfo; };
    /**
     * 
     */
    topic?: string;
    /**
     * 
     */
    workInProgress?: boolean;
    /**
     * 
     */
    validationOptions?: { [key: string]: string; };
}



/**
 * Check if a given object implements the RevertInput interface.
 */
export function instanceOfRevertInput(value: object): value is RevertInput {
    return true;
}

export function RevertInputFromJSON(json: any): RevertInput {
    return RevertInputFromJSONTyped(json, false);
}

export function RevertInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevertInput {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'notify': json['notify'] == null ? undefined : NotifyHandlingFromJSON(json['notify']),
        'notifyDetails': json['notify_details'] == null ? undefined : (mapValues(json['notify_details'], NotifyInfoFromJSON)),
        'topic': json['topic'] == null ? undefined : json['topic'],
        'workInProgress': json['work_in_progress'] == null ? undefined : json['work_in_progress'],
        'validationOptions': json['validation_options'] == null ? undefined : json['validation_options'],
    };
}

export function RevertInputToJSON(json: any): RevertInput {
    return RevertInputToJSONTyped(json, false);
}

export function RevertInputToJSONTyped(value?: RevertInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'notify': NotifyHandlingToJSON(value['notify']),
        'notify_details': value['notifyDetails'] == null ? undefined : (mapValues(value['notifyDetails'], NotifyInfoToJSON)),
        'topic': value['topic'],
        'work_in_progress': value['workInProgress'],
        'validation_options': value['validationOptions'],
    };
}

