/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListChangesOption } from './ListChangesOption';
import {
    ListChangesOptionFromJSON,
    ListChangesOptionFromJSONTyped,
    ListChangesOptionToJSON,
    ListChangesOptionToJSONTyped,
} from './ListChangesOption';
import type { CommentInput } from './CommentInput';
import {
    CommentInputFromJSON,
    CommentInputFromJSONTyped,
    CommentInputToJSON,
    CommentInputToJSONTyped,
} from './CommentInput';
import type { AttentionSetInput } from './AttentionSetInput';
import {
    AttentionSetInputFromJSON,
    AttentionSetInputFromJSONTyped,
    AttentionSetInputToJSON,
    AttentionSetInputToJSONTyped,
} from './AttentionSetInput';
import type { DraftHandling } from './DraftHandling';
import {
    DraftHandlingFromJSON,
    DraftHandlingFromJSONTyped,
    DraftHandlingToJSON,
    DraftHandlingToJSONTyped,
} from './DraftHandling';
import type { NotifyInfo } from './NotifyInfo';
import {
    NotifyInfoFromJSON,
    NotifyInfoFromJSONTyped,
    NotifyInfoToJSON,
    NotifyInfoToJSONTyped,
} from './NotifyInfo';
import type { NotifyHandling } from './NotifyHandling';
import {
    NotifyHandlingFromJSON,
    NotifyHandlingFromJSONTyped,
    NotifyHandlingToJSON,
    NotifyHandlingToJSONTyped,
} from './NotifyHandling';
import type { ReviewerInput } from './ReviewerInput';
import {
    ReviewerInputFromJSON,
    ReviewerInputFromJSONTyped,
    ReviewerInputToJSON,
    ReviewerInputToJSONTyped,
} from './ReviewerInput';

/**
 * 
 * @export
 * @interface ReviewInput
 */
export interface ReviewInput {
    /**
     * The message to be added as review comment.
     */
    message?: string;
    /**
     * Apply this tag to the review comment message, votes, and inline comments. Tags with an 'autogenerated:' prefix may be used by CI or other automated systems to distinguish them from human reviews.
     */
    tag?: string;
    /**
     * The votes that should be added to the revision as a map that maps the label names to the voting values.
     */
    labels?: { [key: string]: number; };
    /**
     * The comments that should be added as a map that maps a file path to a list of CommentInput entities.
     */
    comments?: { [key: string]: Array<CommentInput>; };
    /**
     * Draft handling that defines how draft comments are handled that are already in the database but that were not also described in this input. + Allowed values are PUBLISH, PUBLISH_ALL_REVISIONS and KEEP. All values except PUBLISH_ALL_REVISIONS operate only on drafts for a single revision.
     */
    drafts?: DraftHandling;
    /**
     * List of draft IDs to be published. The draft IDs should belong to the current user and be valid. If drafts is set to PUBLISH, then draft IDs should contain drafts for the same revision that is requested for review.
     */
    draftIdsToPublish?: Array<string>;
    /**
     * Notify handling that defines to whom email notifications should be sent after the review is stored. + Allowed values are NONE, OWNER, OWNER_REVIEWERS and ALL. + If not set, the default is ALL.
     */
    notify?: NotifyHandling;
    /**
     * Additional information about whom to notify about the update as a map of recipient type to NotifyInfo entity.
     */
    notifyDetails?: { [key: string]: NotifyInfo; };
    /**
     * If true, comments with the same content at the same place will be omitted.
     */
    omitDuplicateComments?: boolean;
    /**
     * \{account-id\} the review should be posted on behalf of. To use this option the caller must have been granted labelAs-NAME permission for all keys of labels.
     */
    onBehalfOf?: string;
    /**
     * A list of ReviewerInput representing reviewers that should be added/removed to/from the change.
     */
    reviewers?: Array<ReviewerInput>;
    /**
     * If true, mark the change as work in progress. It is an error for both ready and work_in_progress to be true.
     */
    workInProgress?: boolean;
    /**
     * If true, and if the change is work in progress, then start review. It is an error for both ready and work_in_progress to be true.
     */
    ready?: boolean;
    /**
     * list of AttentionSetInput entities to add to the attention set. Users that are not reviewers, ccs, owner, or uploader are silently ignored.
     */
    addToAttentionSet?: Array<AttentionSetInput>;
    /**
     * list of AttentionSetInput entities to remove from the attention set.
     */
    removeFromAttentionSet?: Array<AttentionSetInput>;
    /**
     * If set to true, ignore all automatic attention set rules described in the attention set. Updates in add_to_attention_set and remove_from_attention_set are not ignored.
     */
    ignoreAutomaticAttentionSetRules?: boolean;
    /**
     * List of query options to format the response.
     */
    responseFormatOptions?: Array<ListChangesOption>;
}



/**
 * Check if a given object implements the ReviewInput interface.
 */
export function instanceOfReviewInput(value: object): value is ReviewInput {
    return true;
}

export function ReviewInputFromJSON(json: any): ReviewInput {
    return ReviewInputFromJSONTyped(json, false);
}

export function ReviewInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewInput {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'comments': json['comments'] == null ? undefined : json['comments'],
        'drafts': json['drafts'] == null ? undefined : DraftHandlingFromJSON(json['drafts']),
        'draftIdsToPublish': json['draft_ids_to_publish'] == null ? undefined : json['draft_ids_to_publish'],
        'notify': json['notify'] == null ? undefined : NotifyHandlingFromJSON(json['notify']),
        'notifyDetails': json['notify_details'] == null ? undefined : (mapValues(json['notify_details'], NotifyInfoFromJSON)),
        'omitDuplicateComments': json['omit_duplicate_comments'] == null ? undefined : json['omit_duplicate_comments'],
        'onBehalfOf': json['on_behalf_of'] == null ? undefined : json['on_behalf_of'],
        'reviewers': json['reviewers'] == null ? undefined : ((json['reviewers'] as Array<any>).map(ReviewerInputFromJSON)),
        'workInProgress': json['work_in_progress'] == null ? undefined : json['work_in_progress'],
        'ready': json['ready'] == null ? undefined : json['ready'],
        'addToAttentionSet': json['add_to_attention_set'] == null ? undefined : ((json['add_to_attention_set'] as Array<any>).map(AttentionSetInputFromJSON)),
        'removeFromAttentionSet': json['remove_from_attention_set'] == null ? undefined : ((json['remove_from_attention_set'] as Array<any>).map(AttentionSetInputFromJSON)),
        'ignoreAutomaticAttentionSetRules': json['ignore_automatic_attention_set_rules'] == null ? undefined : json['ignore_automatic_attention_set_rules'],
        'responseFormatOptions': json['response_format_options'] == null ? undefined : ((json['response_format_options'] as Array<any>).map(ListChangesOptionFromJSON)),
    };
}

export function ReviewInputToJSON(json: any): ReviewInput {
    return ReviewInputToJSONTyped(json, false);
}

export function ReviewInputToJSONTyped(value?: ReviewInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'tag': value['tag'],
        'labels': value['labels'],
        'comments': value['comments'],
        'drafts': DraftHandlingToJSON(value['drafts']),
        'draft_ids_to_publish': value['draftIdsToPublish'],
        'notify': NotifyHandlingToJSON(value['notify']),
        'notify_details': value['notifyDetails'] == null ? undefined : (mapValues(value['notifyDetails'], NotifyInfoToJSON)),
        'omit_duplicate_comments': value['omitDuplicateComments'],
        'on_behalf_of': value['onBehalfOf'],
        'reviewers': value['reviewers'] == null ? undefined : ((value['reviewers'] as Array<any>).map(ReviewerInputToJSON)),
        'work_in_progress': value['workInProgress'],
        'ready': value['ready'],
        'add_to_attention_set': value['addToAttentionSet'] == null ? undefined : ((value['addToAttentionSet'] as Array<any>).map(AttentionSetInputToJSON)),
        'remove_from_attention_set': value['removeFromAttentionSet'] == null ? undefined : ((value['removeFromAttentionSet'] as Array<any>).map(AttentionSetInputToJSON)),
        'ignore_automatic_attention_set_rules': value['ignoreAutomaticAttentionSetRules'],
        'response_format_options': value['responseFormatOptions'] == null ? undefined : ((value['responseFormatOptions'] as Array<any>).map(ListChangesOptionToJSON)),
    };
}

