/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChangeInfo } from './ChangeInfo';
import {
    ChangeInfoFromJSON,
    ChangeInfoFromJSONTyped,
    ChangeInfoToJSON,
    ChangeInfoToJSONTyped,
} from './ChangeInfo';
import type { ReviewerResult } from './ReviewerResult';
import {
    ReviewerResultFromJSON,
    ReviewerResultFromJSONTyped,
    ReviewerResultToJSON,
    ReviewerResultToJSONTyped,
} from './ReviewerResult';

/**
 * 
 * @export
 * @interface ReviewResult
 */
export interface ReviewResult {
    /**
     * 
     */
    labels?: { [key: string]: number; };
    /**
     * 
     */
    reviewers?: { [key: string]: ReviewerResult; };
    /**
     * 
     */
    ready?: boolean;
    /**
     * 
     */
    error?: string;
    /**
     * 
     */
    changeInfo?: ChangeInfo;
}

/**
 * Check if a given object implements the ReviewResult interface.
 */
export function instanceOfReviewResult(value: object): value is ReviewResult {
    return true;
}

export function ReviewResultFromJSON(json: any): ReviewResult {
    return ReviewResultFromJSONTyped(json, false);
}

export function ReviewResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewResult {
    if (json == null) {
        return json;
    }
    return {
        
        'labels': json['labels'] == null ? undefined : json['labels'],
        'reviewers': json['reviewers'] == null ? undefined : (mapValues(json['reviewers'], ReviewerResultFromJSON)),
        'ready': json['ready'] == null ? undefined : json['ready'],
        'error': json['error'] == null ? undefined : json['error'],
        'changeInfo': json['change_info'] == null ? undefined : ChangeInfoFromJSON(json['change_info']),
    };
}

export function ReviewResultToJSON(json: any): ReviewResult {
    return ReviewResultToJSONTyped(json, false);
}

export function ReviewResultToJSONTyped(value?: ReviewResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'labels': value['labels'],
        'reviewers': value['reviewers'] == null ? undefined : (mapValues(value['reviewers'], ReviewerResultToJSON)),
        'ready': value['ready'],
        'error': value['error'],
        'change_info': ChangeInfoToJSON(value['changeInfo']),
    };
}

