/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewerState } from './ReviewerState';
import {
    ReviewerStateFromJSON,
    ReviewerStateFromJSONTyped,
    ReviewerStateToJSON,
    ReviewerStateToJSONTyped,
} from './ReviewerState';
import type { NotifyInfo } from './NotifyInfo';
import {
    NotifyInfoFromJSON,
    NotifyInfoFromJSONTyped,
    NotifyInfoToJSON,
    NotifyInfoToJSONTyped,
} from './NotifyInfo';
import type { NotifyHandling } from './NotifyHandling';
import {
    NotifyHandlingFromJSON,
    NotifyHandlingFromJSONTyped,
    NotifyHandlingToJSON,
    NotifyHandlingToJSONTyped,
} from './NotifyHandling';

/**
 * 
 * @export
 * @interface ReviewerInput
 */
export interface ReviewerInput {
    /**
     * 
     */
    reviewer?: string;
    /**
     * 
     */
    confirmed?: boolean;
    /**
     * 
     */
    state?: ReviewerState;
    /**
     * 
     */
    notify?: NotifyHandling;
    /**
     * 
     */
    notifyDetails?: { [key: string]: NotifyInfo; };
    /**
     * 
     */
    onBehalfOf?: string;
}



/**
 * Check if a given object implements the ReviewerInput interface.
 */
export function instanceOfReviewerInput(value: object): value is ReviewerInput {
    return true;
}

export function ReviewerInputFromJSON(json: any): ReviewerInput {
    return ReviewerInputFromJSONTyped(json, false);
}

export function ReviewerInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewerInput {
    if (json == null) {
        return json;
    }
    return {
        
        'reviewer': json['reviewer'] == null ? undefined : json['reviewer'],
        'confirmed': json['confirmed'] == null ? undefined : json['confirmed'],
        'state': json['state'] == null ? undefined : ReviewerStateFromJSON(json['state']),
        'notify': json['notify'] == null ? undefined : NotifyHandlingFromJSON(json['notify']),
        'notifyDetails': json['notify_details'] == null ? undefined : (mapValues(json['notify_details'], NotifyInfoFromJSON)),
        'onBehalfOf': json['on_behalf_of'] == null ? undefined : json['on_behalf_of'],
    };
}

export function ReviewerInputToJSON(json: any): ReviewerInput {
    return ReviewerInputToJSONTyped(json, false);
}

export function ReviewerInputToJSONTyped(value?: ReviewerInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reviewer': value['reviewer'],
        'confirmed': value['confirmed'],
        'state': ReviewerStateToJSON(value['state']),
        'notify': NotifyHandlingToJSON(value['notify']),
        'notify_details': value['notifyDetails'] == null ? undefined : (mapValues(value['notifyDetails'], NotifyInfoToJSON)),
        'on_behalf_of': value['onBehalfOf'],
    };
}

