/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountInfo } from './AccountInfo';
import {
    AccountInfoFromJSON,
    AccountInfoFromJSONTyped,
    AccountInfoToJSON,
    AccountInfoToJSONTyped,
} from './AccountInfo';
import type { ReviewerInfo } from './ReviewerInfo';
import {
    ReviewerInfoFromJSON,
    ReviewerInfoFromJSONTyped,
    ReviewerInfoToJSON,
    ReviewerInfoToJSONTyped,
} from './ReviewerInfo';

/**
 * 
 * @export
 * @interface ReviewerResult
 */
export interface ReviewerResult {
    /**
     * 
     */
    input?: string;
    /**
     * 
     */
    error?: string;
    /**
     * 
     */
    confirm?: boolean;
    /**
     * 
     */
    reviewers?: Array<ReviewerInfo>;
    /**
     * 
     */
    ccs?: Array<AccountInfo>;
    /**
     * 
     */
    removed?: AccountInfo;
}

/**
 * Check if a given object implements the ReviewerResult interface.
 */
export function instanceOfReviewerResult(value: object): value is ReviewerResult {
    return true;
}

export function ReviewerResultFromJSON(json: any): ReviewerResult {
    return ReviewerResultFromJSONTyped(json, false);
}

export function ReviewerResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewerResult {
    if (json == null) {
        return json;
    }
    return {
        
        'input': json['input'] == null ? undefined : json['input'],
        'error': json['error'] == null ? undefined : json['error'],
        'confirm': json['confirm'] == null ? undefined : json['confirm'],
        'reviewers': json['reviewers'] == null ? undefined : ((json['reviewers'] as Array<any>).map(ReviewerInfoFromJSON)),
        'ccs': json['ccs'] == null ? undefined : ((json['ccs'] as Array<any>).map(AccountInfoFromJSON)),
        'removed': json['removed'] == null ? undefined : AccountInfoFromJSON(json['removed']),
    };
}

export function ReviewerResultToJSON(json: any): ReviewerResult {
    return ReviewerResultToJSONTyped(json, false);
}

export function ReviewerResultToJSONTyped(value?: ReviewerResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'input': value['input'],
        'error': value['error'],
        'confirm': value['confirm'],
        'reviewers': value['reviewers'] == null ? undefined : ((value['reviewers'] as Array<any>).map(ReviewerInfoToJSON)),
        'ccs': value['ccs'] == null ? undefined : ((value['ccs'] as Array<any>).map(AccountInfoToJSON)),
        'removed': AccountInfoToJSON(value['removed']),
    };
}

