/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Side } from './Side';
import {
    SideFromJSON,
    SideFromJSONTyped,
    SideToJSON,
    SideToJSONTyped,
} from './Side';
import type { FixSuggestionInfo } from './FixSuggestionInfo';
import {
    FixSuggestionInfoFromJSON,
    FixSuggestionInfoFromJSONTyped,
    FixSuggestionInfoToJSON,
    FixSuggestionInfoToJSONTyped,
} from './FixSuggestionInfo';
import type { ContextLineInfo } from './ContextLineInfo';
import {
    ContextLineInfoFromJSON,
    ContextLineInfoFromJSONTyped,
    ContextLineInfoToJSON,
    ContextLineInfoToJSONTyped,
} from './ContextLineInfo';
import type { Range } from './Range';
import {
    RangeFromJSON,
    RangeFromJSONTyped,
    RangeToJSON,
    RangeToJSONTyped,
} from './Range';
import type { AccountInfo } from './AccountInfo';
import {
    AccountInfoFromJSON,
    AccountInfoFromJSONTyped,
    AccountInfoToJSON,
    AccountInfoToJSONTyped,
} from './AccountInfo';

/**
 * 
 * @export
 * @interface RobotCommentInfo
 */
export interface RobotCommentInfo {
    /**
     * 
     */
    author?: AccountInfo;
    /**
     * 
     */
    tag?: string;
    /**
     * 
     */
    changeMessageId?: string;
    /**
     * 
     */
    unresolved?: boolean;
    /**
     * 
     */
    contextLines?: Array<ContextLineInfo>;
    /**
     * 
     */
    sourceContentType?: string;
    /**
     * 
     */
    patchSet?: number;
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    path?: string;
    /**
     * 
     */
    side?: Side;
    /**
     * 
     */
    parent?: number;
    /**
     * 
     */
    line?: number;
    /**
     * 
     */
    range?: Range;
    /**
     * 
     */
    inReplyTo?: string;
    /**
     * 
     */
    updated?: string;
    /**
     * 
     */
    message?: string;
    /**
     * 
     */
    commitId?: string;
    /**
     * 
     */
    fixSuggestions?: Array<FixSuggestionInfo>;
    /**
     * 
     */
    isAi?: boolean;
}



/**
 * Check if a given object implements the RobotCommentInfo interface.
 */
export function instanceOfRobotCommentInfo(value: object): value is RobotCommentInfo {
    return true;
}

export function RobotCommentInfoFromJSON(json: any): RobotCommentInfo {
    return RobotCommentInfoFromJSONTyped(json, false);
}

export function RobotCommentInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RobotCommentInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'author': json['author'] == null ? undefined : AccountInfoFromJSON(json['author']),
        'tag': json['tag'] == null ? undefined : json['tag'],
        'changeMessageId': json['change_message_id'] == null ? undefined : json['change_message_id'],
        'unresolved': json['unresolved'] == null ? undefined : json['unresolved'],
        'contextLines': json['context_lines'] == null ? undefined : ((json['context_lines'] as Array<any>).map(ContextLineInfoFromJSON)),
        'sourceContentType': json['source_content_type'] == null ? undefined : json['source_content_type'],
        'patchSet': json['patch_set'] == null ? undefined : json['patch_set'],
        'id': json['id'] == null ? undefined : json['id'],
        'path': json['path'] == null ? undefined : json['path'],
        'side': json['side'] == null ? undefined : SideFromJSON(json['side']),
        'parent': json['parent'] == null ? undefined : json['parent'],
        'line': json['line'] == null ? undefined : json['line'],
        'range': json['range'] == null ? undefined : RangeFromJSON(json['range']),
        'inReplyTo': json['in_reply_to'] == null ? undefined : json['in_reply_to'],
        'updated': json['updated'] == null ? undefined : json['updated'],
        'message': json['message'] == null ? undefined : json['message'],
        'commitId': json['commit_id'] == null ? undefined : json['commit_id'],
        'fixSuggestions': json['fix_suggestions'] == null ? undefined : ((json['fix_suggestions'] as Array<any>).map(FixSuggestionInfoFromJSON)),
        'isAi': json['is_ai'] == null ? undefined : json['is_ai'],
    };
}

export function RobotCommentInfoToJSON(json: any): RobotCommentInfo {
    return RobotCommentInfoToJSONTyped(json, false);
}

export function RobotCommentInfoToJSONTyped(value?: RobotCommentInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'author': AccountInfoToJSON(value['author']),
        'tag': value['tag'],
        'change_message_id': value['changeMessageId'],
        'unresolved': value['unresolved'],
        'context_lines': value['contextLines'] == null ? undefined : ((value['contextLines'] as Array<any>).map(ContextLineInfoToJSON)),
        'source_content_type': value['sourceContentType'],
        'patch_set': value['patchSet'],
        'id': value['id'],
        'path': value['path'],
        'side': SideToJSON(value['side']),
        'parent': value['parent'],
        'line': value['line'],
        'range': RangeToJSON(value['range']),
        'in_reply_to': value['inReplyTo'],
        'updated': value['updated'],
        'message': value['message'],
        'commit_id': value['commitId'],
        'fix_suggestions': value['fixSuggestions'] == null ? undefined : ((value['fixSuggestions'] as Array<any>).map(FixSuggestionInfoToJSON)),
        'is_ai': value['isAi'],
    };
}

