/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SchemaMigrateLabelFunctionsToSubmitRequirementStatus = {
    Migrated: 'MIGRATED',
    HasProlog: 'HAS_PROLOG',
    PreviouslyMigrated: 'PREVIOUSLY_MIGRATED',
    NoChange: 'NO_CHANGE',
} as const;
export type SchemaMigrateLabelFunctionsToSubmitRequirementStatus = typeof SchemaMigrateLabelFunctionsToSubmitRequirementStatus[keyof typeof SchemaMigrateLabelFunctionsToSubmitRequirementStatus];


export function instanceOfSchemaMigrateLabelFunctionsToSubmitRequirementStatus(value: any): boolean {
    for (const key in SchemaMigrateLabelFunctionsToSubmitRequirementStatus) {
        if (Object.prototype.hasOwnProperty.call(SchemaMigrateLabelFunctionsToSubmitRequirementStatus, key)) {
            if (SchemaMigrateLabelFunctionsToSubmitRequirementStatus[key as keyof typeof SchemaMigrateLabelFunctionsToSubmitRequirementStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SchemaMigrateLabelFunctionsToSubmitRequirementStatusFromJSON(json: any): SchemaMigrateLabelFunctionsToSubmitRequirementStatus {
    return SchemaMigrateLabelFunctionsToSubmitRequirementStatusFromJSONTyped(json, false);
}

export function SchemaMigrateLabelFunctionsToSubmitRequirementStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaMigrateLabelFunctionsToSubmitRequirementStatus {
    return json as SchemaMigrateLabelFunctionsToSubmitRequirementStatus;
}

export function SchemaMigrateLabelFunctionsToSubmitRequirementStatusToJSON(value?: SchemaMigrateLabelFunctionsToSubmitRequirementStatus | null): any {
    return value as any;
}

export function SchemaMigrateLabelFunctionsToSubmitRequirementStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): SchemaMigrateLabelFunctionsToSubmitRequirementStatus {
    return value as SchemaMigrateLabelFunctionsToSubmitRequirementStatus;
}

