/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetadataInfo } from './MetadataInfo';
import {
    MetadataInfoFromJSON,
    MetadataInfoFromJSONTyped,
    MetadataInfoToJSON,
    MetadataInfoToJSONTyped,
} from './MetadataInfo';
import type { UserConfigInfo } from './UserConfigInfo';
import {
    UserConfigInfoFromJSON,
    UserConfigInfoFromJSONTyped,
    UserConfigInfoToJSON,
    UserConfigInfoToJSONTyped,
} from './UserConfigInfo';
import type { AuthInfo } from './AuthInfo';
import {
    AuthInfoFromJSON,
    AuthInfoFromJSONTyped,
    AuthInfoToJSON,
    AuthInfoToJSONTyped,
} from './AuthInfo';
import type { SuggestInfo } from './SuggestInfo';
import {
    SuggestInfoFromJSON,
    SuggestInfoFromJSONTyped,
    SuggestInfoToJSON,
    SuggestInfoToJSONTyped,
} from './SuggestInfo';
import type { ReceiveInfo } from './ReceiveInfo';
import {
    ReceiveInfoFromJSON,
    ReceiveInfoFromJSONTyped,
    ReceiveInfoToJSON,
    ReceiveInfoToJSONTyped,
} from './ReceiveInfo';
import type { ChangeConfigInfo } from './ChangeConfigInfo';
import {
    ChangeConfigInfoFromJSON,
    ChangeConfigInfoFromJSONTyped,
    ChangeConfigInfoToJSON,
    ChangeConfigInfoToJSONTyped,
} from './ChangeConfigInfo';
import type { DownloadInfo } from './DownloadInfo';
import {
    DownloadInfoFromJSON,
    DownloadInfoFromJSONTyped,
    DownloadInfoToJSON,
    DownloadInfoToJSONTyped,
} from './DownloadInfo';
import type { PluginConfigInfo } from './PluginConfigInfo';
import {
    PluginConfigInfoFromJSON,
    PluginConfigInfoFromJSONTyped,
    PluginConfigInfoToJSON,
    PluginConfigInfoToJSONTyped,
} from './PluginConfigInfo';
import type { AccountsInfo } from './AccountsInfo';
import {
    AccountsInfoFromJSON,
    AccountsInfoFromJSONTyped,
    AccountsInfoToJSON,
    AccountsInfoToJSONTyped,
} from './AccountsInfo';
import type { GerritInfo } from './GerritInfo';
import {
    GerritInfoFromJSON,
    GerritInfoFromJSONTyped,
    GerritInfoToJSON,
    GerritInfoToJSONTyped,
} from './GerritInfo';
import type { GroupsInfo } from './GroupsInfo';
import {
    GroupsInfoFromJSON,
    GroupsInfoFromJSONTyped,
    GroupsInfoToJSON,
    GroupsInfoToJSONTyped,
} from './GroupsInfo';

/**
 * 
 * @export
 * @interface ServerInfo
 */
export interface ServerInfo {
    /**
     * Information about the configuration from the accounts section as AccountsConfigInfo entity.
     */
    accounts?: AccountsInfo;
    /**
     * Information about the authentication configuration as AuthInfo entity.
     */
    auth?: AuthInfo;
    /**
     * Information about the configuration from the change section as ChangeConfigInfo entity.
     */
    change?: ChangeConfigInfo;
    /**
     * Information about the configured download options as DownloadInfo entity. information about Gerrit
     */
    download?: DownloadInfo;
    /**
     * Information about the configuration from the gerrit section as GerritInfo entity.
     */
    gerrit?: GerritInfo;
    /**
     * Information about the configuration from the groups section as GroupsConfigInfo entity.
     */
    groups?: GroupsInfo;
    /**
     * Whether the NoteDb storage backend is fully enabled.
     */
    noteDbEnabled?: boolean;
    /**
     * Information about Gerrit extensions by plugins as PluginConfigInfo entity.
     */
    plugin?: PluginConfigInfo;
    /**
     * Information about the configuration from the sshd section as SshdInfo entity. Not set if SSHD is disabled.
     */
    sshd?: object;
    /**
     * Information about the configuration from the suggest section as SuggestInfo entity.
     */
    suggest?: SuggestInfo;
    /**
     * Information about the configuration from the user section as UserConfigInfo entity.
     */
    user?: UserConfigInfo;
    /**
     * Information about the receive-pack configuration as a ReceiveInfo entity.
     */
    receive?: ReceiveInfo;
    /**
     * URL to a default Gerrit UI theme plugin, if available. Located in /static/gerrit-theme.js by default.
     */
    defaultTheme?: string;
    /**
     * The list of submit requirement names that should be displayed as separate columns in the dashboard. If empty, the default is to display all submit requirements that are applicable for changes appearing in the dashboard.
     */
    submitRequirementDashboardColumns?: Array<string>;
    /**
     * Whether to show all labels in the dashboard, even if they are not submit requirements.
     */
    dashboardShowAllLabels?: boolean;
    /**
     * Optional server metadata as a list of MetadataInfo entities. If and which metadata is provided depends on the Gerrit setup.
     */
    metadata?: Array<MetadataInfo>;
}

/**
 * Check if a given object implements the ServerInfo interface.
 */
export function instanceOfServerInfo(value: object): value is ServerInfo {
    return true;
}

export function ServerInfoFromJSON(json: any): ServerInfo {
    return ServerInfoFromJSONTyped(json, false);
}

export function ServerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'accounts': json['accounts'] == null ? undefined : AccountsInfoFromJSON(json['accounts']),
        'auth': json['auth'] == null ? undefined : AuthInfoFromJSON(json['auth']),
        'change': json['change'] == null ? undefined : ChangeConfigInfoFromJSON(json['change']),
        'download': json['download'] == null ? undefined : DownloadInfoFromJSON(json['download']),
        'gerrit': json['gerrit'] == null ? undefined : GerritInfoFromJSON(json['gerrit']),
        'groups': json['groups'] == null ? undefined : GroupsInfoFromJSON(json['groups']),
        'noteDbEnabled': json['note_db_enabled'] == null ? undefined : json['note_db_enabled'],
        'plugin': json['plugin'] == null ? undefined : PluginConfigInfoFromJSON(json['plugin']),
        'sshd': json['sshd'] == null ? undefined : json['sshd'],
        'suggest': json['suggest'] == null ? undefined : SuggestInfoFromJSON(json['suggest']),
        'user': json['user'] == null ? undefined : UserConfigInfoFromJSON(json['user']),
        'receive': json['receive'] == null ? undefined : ReceiveInfoFromJSON(json['receive']),
        'defaultTheme': json['default_theme'] == null ? undefined : json['default_theme'],
        'submitRequirementDashboardColumns': json['submit_requirement_dashboard_columns'] == null ? undefined : json['submit_requirement_dashboard_columns'],
        'dashboardShowAllLabels': json['dashboard_show_all_labels'] == null ? undefined : json['dashboard_show_all_labels'],
        'metadata': json['metadata'] == null ? undefined : ((json['metadata'] as Array<any>).map(MetadataInfoFromJSON)),
    };
}

export function ServerInfoToJSON(json: any): ServerInfo {
    return ServerInfoToJSONTyped(json, false);
}

export function ServerInfoToJSONTyped(value?: ServerInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accounts': AccountsInfoToJSON(value['accounts']),
        'auth': AuthInfoToJSON(value['auth']),
        'change': ChangeConfigInfoToJSON(value['change']),
        'download': DownloadInfoToJSON(value['download']),
        'gerrit': GerritInfoToJSON(value['gerrit']),
        'groups': GroupsInfoToJSON(value['groups']),
        'note_db_enabled': value['noteDbEnabled'],
        'plugin': PluginConfigInfoToJSON(value['plugin']),
        'sshd': value['sshd'],
        'suggest': SuggestInfoToJSON(value['suggest']),
        'user': UserConfigInfoToJSON(value['user']),
        'receive': ReceiveInfoToJSON(value['receive']),
        'default_theme': value['defaultTheme'],
        'submit_requirement_dashboard_columns': value['submitRequirementDashboardColumns'],
        'dashboard_show_all_labels': value['dashboardShowAllLabels'],
        'metadata': value['metadata'] == null ? undefined : ((value['metadata'] as Array<any>).map(MetadataInfoToJSON)),
    };
}

