/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SnapshotIndexVersionInput
 */
export interface SnapshotIndexVersionInput {
    /**
     * A string ID that will be used as the folder name containing the snapshot. Defaults to current timestamp.
     */
    id?: string;
}

/**
 * Check if a given object implements the SnapshotIndexVersionInput interface.
 */
export function instanceOfSnapshotIndexVersionInput(value: object): value is SnapshotIndexVersionInput {
    return true;
}

export function SnapshotIndexVersionInputFromJSON(json: any): SnapshotIndexVersionInput {
    return SnapshotIndexVersionInputFromJSONTyped(json, false);
}

export function SnapshotIndexVersionInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnapshotIndexVersionInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function SnapshotIndexVersionInputToJSON(json: any): SnapshotIndexVersionInput {
    return SnapshotIndexVersionInputToJSONTyped(json, false);
}

export function SnapshotIndexVersionInputToJSONTyped(value?: SnapshotIndexVersionInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

