/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SnapshotIndexInput
 */
export interface SnapshotIndexInput {
    /**
     * 
     */
    id?: string;
}

/**
 * Check if a given object implements the SnapshotIndexInput interface.
 */
export function instanceOfSnapshotIndexInput(value: object): value is SnapshotIndexInput {
    return true;
}

export function SnapshotIndexInputFromJSON(json: any): SnapshotIndexInput {
    return SnapshotIndexInputFromJSONTyped(json, false);
}

export function SnapshotIndexInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnapshotIndexInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function SnapshotIndexInputToJSON(json: any): SnapshotIndexInput {
    return SnapshotIndexInputToJSONTyped(json, false);
}

export function SnapshotIndexInputToJSONTyped(value?: SnapshotIndexInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

