/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const State = {
    Done: 'DONE',
    Cancelled: 'CANCELLED',
    Stopping: 'STOPPING',
    Running: 'RUNNING',
    Starting: 'STARTING',
    Parked: 'PARKED',
    Ready: 'READY',
    Sleeping: 'SLEEPING',
    Other: 'OTHER',
} as const;
export type State = typeof State[keyof typeof State];


export function instanceOfState(value: any): boolean {
    for (const key in State) {
        if (Object.prototype.hasOwnProperty.call(State, key)) {
            if (State[key as keyof typeof State] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StateFromJSON(json: any): State {
    return StateFromJSONTyped(json, false);
}

export function StateFromJSONTyped(json: any, ignoreDiscriminator: boolean): State {
    return json as State;
}

export function StateToJSON(value?: State | null): any {
    return value as any;
}

export function StateToJSONTyped(value: any, ignoreDiscriminator: boolean): State {
    return value as State;
}

