/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubmitRequirementResultInfoStatus } from './SubmitRequirementResultInfoStatus';
import {
    SubmitRequirementResultInfoStatusFromJSON,
    SubmitRequirementResultInfoStatusFromJSONTyped,
    SubmitRequirementResultInfoStatusToJSON,
    SubmitRequirementResultInfoStatusToJSONTyped,
} from './SubmitRequirementResultInfoStatus';
import type { SubmitRequirementExpressionInfo } from './SubmitRequirementExpressionInfo';
import {
    SubmitRequirementExpressionInfoFromJSON,
    SubmitRequirementExpressionInfoFromJSONTyped,
    SubmitRequirementExpressionInfoToJSON,
    SubmitRequirementExpressionInfoToJSONTyped,
} from './SubmitRequirementExpressionInfo';

/**
 * 
 * @export
 * @interface SubmitRequirementResultInfo
 */
export interface SubmitRequirementResultInfo {
    /**
     * The submit requirement name.
     */
    name?: string;
    /**
     * Description of the submit requirement.
     */
    description?: string;
    /**
     * Status describing the result of evaluating the submit requirement. The status is one of (SATISFIED, UNSATISFIED, OVERRIDDEN, NOT_APPLICABLE, ERROR, FORCED, TIMEOUT).
     */
    status?: SubmitRequirementResultInfoStatus;
    /**
     * If true, this submit requirement result was created from a legacy SubmitRecord. Otherwise, it was created by evaluating a submit requirement.
     */
    isLegacy?: boolean;
    /**
     * A SubmitRequirementExpressionInfo containing the result of evaluating the applicability expression. Not set if the submit requirement did not define an applicability expression. Note that fields expression, passing_atoms and failing_atoms are always omitted for the applicability_expression_result.
     */
    applicabilityExpressionResult?: SubmitRequirementExpressionInfo;
    /**
     * A SubmitRequirementExpressionInfo containing the result of evaluating the submittability expression. + If the submit requirement does not apply, the status field of the result will be set to NOT_EVALUATED.
     */
    submittabilityExpressionResult?: SubmitRequirementExpressionInfo;
    /**
     * A SubmitRequirementExpressionInfo containing the result of evaluating the override expression. + Not set if the submit requirement did not define an override expression. If the submit requirement does not apply, the status field of the result will be set to NOT_EVALUATED.
     */
    overrideExpressionResult?: SubmitRequirementExpressionInfo;
}



/**
 * Check if a given object implements the SubmitRequirementResultInfo interface.
 */
export function instanceOfSubmitRequirementResultInfo(value: object): value is SubmitRequirementResultInfo {
    return true;
}

export function SubmitRequirementResultInfoFromJSON(json: any): SubmitRequirementResultInfo {
    return SubmitRequirementResultInfoFromJSONTyped(json, false);
}

export function SubmitRequirementResultInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitRequirementResultInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : SubmitRequirementResultInfoStatusFromJSON(json['status']),
        'isLegacy': json['is_legacy'] == null ? undefined : json['is_legacy'],
        'applicabilityExpressionResult': json['applicability_expression_result'] == null ? undefined : SubmitRequirementExpressionInfoFromJSON(json['applicability_expression_result']),
        'submittabilityExpressionResult': json['submittability_expression_result'] == null ? undefined : SubmitRequirementExpressionInfoFromJSON(json['submittability_expression_result']),
        'overrideExpressionResult': json['override_expression_result'] == null ? undefined : SubmitRequirementExpressionInfoFromJSON(json['override_expression_result']),
    };
}

export function SubmitRequirementResultInfoToJSON(json: any): SubmitRequirementResultInfo {
    return SubmitRequirementResultInfoToJSONTyped(json, false);
}

export function SubmitRequirementResultInfoToJSONTyped(value?: SubmitRequirementResultInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'status': SubmitRequirementResultInfoStatusToJSON(value['status']),
        'is_legacy': value['isLegacy'],
        'applicability_expression_result': SubmitRequirementExpressionInfoToJSON(value['applicabilityExpressionResult']),
        'submittability_expression_result': SubmitRequirementExpressionInfoToJSON(value['submittabilityExpressionResult']),
        'override_expression_result': SubmitRequirementExpressionInfoToJSON(value['overrideExpressionResult']),
    };
}

