/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotifyInfo } from './NotifyInfo';
import {
    NotifyInfoFromJSON,
    NotifyInfoFromJSONTyped,
    NotifyInfoToJSON,
    NotifyInfoToJSONTyped,
} from './NotifyInfo';
import type { NotifyHandling } from './NotifyHandling';
import {
    NotifyHandlingFromJSON,
    NotifyHandlingFromJSONTyped,
    NotifyHandlingToJSON,
    NotifyHandlingToJSONTyped,
} from './NotifyHandling';

/**
 * 
 * @export
 * @interface SubmitInput
 */
export interface SubmitInput {
    /**
     * 
     */
    waitForMerge?: boolean;
    /**
     * If set, submit the change on behalf of the given user. The value may take any format accepted by the accounts REST API. Using this option requires Submit (On Behalf Of) permission on the branch.
     */
    onBehalfOf?: string;
    /**
     * Notify handling that defines to whom email notifications should be sent after the change is submitted. + Allowed values are NONE, OWNER, OWNER_REVIEWERS and ALL. + If not set, the default is ALL. + Ignored if a post approval diff is present (i.e.
     */
    notify?: NotifyHandling;
    /**
     * Additional information about whom to notify about the update as a map of recipient type to NotifyInfo entity.
     */
    notifyDetails?: { [key: string]: NotifyInfo; };
}



/**
 * Check if a given object implements the SubmitInput interface.
 */
export function instanceOfSubmitInput(value: object): value is SubmitInput {
    return true;
}

export function SubmitInputFromJSON(json: any): SubmitInput {
    return SubmitInputFromJSONTyped(json, false);
}

export function SubmitInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitInput {
    if (json == null) {
        return json;
    }
    return {
        
        'waitForMerge': json['wait_for_merge'] == null ? undefined : json['wait_for_merge'],
        'onBehalfOf': json['on_behalf_of'] == null ? undefined : json['on_behalf_of'],
        'notify': json['notify'] == null ? undefined : NotifyHandlingFromJSON(json['notify']),
        'notifyDetails': json['notify_details'] == null ? undefined : (mapValues(json['notify_details'], NotifyInfoFromJSON)),
    };
}

export function SubmitInputToJSON(json: any): SubmitInput {
    return SubmitInputToJSONTyped(json, false);
}

export function SubmitInputToJSONTyped(value?: SubmitInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wait_for_merge': value['waitForMerge'],
        'on_behalf_of': value['onBehalfOf'],
        'notify': NotifyHandlingToJSON(value['notify']),
        'notify_details': value['notifyDetails'] == null ? undefined : (mapValues(value['notifyDetails'], NotifyInfoToJSON)),
    };
}

