/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SubmitType = {
    Inherit: 'INHERIT',
    FastForwardOnly: 'FAST_FORWARD_ONLY',
    MergeIfNecessary: 'MERGE_IF_NECESSARY',
    RebaseIfNecessary: 'REBASE_IF_NECESSARY',
    RebaseAlways: 'REBASE_ALWAYS',
    MergeAlways: 'MERGE_ALWAYS',
    CherryPick: 'CHERRY_PICK',
} as const;
export type SubmitType = typeof SubmitType[keyof typeof SubmitType];


export function instanceOfSubmitType(value: any): boolean {
    for (const key in SubmitType) {
        if (Object.prototype.hasOwnProperty.call(SubmitType, key)) {
            if (SubmitType[key as keyof typeof SubmitType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SubmitTypeFromJSON(json: any): SubmitType {
    return SubmitTypeFromJSONTyped(json, false);
}

export function SubmitTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitType {
    return json as SubmitType;
}

export function SubmitTypeToJSON(value?: SubmitType | null): any {
    return value as any;
}

export function SubmitTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): SubmitType {
    return value as SubmitType;
}

