/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitRequirementInfo
 */
export interface SubmitRequirementInfo {
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    projectName?: string;
    /**
     * 
     */
    applicabilityExpression?: string;
    /**
     * 
     */
    submittabilityExpression?: string;
    /**
     * 
     */
    overrideExpression?: string;
    /**
     * 
     */
    allowOverrideInChildProjects?: boolean;
}

/**
 * Check if a given object implements the SubmitRequirementInfo interface.
 */
export function instanceOfSubmitRequirementInfo(value: object): value is SubmitRequirementInfo {
    return true;
}

export function SubmitRequirementInfoFromJSON(json: any): SubmitRequirementInfo {
    return SubmitRequirementInfoFromJSONTyped(json, false);
}

export function SubmitRequirementInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitRequirementInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'projectName': json['project_name'] == null ? undefined : json['project_name'],
        'applicabilityExpression': json['applicability_expression'] == null ? undefined : json['applicability_expression'],
        'submittabilityExpression': json['submittability_expression'] == null ? undefined : json['submittability_expression'],
        'overrideExpression': json['override_expression'] == null ? undefined : json['override_expression'],
        'allowOverrideInChildProjects': json['allow_override_in_child_projects'] == null ? undefined : json['allow_override_in_child_projects'],
    };
}

export function SubmitRequirementInfoToJSON(json: any): SubmitRequirementInfo {
    return SubmitRequirementInfoToJSONTyped(json, false);
}

export function SubmitRequirementInfoToJSONTyped(value?: SubmitRequirementInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'project_name': value['projectName'],
        'applicability_expression': value['applicabilityExpression'],
        'submittability_expression': value['submittabilityExpression'],
        'override_expression': value['overrideExpression'],
        'allow_override_in_child_projects': value['allowOverrideInChildProjects'],
    };
}

