/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebLinkInfo } from './WebLinkInfo';
import {
    WebLinkInfoFromJSON,
    WebLinkInfoFromJSONTyped,
    WebLinkInfoToJSON,
    WebLinkInfoToJSONTyped,
} from './WebLinkInfo';
import type { GitPerson } from './GitPerson';
import {
    GitPersonFromJSON,
    GitPersonFromJSONTyped,
    GitPersonToJSON,
    GitPersonToJSONTyped,
} from './GitPerson';

/**
 * 
 * @export
 * @interface TagInfo
 */
export interface TagInfo {
    /**
     * The revision of the object to which the tag points.
     */
    object?: string;
    /**
     * The tag message. For signed tags, includes the signature.
     */
    message?: string;
    /**
     * The tagger as a GitPersonInfo entity.
     */
    tagger?: GitPerson;
    /**
     * The timestamp of when the tag was created. For annotated and signed tags, this is the timestamp of the tag object and is the same as the date field in the tagger. For lightweight tags, it is the commit timestamp of the commit to which the tag points, when the object is a commit.
     */
    created?: string;
    /**
     * Links to the tag in external sites as a list of WebLinkInfo entries.
     */
    webLinks?: Array<WebLinkInfo>;
    /**
     * The ref of the tag.
     */
    ref?: string;
    /**
     * For lightweight tags, the revision of the commit to which the tag points. For annotated tags, the revision of the tag object.
     */
    revision?: string;
    /**
     * Whether the calling user can delete this tag.
     */
    canDelete?: boolean;
}

/**
 * Check if a given object implements the TagInfo interface.
 */
export function instanceOfTagInfo(value: object): value is TagInfo {
    return true;
}

export function TagInfoFromJSON(json: any): TagInfo {
    return TagInfoFromJSONTyped(json, false);
}

export function TagInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'] == null ? undefined : json['object'],
        'message': json['message'] == null ? undefined : json['message'],
        'tagger': json['tagger'] == null ? undefined : GitPersonFromJSON(json['tagger']),
        'created': json['created'] == null ? undefined : json['created'],
        'webLinks': json['web_links'] == null ? undefined : ((json['web_links'] as Array<any>).map(WebLinkInfoFromJSON)),
        'ref': json['ref'] == null ? undefined : json['ref'],
        'revision': json['revision'] == null ? undefined : json['revision'],
        'canDelete': json['can_delete'] == null ? undefined : json['can_delete'],
    };
}

export function TagInfoToJSON(json: any): TagInfo {
    return TagInfoToJSONTyped(json, false);
}

export function TagInfoToJSONTyped(value?: TagInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'message': value['message'],
        'tagger': GitPersonToJSON(value['tagger']),
        'created': value['created'],
        'web_links': value['webLinks'] == null ? undefined : ((value['webLinks'] as Array<any>).map(WebLinkInfoToJSON)),
        'ref': value['ref'],
        'revision': value['revision'],
        'can_delete': value['canDelete'],
    };
}

