/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { State } from './State';
import {
    StateFromJSON,
    StateFromJSONTyped,
    StateToJSON,
    StateToJSONTyped,
} from './State';

/**
 * 
 * @export
 * @interface TaskInfo
 */
export interface TaskInfo {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    state?: State;
    /**
     * 
     */
    startTime?: string;
    /**
     * 
     */
    delay?: number;
    /**
     * 
     */
    command?: string;
    /**
     * 
     */
    remoteName?: string;
    /**
     * 
     */
    projectName?: string;
    /**
     * 
     */
    queueName?: string;
}



/**
 * Check if a given object implements the TaskInfo interface.
 */
export function instanceOfTaskInfo(value: object): value is TaskInfo {
    return true;
}

export function TaskInfoFromJSON(json: any): TaskInfo {
    return TaskInfoFromJSONTyped(json, false);
}

export function TaskInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'state': json['state'] == null ? undefined : StateFromJSON(json['state']),
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
        'delay': json['delay'] == null ? undefined : json['delay'],
        'command': json['command'] == null ? undefined : json['command'],
        'remoteName': json['remote_name'] == null ? undefined : json['remote_name'],
        'projectName': json['project_name'] == null ? undefined : json['project_name'],
        'queueName': json['queue_name'] == null ? undefined : json['queue_name'],
    };
}

export function TaskInfoToJSON(json: any): TaskInfo {
    return TaskInfoToJSONTyped(json, false);
}

export function TaskInfoToJSONTyped(value?: TaskInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'state': StateToJSON(value['state']),
        'start_time': value['startTime'],
        'delay': value['delay'],
        'command': value['command'],
        'remote_name': value['remoteName'],
        'project_name': value['projectName'],
        'queue_name': value['queueName'],
    };
}

