/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskSummaryInfo
 */
export interface TaskSummaryInfo {
    /**
     * 
     */
    total?: number;
    /**
     * 
     */
    stopping?: number;
    /**
     * 
     */
    running?: number;
    /**
     * 
     */
    parked?: number;
    /**
     * 
     */
    starting?: number;
    /**
     * 
     */
    ready?: number;
    /**
     * 
     */
    sleeping?: number;
}

/**
 * Check if a given object implements the TaskSummaryInfo interface.
 */
export function instanceOfTaskSummaryInfo(value: object): value is TaskSummaryInfo {
    return true;
}

export function TaskSummaryInfoFromJSON(json: any): TaskSummaryInfo {
    return TaskSummaryInfoFromJSONTyped(json, false);
}

export function TaskSummaryInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskSummaryInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'stopping': json['stopping'] == null ? undefined : json['stopping'],
        'running': json['running'] == null ? undefined : json['running'],
        'parked': json['parked'] == null ? undefined : json['parked'],
        'starting': json['starting'] == null ? undefined : json['starting'],
        'ready': json['ready'] == null ? undefined : json['ready'],
        'sleeping': json['sleeping'] == null ? undefined : json['sleeping'],
    };
}

export function TaskSummaryInfoToJSON(json: any): TaskSummaryInfo {
    return TaskSummaryInfoToJSONTyped(json, false);
}

export function TaskSummaryInfoToJSONTyped(value?: TaskSummaryInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'stopping': value['stopping'],
        'running': value['running'],
        'parked': value['parked'],
        'starting': value['starting'],
        'ready': value['ready'],
        'sleeping': value['sleeping'],
    };
}

