/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopicInput
 */
export interface TopicInput {
    /**
     * 
     */
    topic?: string;
}

/**
 * Check if a given object implements the TopicInput interface.
 */
export function instanceOfTopicInput(value: object): value is TopicInput {
    return true;
}

export function TopicInputFromJSON(json: any): TopicInput {
    return TopicInputFromJSONTyped(json, false);
}

export function TopicInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicInput {
    if (json == null) {
        return json;
    }
    return {
        
        'topic': json['topic'] == null ? undefined : json['topic'],
    };
}

export function TopicInputToJSON(json: any): TopicInput {
    return TopicInputToJSONTyped(json, false);
}

export function TopicInputToJSONTyped(value?: TopicInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'topic': value['topic'],
    };
}

