/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackingIdInfo
 */
export interface TrackingIdInfo {
    /**
     * 
     */
    system?: string;
    /**
     * 
     */
    id?: string;
}

/**
 * Check if a given object implements the TrackingIdInfo interface.
 */
export function instanceOfTrackingIdInfo(value: object): value is TrackingIdInfo {
    return true;
}

export function TrackingIdInfoFromJSON(json: any): TrackingIdInfo {
    return TrackingIdInfoFromJSONTyped(json, false);
}

export function TrackingIdInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackingIdInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'system': json['system'] == null ? undefined : json['system'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function TrackingIdInfoToJSON(json: any): TrackingIdInfo {
    return TrackingIdInfoToJSONTyped(json, false);
}

export function TrackingIdInfoToJSONTyped(value?: TrackingIdInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'system': value['system'],
        'id': value['id'],
    };
}

