/* tslint:disable */
/* eslint-disable */
/**
 * Gerrit Code Review REST API
 * The Gerrit Code Review REST API. Paths, parameters, and payload schemas are generated statically from the server\'s REST bindings; human-authored summaries and descriptions are supplied here and merged in at build time.
 *
 * The version of the OpenAPI document: 3.15.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsernameInput
 */
export interface UsernameInput {
    /**
     * 
     */
    username?: string;
}

/**
 * Check if a given object implements the UsernameInput interface.
 */
export function instanceOfUsernameInput(value: object): value is UsernameInput {
    return true;
}

export function UsernameInputFromJSON(json: any): UsernameInput {
    return UsernameInputFromJSONTyped(json, false);
}

export function UsernameInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsernameInput {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function UsernameInputToJSON(json: any): UsernameInput {
    return UsernameInputToJSONTyped(json, false);
}

export function UsernameInputToJSONTyped(value?: UsernameInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
    };
}

